const minorGodLaneMatrices = {

    amaterasu : [
            [NEW_MOON, KATAGI, TENSHU], // archaic_1  
            [], // archaic_2 
            [AME_NO_UZUME, GOSHINBOKU, AUTOMATON, WIND_SICKLES, KATAGI, GOHEI_WANDS], // classical_1
            [SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
            [HACHIMAN, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
            [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_2
            [WATATSUMI, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO, ASMMETRICAL_BOW], // heroic_3
            [OKUNINUSHI, SACRED_GATE, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
            [], // mythic_2
    ],

    tsukuyomi : [
            [NEW_MOON, KATAGI, TENSHU], // archaic_1  
            [], // archaic_2 
            [AME_NO_UZUME, GOSHINBOKU, AUTOMATON, WIND_SICKLES, KATAGI, GOHEI_WANDS], // classical_1
            [SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
            [HACHIMAN, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
            [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_2
            [WATATSUMI, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO, ASMMETRICAL_BOW], // heroic_3
            [OKUNINUSHI, SACRED_GATE, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
            [], // mythic_2
    ],

    susanoo : [
            [NEW_MOON, KATAGI, TENSHU], // archaic_1  
            [], // archaic_2 
            [AME_NO_UZUME, GOSHINBOKU, AUTOMATON, WIND_SICKLES, KATAGI, GOHEI_WANDS], // classical_1
            [SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
            [HACHIMAN, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
            [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_2
            [WATATSUMI, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO, ASMMETRICAL_BOW], // heroic_3
            [OKUNINUSHI, SACRED_GATE, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
            [], // mythic_2
    ],

    fuxi : [
            [PROSPEROUS_SEEDS, TENSHU, HERBAL_MEDICINE, PEACH_OF_IMMORTALITY],
            [], // archaic_2 
            [HOUTU, EARTH_WALL, QIONGQI, ADVANCED_DEFENSES, CHASING_THE_SUN, ABUNDANCE, SINISTER_DEFIANCE], // classical_1
            [CHIYOU, LIGHTNING_WEAPONS, YAZI, MASTER_OF_WEAPONRY, SPOILS_OF_WAR, SON_OF_LOONG, RAGE_OF_SLAUGHTER], // classical_2
            [RUSHOU, FEI_BEASTS, BAIHU, PIXIU, GILDED_SHIELDS, DIVINE_JUDGMENT, AUTUMN_OF_ABUNDANCE, RED_CLIFFS_FLEET], // heroic_1
            [NUBA, DECONSTRUCTION,TAOTIE, SCORCHING_FEATHERS, ROCK_SOLID, BOTTOMLESS_STOMACH, DROUGHT_SHIPS], // heroic_2
            [ZHURONG, BLAZING_PRAIRIE, ZHUQUE, FLAMING_BLOOD, SLASH_AND_BURN, SONG_OF_MIDSUMMER, SOUTHERN_FIRE], // heroic_3
            [HUANGDI, YINGLONGS_WRATH, HUNDUN, XUANYUANS_BLOODLINE, LEIZUS_SILK, IMPERIAL_ORDER, POWER_OF_CHAOS], // mythic_1
            [], // mythic_2
    ],

    nuwa : [
            [PROSPEROUS_SEEDS, TENSHU, HERBAL_MEDICINE, PEACH_OF_IMMORTALITY],
            [], // archaic_2 
            [HOUTU, EARTH_WALL, QIONGQI, ADVANCED_DEFENSES, CHASING_THE_SUN, ABUNDANCE, SINISTER_DEFIANCE], // classical_1
            [CHIYOU, LIGHTNING_WEAPONS, YAZI, MASTER_OF_WEAPONRY, SPOILS_OF_WAR, SON_OF_LOONG, RAGE_OF_SLAUGHTER], // classical_2
            [RUSHOU, FEI_BEASTS, BAIHU, PIXIU, GILDED_SHIELDS, DIVINE_JUDGMENT, AUTUMN_OF_ABUNDANCE, RED_CLIFFS_FLEET], // heroic_1
            [NUBA, DECONSTRUCTION,TAOTIE, SCORCHING_FEATHERS, ROCK_SOLID, BOTTOMLESS_STOMACH, DROUGHT_SHIPS], // heroic_2
            [ZHURONG, BLAZING_PRAIRIE, ZHUQUE, FLAMING_BLOOD, SLASH_AND_BURN, SONG_OF_MIDSUMMER, SOUTHERN_FIRE], // heroic_3
            [HUANGDI, YINGLONGS_WRATH, HUNDUN, XUANYUANS_BLOODLINE, LEIZUS_SILK, IMPERIAL_ORDER, POWER_OF_CHAOS], // mythic_1
            [], // mythic_2
    ],

    shennong : [
            [PROSPEROUS_SEEDS, TENSHU, HERBAL_MEDICINE, PEACH_OF_IMMORTALITY],
            [], // archaic_2 
            [HOUTU, EARTH_WALL, QIONGQI, ADVANCED_DEFENSES, CHASING_THE_SUN, ABUNDANCE, SINISTER_DEFIANCE], // classical_1
            [CHIYOU, LIGHTNING_WEAPONS, YAZI, MASTER_OF_WEAPONRY, SPOILS_OF_WAR, SON_OF_LOONG, RAGE_OF_SLAUGHTER], // classical_2
            [RUSHOU, FEI_BEASTS, BAIHU, PIXIU, GILDED_SHIELDS, DIVINE_JUDGMENT, AUTUMN_OF_ABUNDANCE, RED_CLIFFS_FLEET], // heroic_1
            [NUBA, DECONSTRUCTION,TAOTIE, SCORCHING_FEATHERS, ROCK_SOLID, BOTTOMLESS_STOMACH, DROUGHT_SHIPS], // heroic_2
            [ZHURONG, BLAZING_PRAIRIE, ZHUQUE, FLAMING_BLOOD, SLASH_AND_BURN, SONG_OF_MIDSUMMER, SOUTHERN_FIRE], // heroic_3
            [HUANGDI, YINGLONGS_WRATH, HUNDUN, XUANYUANS_BLOODLINE, LEIZUS_SILK, IMPERIAL_ORDER, POWER_OF_CHAOS], // mythic_1
            [], // mythic_2
    ],

    ra:[
            [PROSPERITY, FLOOD_OF_THE_NILE], // archaic_1
            [], // archaic_2
            [BAST, ECLIPSE, SPHINX, SACRED_CATS, ADZE_OF_WEPWAWET, CRIOSPHINX, HIERACOSPHINX], // classical_1
            [ANUBIS, PLAGUE_OF_SERPENTS, ANUBITE, FEET_OF_THE_JACKAL, SERPENT_SPEAR, NECROPOLIS], // classical_2
            [SOBEK_HATHOR, LOCUST_SWARM, ROC, PETSUCHOS, CROCODILOPOLIS, SUN_DRIED_MUD_BRICK, DARK_WATER, SOLAR_BARQUE], // heroic_1
            [NEPHTHYS, ANCESTORS, SCORPION_MAN, FUNERAL_RITES, SPIRIT_OF_MAAT, NEBTY, FUNERAL_BARGE], // heroic_2
            [OSIRIS, SON_OF_OSIRIS, MUMMY, DESERT_WIND, NEW_KINGDOM, ATEF_CROWN], // heroic_3
            [THOTH, METEOR, PHOENIX, VALLEY_OF_THE_KINGS, BOOK_OF_THOTH, TUSKS_OF_APEDEMAK], // mythic_1
            [], // mythic_2
    ],

    isis:[
            [PROSPERITY, FLOOD_OF_THE_NILE], // archaic_1
            [], // archaic_2
            [BAST, ECLIPSE, SPHINX, SACRED_CATS, ADZE_OF_WEPWAWET, CRIOSPHINX, HIERACOSPHINX], // classical_1
            [ANUBIS, PLAGUE_OF_SERPENTS, ANUBITE, FEET_OF_THE_JACKAL, SERPENT_SPEAR, NECROPOLIS], // classical_2
            [SOBEK_HATHOR, LOCUST_SWARM, ROC, PETSUCHOS, CROCODILOPOLIS, SUN_DRIED_MUD_BRICK, DARK_WATER, SOLAR_BARQUE], // heroic_1
            [NEPHTHYS, ANCESTORS, SCORPION_MAN, FUNERAL_RITES, SPIRIT_OF_MAAT, NEBTY, FUNERAL_BARGE], // heroic_2
            [OSIRIS, SON_OF_OSIRIS, MUMMY, DESERT_WIND, NEW_KINGDOM, ATEF_CROWN], // heroic_3
            [THOTH, METEOR, PHOENIX, VALLEY_OF_THE_KINGS, BOOK_OF_THOTH, TUSKS_OF_APEDEMAK], // mythic_1
            [], // mythic_2
    ],

    set:[
            [PROSPERITY, FLOOD_OF_THE_NILE], // archaic_1
            [], // archaic_2
            [BAST, ECLIPSE, SPHINX, SACRED_CATS, ADZE_OF_WEPWAWET, CRIOSPHINX, HIERACOSPHINX], // classical_1
            [ANUBIS, PLAGUE_OF_SERPENTS, ANUBITE, FEET_OF_THE_JACKAL, SERPENT_SPEAR, NECROPOLIS], // classical_2
            [SOBEK_HATHOR, LOCUST_SWARM, ROC, PETSUCHOS, CROCODILOPOLIS, SUN_DRIED_MUD_BRICK, DARK_WATER, SOLAR_BARQUE], // heroic_1
            [NEPHTHYS, ANCESTORS, SCORPION_MAN, FUNERAL_RITES, SPIRIT_OF_MAAT, NEBTY, FUNERAL_BARGE], // heroic_2
            [OSIRIS, SON_OF_OSIRIS, MUMMY, DESERT_WIND, NEW_KINGDOM, ATEF_CROWN], // heroic_3
            [THOTH, METEOR, PHOENIX, VALLEY_OF_THE_KINGS, BOOK_OF_THOTH, TUSKS_OF_APEDEMAK], // mythic_1
            [], // mythic_2
    ],

    zeus : [
            [BOLT, OLYMPIAN_PARENTAGE], // archaic_1
            [], // archaic_2
            [ATHENA, RESTORATION, MINOTAUR, LABYRINTH_OF_MINOS, AEGIS_SHIELD, SARISSA], // classical_1
            [HERMES, CEASEFIRE, CENTAUR, SYLVAN_LORE, SPIRITED_CHARGE, WINGED_MESSENGER], // classical_2
            [APOLLO, UNDERWORLD_PASSAGE, MANTICORE, ORACLE, TEMPLE_OF_HEALING, SUN_RAY, ANASTROPHE], // heroic_1
            [DIONYSUS,BRONZE, HYDRA, CHTHONIC_RITES, DIONYSIA, THRACIAN_HORSES], // heroic_2
            [HEPHAESTUS, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
            [HERA, LIGHTNING_STORM, MEDUSA, ARGIVE_PATRONAGE, FACE_OF_THE_GORGON, MONSTROUS_RAGE], // mythic_1
            [], // mythic_2
    ],

    hades : [
            [BOLT, OLYMPIAN_PARENTAGE], // archaic_1
            [], // archaic_2
            [ATHENA, RESTORATION, MINOTAUR, LABYRINTH_OF_MINOS, AEGIS_SHIELD, SARISSA], // classical_1
            [HERMES, CEASEFIRE, CENTAUR, SYLVAN_LORE, SPIRITED_CHARGE, WINGED_MESSENGER], // classical_2
            [APOLLO, UNDERWORLD_PASSAGE, MANTICORE, ORACLE, TEMPLE_OF_HEALING, SUN_RAY, ANASTROPHE], // heroic_1
            [DIONYSUS,BRONZE, HYDRA, CHTHONIC_RITES, DIONYSIA, THRACIAN_HORSES], // heroic_2
            [HEPHAESTUS, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
            [HERA, LIGHTNING_STORM, MEDUSA, ARGIVE_PATRONAGE, FACE_OF_THE_GORGON, MONSTROUS_RAGE], // mythic_1
            [], // mythic_2
    ],

    poseidon : [
            [BOLT, OLYMPIAN_PARENTAGE], // archaic_1
            [], // archaic_2
            [ATHENA, RESTORATION, MINOTAUR, LABYRINTH_OF_MINOS, AEGIS_SHIELD, SARISSA], // classical_1
            [HERMES, CEASEFIRE, CENTAUR, SYLVAN_LORE, SPIRITED_CHARGE, WINGED_MESSENGER], // classical_2
            [APOLLO, UNDERWORLD_PASSAGE, MANTICORE, ORACLE, TEMPLE_OF_HEALING, SUN_RAY, ANASTROPHE], // heroic_1
            [DIONYSUS,BRONZE, HYDRA, CHTHONIC_RITES, DIONYSIA, THRACIAN_HORSES], // heroic_2
            [HEPHAESTUS, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
            [HERA, LIGHTNING_STORM, MEDUSA, ARGIVE_PATRONAGE, FACE_OF_THE_GORGON, MONSTROUS_RAGE], // mythic_1
            [], // mythic_2
    ],

    thor: [
            [DWARVEN_MINE, DWARVEN_ARMORY, HAMMER_OF_THUNDER], // archaic_1
            [], // archaic_2
            [FREYJA, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
            [FORSETI, HEALING_SPRING, TROLL, HALL_OF_THANES, DWARVEN_BREASTPLATE, CAVE_TROLL], // classical_2
            [SKADI, FROST, FROST_GIANT, RIME, HUNTRESS_AXE, WINTER_HARVEST, ARCTIC_WINDS], // heroic_1
            [BRAGI, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_2
            [BALDR, RAGNAROK, FIRE_GIANT, SONS_OF_SLEIPNIR, DWARVEN_AUGER], // heroic_3
            [TYR, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
            [], // mythic_2
    ],

    odin: [
        [GREAT_HUNT, HAMASK, HAMASK], // archaic_1
        [], // archaic_2
        [FREYJA, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
        [HEIMDALL, UNDERMINE, EINHERI, GJALLARHORN, SAFEGUARD, RIGSTHULA], // classical_2
        [SKADI, FROST, FROST_GIANT, RIME, HUNTRESS_AXE, WINTER_HARVEST, ARCTIC_WINDS], // heroic_1
        [NJORD, WALKING_WOODS, MOUNTAIN_GIANT, RING_GIVER, VIKINGS, JOTUNS, WRATH_OF_THE_DEEP], // heroic_2
        [BALDR, RAGNAROK, FIRE_GIANT, SONS_OF_SLEIPNIR, DWARVEN_AUGER], // heroic_3
        [TYR, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
        [], // mythic_2
    ],

    loki: [
            [SPY, EYES_IN_THE_FOREST], // archaic_1
            [], // archaic_2
            [FORSETI, HEALING_SPRING, TROLL, HALL_OF_THANES, DWARVEN_BREASTPLATE, CAVE_TROLL], // classical_1
            [HEIMDALL, UNDERMINE, EINHERI, GJALLARHORN, SAFEGUARD, RIGSTHULA], // classical_2
            [BRAGI, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_1
            [NJORD, WALKING_WOODS, MOUNTAIN_GIANT, RING_GIVER, VIKINGS, JOTUNS, WRATH_OF_THE_DEEP], // heroic_2
            [HEL, NIDHOGG, FIRE_GIANT, FROST_GIANT, MOUNTAIN_GIANT, RAMPAGE, GRANITE_BLOOD], // heroic_3
            [TYR, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
            [], // mythic_2
    ],

     
    freyr : [
            [GULLINBURSTI, FREYRS_GIFT], // archaic_1
            [], // archaic_2
            [FREYJA, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
            [ULLR, ASGARDIAN_BASTION, DRAUGR, VALGALDR, SERVANTS_OF_GLORY, RING_OATH, YDALIR], // classical_2
            [BRAGI, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_1
            [AEGIR, TEMPEST, ROCK_GIANT, GRANITE_MAW, FEASTS_OF_RENOWN, NINE_WAVES, GRASP_OF_RAN], // heroic_2
            [HEL, NIDHOGG, FIRE_GIANT, FROST_GIANT, MOUNTAIN_GIANT, RAMPAGE, GRANITE_BLOOD], // heroic_3
            [VIDAR, INFERNO, FAFNIR, TWILIGHT_OF_THE_GODS, AVENGING_SPIRIT, SILENT_RESOLVE, FURY_OF_THE_FALLEN], // mythic_1
            [], // mythic_2
    ],

    kronos: [
            [DECONSTRUCTION, TEMPORAL_CHAOS], // archaic_1
            [], // archaic_2
            [PROMETHEUS, VALOR, PROMETHEAN, ALLUVIAL_CLAY, HEART_OF_THE_TITANS, THEFT_OF_FIRE], // classical_1
            [LETO, SPIDER_LAIR, AUTOMATON, HEPHAESTUS_REVENGE, VOLCANIC_FORGE, PERCEPTION], // classical_2
            [HYPERION, CHAOS, SATYR, GEMINI, HEROIC_RENEWAL, SONS_OF_THE_SUN, PIONEER_OF_THE_SKIES], // heroic_1
            [RHEIA, TRAITOR, BEHEMOTH, HORNS_OF_CONSECRATION, ORICHALCUM_MAIL, RHEIAS_GIFT, DAKTYLOI], // heroic_2
            [HELIOS, VORTEX, CENTIMANUS, MIRROR_TOWER, HALO_OF_THE_SUN, PETRIFICATION, TITANOMACHY], // heroic_3
            [ATLAS, IMPLODE, ARGUS, GUARDIAN_OF_IO, DEVOTEES_OF_ATLAS, TITAN_SHIELD], // mythic_1
            [], // mythic_2
    ],

    oranos : [
            [DECONSTRUCTION, TEMPORAL_CHAOS], // archaic_1
            [], // archaic_2
            [PROMETHEUS, VALOR, PROMETHEAN, ALLUVIAL_CLAY, HEART_OF_THE_TITANS, THEFT_OF_FIRE], // classical_1
            [LETO, SPIDER_LAIR, AUTOMATON, HEPHAESTUS_REVENGE, VOLCANIC_FORGE, PERCEPTION], // classical_2
            [HYPERION, CHAOS, SATYR, GEMINI, HEROIC_RENEWAL, SONS_OF_THE_SUN, PIONEER_OF_THE_SKIES], // heroic_1
            [RHEIA, TRAITOR, BEHEMOTH, HORNS_OF_CONSECRATION, ORICHALCUM_MAIL, RHEIAS_GIFT, DAKTYLOI], // heroic_2
            [HELIOS, VORTEX, CENTIMANUS, MIRROR_TOWER, HALO_OF_THE_SUN, PETRIFICATION, TITANOMACHY], // heroic_3
            [ATLAS, IMPLODE, ARGUS, GUARDIAN_OF_IO, DEVOTEES_OF_ATLAS, TITAN_SHIELD], // mythic_1
            [], // mythic_2
    ],

    gaia : [
            [DECONSTRUCTION, TEMPORAL_CHAOS], // archaic_1
            [], // archaic_2
            [PROMETHEUS, VALOR, PROMETHEAN, ALLUVIAL_CLAY, HEART_OF_THE_TITANS, THEFT_OF_FIRE], // classical_1
            [LETO, SPIDER_LAIR, AUTOMATON, HEPHAESTUS_REVENGE, VOLCANIC_FORGE, PERCEPTION], // classical_2
            [HYPERION, CHAOS, SATYR, GEMINI, HEROIC_RENEWAL, SONS_OF_THE_SUN, PIONEER_OF_THE_SKIES], // heroic_1
            [RHEIA, TRAITOR, BEHEMOTH, HORNS_OF_CONSECRATION, ORICHALCUM_MAIL, RHEIAS_GIFT, DAKTYLOI], // heroic_2
            [HELIOS, VORTEX, CENTIMANUS, MIRROR_TOWER, HALO_OF_THE_SUN, PETRIFICATION, TITANOMACHY], // heroic_3
            [ATLAS, IMPLODE, ARGUS, GUARDIAN_OF_IO, DEVOTEES_OF_ATLAS, TITAN_SHIELD], // mythic_1
            [], // mythic_2
    ],

}



    

    
    

    


    
    
    // TSUKUYOMI

    // minorGodLaneMatrix = [
    //         [NEW_MOON, KATAGI, TENSHU], // archaic_1  
    //         [], // archaic_2 
    //         [AME_NO_UZUME, GOSHINBOKU, AUTOMATON, WIND_SICKLES, KATAGI, GOHEI_WANDS], // classical_1
    //         [SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
    //         [HACHIMAN, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
    //         [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_2
    //         [WATATSUMI, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO, ASMMETRICAL_BOW], // heroic_3
    //         [OKUNINUSHI, SACRED_GATE, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
    //         [], // mythic_2
    // ];

    