const TYPES = Object.freeze({
    'BUILDING': {colour: '#922602', type: 'BUILDING', name: 'Building'},
    'UNIT': {colour: '#3a6a80', type: 'UNIT', name: 'Unit'},
    // 'UNIQUEUNIT': {colour: '#af30a3', type: 'UNIQUEUNIT', name: 'Unique Unit'},
    'TECHNOLOGY': {colour: '#2c5729', type: 'TECHNOLOGY', name: 'Technology'},
    'BLANK': {colour: '#000000', type: 'BLANK', name: 'Blank', opacity: 0},
});

const PREFIX = Object.freeze({
    'BUILDING': 'building_',
    'UNIT': 'unit_',
    'TECHNOLOGY': 'tech_',       
});

AGE_IMAGES = ['archaic_age_icon.webp', 'classical_age_icon.webp', 'heroic_age_icon.webp', 'mythic_age_icon.webp'];


ACHILLES_HERO = {id: 0, name: 'ACHILLES_HERO'};
AJAX_HERO = {id: 1, name: 'AJAX_HERO'};
ANUBITE = {id: 2, name: 'ANUBITE'};
ARCUS_HERO = {id: 3, name: 'ARCUS_HERO'};
ARCUS = {id: 4, name: 'ARCUS'};
ARGUS = {id: 5, name: 'ARGUS'};
ASURA = {id: 6, name: 'ASURA'};
ATALANTA_HERO = {id: 7, name: 'ATALANTA_HERO'};
AUTOMATON = {id: 8, name: 'AUTOMATON'};
AVENGER = {id: 9, name: 'AVENGER'};
AXE_CART = {id: 10, name: 'AXE_CART'};
AXEMAN = {id: 11, name: 'AXEMAN'};
BAIHU = {id: 12, name: 'BAIHU'};
BALLISTA = {id: 13, name: 'BALLISTA'};
BATTLE_BOAR = {id: 14, name: 'BATTLE_BOAR'};
BEHEMOTH = {id: 15, name: 'BEHEMOTH'};
BELLEROPHON_HERO = {id: 16, name: 'BELLEROPHON_HERO'};
BERSERK = {id: 17, name: 'BERSERK'};
BIREME = {id: 18, name: 'BIREME'};
BUSHI_HERO = {id: 19, name: 'BUSHI_HERO'};
CALADRIA = {id: 20, name: 'CALADRIA'};
CAMEL_CARAVAN = {id: 21, name: 'CAMEL_CARAVAN'};
CAMEL_RIDER = {id: 22, name: 'CAMEL_RIDER'};
CARCINOS = {id: 23, name: 'CARCINOS'};
CARNIVORA = {id: 24, name: 'CARNIVORA'};
CATAPULT = {id: 25, name: 'CATAPULT'};
CENTAUR = {id: 26, name: 'CENTAUR'};
CENTIMANUS = {id: 27, name: 'CENTIMANUS'};
CHARIOT_ARCHER = {id: 28, name: 'CHARIOT_ARCHER'};
CHEIROBALLISTA_HERO = {id: 29, name: 'CHEIROBALLISTA_HERO'};
CHEIROBALLISTA = {id: 30, name: 'CHEIROBALLISTA'};
CHIMERA = {id: 31, name: 'CHIMERA'};
CHIRON_HERO = {id: 32, name: 'CHIRON_HERO'};
CHIWEN = {id: 33, name: 'CHIWEN'};
CHU_KO_NU = {id: 34, name: 'CHU_KO_NU'};
CITIZEN_HERO = {id: 35, name: 'CITIZEN_HERO'};
CITIZEN = {id: 36, name: 'CITIZEN'};
COLOSSUS = {id: 37, name: 'COLOSSUS'};
COMMONER = {id: 38, name: 'COMMONER'};
CONTARIUS_HERO = {id: 39, name: 'CONTARIUS_HERO'};
CONTARIUS = {id: 40, name: 'CONTARIUS'};
CYCLOPS = {id: 41, name: 'CYCLOPS'};
DAIMYO_HERO = {id: 42, name: 'DAIMYO_HERO'};
DAO_SWORDSMAN = {id: 43, name: 'DAO_SWORDSMAN'};
DEER_CARAVAN = {id: 44, name: 'DEER_CARAVAN'};
DESTROYER_HERO = {id: 45, name: 'DESTROYER_HERO'};
DESTROYER = {id: 46, name: 'DESTROYER'};
DONKEY_CARAVAN = {id: 47, name: 'DONKEY_CARAVAN'};
DOUJIAN = {id: 48, name: 'DOUJIAN'};
DRAGON_SHIP = {id: 49, name: 'DRAGON_SHIP'};
DRAUGR = {id: 50, name: 'DRAUGR'};
DREKI = {id: 51, name: 'DREKI'};
DRYAD = {id: 52, name: 'DRYAD'};
DWARF = {id: 53, name: 'DWARF'};
EINHERI = {id: 54, name: 'EINHERI'};
FAFNIR = {id: 55, name: 'FAFNIR'};
FANATIC_HERO = {id: 56, name: 'FANATIC_HERO'};
FANATIC = {id: 57, name: 'FANATIC'};
FEI = {id: 58, name: 'FEI'};
FENRIS_WOLF_BROOD = {id: 59, name: 'FENRIS_WOLF_BROOD'};
FIMBULWINTER_WOLF = {id: 60, name: 'FIMBULWINTER_WOLF'};
FIRE_ARCHER = {id: 61, name: 'FIRE_ARCHER'};
FIRE_GIANT = {id: 62, name: 'FIRE_GIANT'};
FIRE_SHIP = {id: 63, name: 'FIRE_SHIP'};
FIRE_SIPHON = {id: 64, name: 'FIRE_SIPHON'};
FISHING_SHIP_ATLANTEAN = {id: 65, name: 'FISHING_SHIP_ATLANTEAN'};
FISHING_SHIP_CHINESE = {id: 66, name: 'FISHING_SHIP_CHINESE'};
FISHING_SHIP_EGYPTIAN = {id: 67, name: 'FISHING_SHIP_EGYPTIAN'};
FISHING_SHIP_GREEK = {id: 68, name: 'FISHING_SHIP_GREEK'};
FISHING_SHIP_JAPANESE = {id: 69, name: 'FISHING_SHIP_JAPANESE'};
FISHING_SHIP_NORSE = {id: 70, name: 'FISHING_SHIP_NORSE'};
FROST_GIANT = {id: 71, name: 'FROST_GIANT'};
GASTRAPHETOROS = {id: 72, name: 'GASTRAPHETOROS'};
GATHERER = {id: 73, name: 'GATHERER'};
GE_HALBERDIER = {id: 74, name: 'GE_HALBERDIER'};
GODI_HERO = {id: 75, name: 'GODI_HERO'};
HATAMOTO_SAMURAI = {id: 76, name: 'HATAMOTO_SAMURAI'};
HELEPOLIS = {id: 77, name: 'HELEPOLIS'};
HERACLES_HERO = {id: 78, name: 'HERACLES_HERO'};
HERO_OF_RAGNAROK_DWARF = {id: 79, name: 'HERO_OF_RAGNAROK_DWARF'};
HERO_OF_RAGNAROK = {id: 80, name: 'HERO_OF_RAGNAROK'};
HERSIR_HERO = {id: 81, name: 'HERSIR_HERO'};
HETAIROS = {id: 82, name: 'HETAIROS'};
HIPPEUS = {id: 83, name: 'HIPPEUS'};
HIPPOCAMPUS = {id: 84, name: 'HIPPOCAMPUS'};
HIPPOLYTA_HERO = {id: 85, name: 'HIPPOLYTA_HERO'};
HIRDMAN = {id: 86, name: 'HIRDMAN'};
HONENGYO = {id: 87, name: 'HONENGYO'};
HOPLITE = {id: 88, name: 'HOPLITE'};
HUNDUN = {id: 89, name: 'HUNDUN'};
HUSKARL = {id: 90, name: 'HUSKARL'};
HYDRA = {id: 91, name: 'HYDRA'};
HYPASPIST = {id: 92, name: 'HYPASPIST'};
JARL = {id: 93, name: 'JARL'};
JASON_HERO = {id: 94, name: 'JASON_HERO'};
JIANG_ZIYA_HERO = {id: 95, name: 'JIANG_ZIYA_HERO'};
JORMUN_ELVER = {id: 96, name: 'JORMUN_ELVER'};
JOROGUMO = {id: 97, name: 'JOROGUMO'};
JUGGERNAUT = {id: 98, name: 'JUGGERNAUT'};
JUNKOZOSEN = {id: 99, name: 'JUNKOZOSEN'};
KATAPELTES_HERO = {id: 100, name: 'KATAPELTES_HERO'};
KATAPELTES = {id: 101, name: 'KATAPELTES'};
KEBENIT = {id: 102, name: 'KEBENIT'};
KITSUNE = {id: 103, name: 'KITSUNE'};
KRAKEN = {id: 104, name: 'KRAKEN'};
KUAFU = {id: 105, name: 'KUAFU'};
LABORER = {id: 106, name: 'LABORER'};
LAMPADES = {id: 107, name: 'LAMPADES'};
LEVIATHAN = {id: 108, name: 'LEVIATHAN'};
LI_JING_HERO = {id: 109, name: 'LI_JING_HERO'};
LLAMA_CARAVAN = {id: 110, name: 'LLAMA_CARAVAN'};
LONGBOAT = {id: 111, name: 'LONGBOAT'};
LOUCHUAN = {id: 112, name: 'LOUCHUAN'};
MAN_O_WAR = {id: 113, name: 'MAN_O_WAR'};
MANTICORE = {id: 114, name: 'MANTICORE'};
MASTERLESS_SWORD = {id: 115, name: 'MASTERLESS_SWORD'};
MECHANICAL_OX_CARAVAN = {id: 116, name: 'MECHANICAL_OX_CARAVAN'};
MEDUSA = {id: 117, name: 'MEDUSA'};
MENGCHONG = {id: 118, name: 'MENGCHONG'};
MERCENARY_CAVALRY = {id: 119, name: 'MERCENARY_CAVALRY'};
MERCENARY = {id: 120, name: 'MERCENARY'};
MIKO_HERO = {id: 121, name: 'MIKO_HERO'};
MILITIA = {id: 122, name: 'MILITIA'};
MINION_REINCARNATED = {id: 123, name: 'MINION_REINCARNATED'};
MINION = {id: 124, name: 'MINION'};
MINOTAUR = {id: 125, name: 'MINOTAUR'};
MOUNTAIN_GIANT = {id: 126, name: 'MOUNTAIN_GIANT'};
MUMMY = {id: 127, name: 'MUMMY'};
MURMILLO_HERO = {id: 128, name: 'MURMILLO_HERO'};
MURMILLO = {id: 129, name: 'MURMILLO'};
MYRMIDON = {id: 130, name: 'MYRMIDON'};
NAGINATA_RIDER = {id: 131, name: 'NAGINATA_RIDER'};
NEMEAN_LION = {id: 132, name: 'NEMEAN_LION'};
NEREID = {id: 133, name: 'NEREID'};
NEZHA_HERO_CHILD = {id: 134, name: 'NEZHA_HERO_CHILD'};
NEZHA_HERO_YOUTH = {id: 135, name: 'NEZHA_HERO_YOUTH'};
NEZHA_HERO = {id: 136, name: 'NEZHA_HERO'};
NIDHOGG = {id: 137, name: 'NIDHOGG'};
ODYSSEUS_HERO = {id: 138, name: 'ODYSSEUS_HERO'};
ONI = {id: 139, name: 'ONI'};
ONMORAKI = {id: 140, name: 'ONMORAKI'};
ONMYOJI_HERO = {id: 141, name: 'ONMYOJI_HERO'};
ONNA_MUSHA_HERO = {id: 142, name: 'ONNA_MUSHA_HERO'};
ORACLE_HERO = {id: 143, name: 'ORACLE_HERO'};
ORACLE = {id: 144, name: 'ORACLE'};
OX_CARAVAN = {id: 145, name: 'OX_CARAVAN'};
OX_CART = {id: 146, name: 'OX_CART'};
OYUMI = {id: 147, name: 'OYUMI'};
PEASANT = {id: 148, name: 'PEASANT'};
PEGASUS = {id: 149, name: 'PEGASUS'};
PELTAST = {id: 150, name: 'PELTAST'};
PENTEKONTER = {id: 151, name: 'PENTEKONTER'};
PERSEUS_HERO = {id: 152, name: 'PERSEUS_HERO'};
PETROBOLOS = {id: 153, name: 'PETROBOLOS'};
PETSUCHOS = {id: 154, name: 'PETSUCHOS'};
PHARAOH_HERO_NEW_KINGDOM = {id: 155, name: 'PHARAOH_HERO_NEW_KINGDOM'};
PHARAOH_HERO = {id: 156, name: 'PHARAOH_HERO'};
PHOENIX = {id: 157, name: 'PHOENIX'};
PIONEER_HERO = {id: 158, name: 'PIONEER_HERO'};
PIXIU = {id: 159, name: 'PIXIU'};
POLYPHEMUS_HERO = {id: 160, name: 'POLYPHEMUS_HERO'};
PORTABLE_RAM = {id: 161, name: 'PORTABLE_RAM'};
PRIEST_HERO = {id: 162, name: 'PRIEST_HERO'};
PRODROMOS = {id: 163, name: 'PRODROMOS'};
PROMETHEAN_OFFSPRING = {id: 164, name: 'PROMETHEAN_OFFSPRING'};
PROMETHEAN = {id: 165, name: 'PROMETHEAN'};
QILIN = {id: 166, name: 'QILIN'};
QINGLONG = {id: 167, name: 'QINGLONG'};
QIONGQI_AIR = {id: 168, name: 'QIONGQI_AIR'};
QIONGQI = {id: 169, name: 'QIONGQI'};
RAIDING_CAVALRY = {id: 170, name: 'RAIDING_CAVALRY'};
RAIJU = {id: 171, name: 'RAIJU'};
RAMMING_GALLEY = {id: 172, name: 'RAMMING_GALLEY'};
RAMMING_WASEN = {id: 173, name: 'RAMMING_WASEN'};
REVENANT_SHIMIGAMI = {id: 174, name: 'REVENANT_SHIMIGAMI'};
ROC = {id: 175, name: 'ROC'};
ROCK_GIANT = {id: 176, name: 'ROCK_GIANT'};
SAGE_HERO = {id: 177, name: 'SAGE_HERO'};
SAMURAI = {id: 178, name: 'SAMURAI'};
SATYR = {id: 179, name: 'SATYR'};
SCARAB = {id: 180, name: 'SCARAB'};
SCORPION_MAN = {id: 181, name: 'SCORPION_MAN'};
SCYLLA = {id: 182, name: 'SCYLLA'};
SEA_SNAKE = {id: 183, name: 'SEA_SNAKE'};
SERPENT = {id: 184, name: 'SERPENT'};
SERVANT = {id: 185, name: 'SERVANT'};
SHINIGAMI = {id: 186, name: 'SHINIGAMI'};
SHINOBI = {id: 187, name: 'SHINOBI'};
SHOGUN_HERO = {id: 188, name: 'SHOGUN_HERO'};
SIEGE_BIREME = {id: 189, name: 'SIEGE_BIREME'};
SIEGE_CROSSBOW = {id: 190, name: 'SIEGE_CROSSBOW'};
SIEGE_TOWER = {id: 191, name: 'SIEGE_TOWER'};
SKY_LANTERN = {id: 192, name: 'SKY_LANTERN'};
SLINGER = {id: 193, name: 'SLINGER'};
SON_OF_OSIRIS_HERO = {id: 194, name: 'SON_OF_OSIRIS_HERO'};
SPEARMAN = {id: 195, name: 'SPEARMAN'};
SPHINX = {id: 196, name: 'SPHINX'};
STYMPHALIAN_BIRD = {id: 197, name: 'STYMPHALIAN_BIRD'};
TAOTIE = {id: 198, name: 'TAOTIE'};
TAOWU = {id: 199, name: 'TAOWU'};
TENGU = {id: 200, name: 'TENGU'};
THE_ARGO_HERO = {id: 201, name: 'THE_ARGO_HERO'};
THESEUS = {id: 202, name: 'THESEUS'};
THROWING_AXEMAN = {id: 203, name: 'THROWING_AXEMAN'};
TIGER_CAVALRY_DISMOUNTED = {id: 204, name: 'TIGER_CAVALRY_DISMOUNTED'};
TIGER_CAVALRY = {id: 205, name: 'TIGER_CAVALRY'};
TITAN_ATLANTEAN = {id: 206, name: 'TITAN_ATLANTEAN'};
TITAN_CHINESE = {id: 207, name: 'TITAN_CHINESE'};
TITAN_EGYPTIAN = {id: 208, name: 'TITAN_EGYPTIAN'};
TITAN_GREEK = {id: 209, name: 'TITAN_GREEK'};
TITAN_JAPANESE = {id: 210, name: 'TITAN_JAPANESE'};
TITAN_NORSE = {id: 211, name: 'TITAN_NORSE'};
TOXOTES = {id: 212, name: 'TOXOTES'};
TRANSPORT_SHIP_ATLANTEAN = {id: 213, name: 'TRANSPORT_SHIP_ATLANTEAN'};
TRANSPORT_SHIP_CHINESE = {id: 214, name: 'TRANSPORT_SHIP_CHINESE'};
TRANSPORT_SHIP_EGYPTIAN = {id: 215, name: 'TRANSPORT_SHIP_EGYPTIAN'};
TRANSPORT_SHIP_GREEK = {id: 216, name: 'TRANSPORT_SHIP_GREEK'};
TRANSPORT_SHIP_JAPANESE = {id: 217, name: 'TRANSPORT_SHIP_JAPANESE'};
TRANSPORT_SHIP_NORSE = {id: 218, name: 'TRANSPORT_SHIP_NORSE'};
TRIREME = {id: 219, name: 'TRIREME'};
TROLL = {id: 220, name: 'TROLL'};
TURMA_HERO = {id: 221, name: 'TURMA_HERO'};
TURMA = {id: 222, name: 'TURMA'};
UMIBOZU = {id: 223, name: 'UMIBOZU'};
VALKYRIE = {id: 224, name: 'VALKYRIE'};
VENGEFUL_SHINIGAMI = {id: 225, name: 'VENGEFUL_SHINIGAMI'};
VILLAGER_GREEK = {id: 226, name: 'VILLAGER_GREEK'};
WADJET = {id: 227, name: 'WADJET'};
WALKING_WOODS = {id: 228, name: 'WALKING_WOODS'};
WANYUDO = {id: 229, name: 'WANYUDO'};
WAR_BARGE = {id: 230, name: 'WAR_BARGE'};
WAR_ELEPHANT = {id: 231, name: 'WAR_ELEPHANT'};
WAR_TURTLE = {id: 232, name: 'WAR_TURTLE'};
WASEN = {id: 233, name: 'WASEN'};
WATER_CARNIVORA = {id: 234, name: 'WATER_CARNIVORA'};
WEN_ZHONG_HERO = {id: 235, name: 'WEN_ZHONG_HERO'};
WHITE_HORSE_CAVALRY = {id: 236, name: 'WHITE_HORSE_CAVALRY'};
WRETCH = {id: 237, name: 'WRETCH'};
WUZU_JAVELINEER = {id: 238, name: 'WUZU_JAVELINEER'};
XUANWU = {id: 239, name: 'XUANWU'};
YANG_JIAN_HERO = {id: 240, name: 'YANG_JIAN_HERO'};
YARI_SPEARMAN = {id: 241, name: 'YARI_SPEARMAN'};
YAZI = {id: 242, name: 'YAZI'};
YINGLONG = {id: 243, name: 'YINGLONG'};
YUMI_ARCHER = {id: 244, name: 'YUMI_ARCHER'};
YUMI_HORSE_ARCHER = {id: 245, name: 'YUMI_HORSE_ARCHER'};
ZHUQUE_LANDED = {id: 246, name: 'ZHUQUE_LANDED'};
ZHUQUE = {id: 247, name: 'ZHUQUE'};
ARCHERY_RANGE = {id: 248, name: 'ARCHERY_RANGE'};
ARMORY_ATLANTEAN = {id: 249, name: 'ARMORY_ATLANTEAN'};
ARMORY_CHINESE = {id: 250, name: 'ARMORY_CHINESE'};
ARMORY_EGYPTIANS = {id: 251, name: 'ARMORY_EGYPTIANS'};
ARMORY_GREEK = {id: 252, name: 'ARMORY_GREEK'};
ARMORY_JAPANESE = {id: 253, name: 'ARMORY_JAPANESE'};
ARMORY_NORSE = {id: 254, name: 'ARMORY_NORSE'};
BAOLEI = {id: 255, name: 'BAOLEI'};
BARRACKS = {id: 256, name: 'BARRACKS'};
CASTLE = {id: 257, name: 'CASTLE'};
CITADEL_CENTER_ATLANTEAN = {id: 258, name: 'CITADEL_CENTER_ATLANTEAN'};
CITADEL_CENTER_CHINESE = {id: 259, name: 'CITADEL_CENTER_CHINESE'};
CITADEL_CENTER_EGYPTIAN = {id: 260, name: 'CITADEL_CENTER_EGYPTIAN'};
CITADEL_CENTER_GREEK = {id: 261, name: 'CITADEL_CENTER_GREEK'};
CITADEL_CENTER_NORSE = {id: 262, name: 'CITADEL_CENTER_NORSE'};
COUNTER_BARRACKS = {id: 263, name: 'COUNTER_BARRACKS'};
DOCK_ATLANTEAN = {id: 264, name: 'DOCK_ATLANTEAN'};
DOCK_CHINESE = {id: 265, name: 'DOCK_CHINESE'};
DOCK_EGYPTIAN = {id: 266, name: 'DOCK_EGYPTIAN'};
DOCK_GREEK = {id: 267, name: 'DOCK_GREEK'};
DOCK_JAPANESE = {id: 268, name: 'DOCK_JAPANESE'};
DOCK_NORSE = {id: 269, name: 'DOCK_NORSE'};
DOJO = {id: 270, name: 'DOJO'};
DWARVEN_ARMORY = {id: 271, name: 'DWARVEN_ARMORY'};
ECONOMIC_GUILD = {id: 272, name: 'ECONOMIC_GUILD'};
FARM_ATLANTEAN = {id: 273, name: 'FARM_ATLANTEAN'};
FARM_CHINESE = {id: 274, name: 'FARM_CHINESE'};
FARM_EGYPTIAN = {id: 275, name: 'FARM_EGYPTIAN'};
FARM_GREEK = {id: 276, name: 'FARM_GREEK'};
FARM_JAPANESE = {id: 277, name: 'FARM_JAPANESE'};
FARM_NORSE = {id: 278, name: 'FARM_NORSE'};
FORTRESS = {id: 279, name: 'FORTRESS'};
GRANARY_EGYPTIAN = {id: 280, name: 'GRANARY_EGYPTIAN'};
GRANARY = {id: 281, name: 'GRANARY'};
GREAT_HALL = {id: 282, name: 'GREAT_HALL'};
GUARDHOUSE = {id: 283, name: 'GUARDHOUSE'};
HILL_FORT = {id: 284, name: 'HILL_FORT'};
HOUSE_ATLANTEAN = {id: 285, name: 'HOUSE_ATLANTEAN'};
HOUSE_EGYPTIAN = {id: 286, name: 'HOUSE_EGYPTIAN'};
HOUSE_GREEK = {id: 287, name: 'HOUSE_GREEK'};
HOUSE_JAPANESE = {id: 288, name: 'HOUSE_JAPANESE'};
HOUSE_NORSE = {id: 289, name: 'HOUSE_NORSE'};
IMPERIAL_ACADEMY = {id: 290, name: 'IMPERIAL_ACADEMY'};
LIGHTHOUSE = {id: 291, name: 'LIGHTHOUSE'};
LONGHOUSE = {id: 292, name: 'LONGHOUSE'};
LUMBER_CAMP = {id: 293, name: 'LUMBER_CAMP'};
MACHINE_WORKSHOP = {id: 294, name: 'MACHINE_WORKSHOP'};
MANOR = {id: 295, name: 'MANOR'};
MARKET_ATLANTEAN = {id: 296, name: 'MARKET_ATLANTEAN'};
MARKET_CHINESE = {id: 297, name: 'MARKET_CHINESE'};
MARKET_EGYPTIAN = {id: 298, name: 'MARKET_EGYPTIAN'};
MARKET_GREEK = {id: 299, name: 'MARKET_GREEK'};
MARKET_JAPANESE = {id: 300, name: 'MARKET_JAPANESE'};
MARKET_NORSE = {id: 301, name: 'MARKET_NORSE'};
MIGDOL_STRONGHOLD = {id: 302, name: 'MIGDOL_STRONGHOLD'};
MILITARY_ACADEMY = {id: 303, name: 'MILITARY_ACADEMY'};
MILITARY_CAMP_TOWER_TRAINING_YARD = {id: 304, name: 'MILITARY_CAMP_TOWER_TRAINING_YARD'};
MILITARY_CAMP_TOWER = {id: 305, name: 'MILITARY_CAMP_TOWER'};
MILITARY_CAMP = {id: 306, name: 'MILITARY_CAMP'};
MILLITARY_BARRACKS = {id: 307, name: 'MILLITARY_BARRACKS'};
MINING_CAMP_EGYPTIAN = {id: 308, name: 'MINING_CAMP_EGYPTIAN'};
MINING_CAMP_JAPANESE = {id: 309, name: 'MINING_CAMP_JAPANESE'};
MIRROR_TOWER = {id: 310, name: 'MIRROR_TOWER'};
MONUMENT_TO_GODS = {id: 311, name: 'MONUMENT_TO_GODS'};
MONUMENT_TO_PHARAOHS = {id: 312, name: 'MONUMENT_TO_PHARAOHS'};
MONUMENT_TO_PRIESTS = {id: 313, name: 'MONUMENT_TO_PRIESTS'};
MONUMENT_TO_SOLDIERS = {id: 314, name: 'MONUMENT_TO_SOLDIERS'};
MONUMENT_TO_VILLAGERS = {id: 315, name: 'MONUMENT_TO_VILLAGERS'};
OBELISK = {id: 316, name: 'OBELISK'};
PALACE = {id: 317, name: 'PALACE'};
SENTINEL = {id: 318, name: 'SENTINEL'};
SENTRY_TOWER_ATLANTEAN = {id: 319, name: 'SENTRY_TOWER_ATLANTEAN'};
SENTRY_TOWER_CHINESE = {id: 320, name: 'SENTRY_TOWER_CHINESE'};
SENTRY_TOWER_EGYPTIAN = {id: 321, name: 'SENTRY_TOWER_EGYPTIAN'};
SENTRY_TOWER_GREEK = {id: 322, name: 'SENTRY_TOWER_GREEK'};
SENTRY_TOWER_JAPANESE = {id: 323, name: 'SENTRY_TOWER_JAPANESE'};
SENTRY_TOWER_NORSE = {id: 324, name: 'SENTRY_TOWER_NORSE'};
SHENNOGS_FARM = {id: 325, name: 'SHENNOGS_FARM'};
SHRINE = {id: 326, name: 'SHRINE'};
SIEGE_WORKS = {id: 327, name: 'SIEGE_WORKS'};
SILO = {id: 328, name: 'SILO'};
SKY_PASSAGE = {id: 329, name: 'SKY_PASSAGE'};
STABLE_JAPANESE = {id: 330, name: 'STABLE_JAPANESE'};
STABLE = {id: 331, name: 'STABLE'};
STOREHOUSE = {id: 332, name: 'STOREHOUSE'};
TEMPLE_ATLANTEAN = {id: 333, name: 'TEMPLE_ATLANTEAN'};
TEMPLE_CHINESE = {id: 334, name: 'TEMPLE_CHINESE'};
TEMPLE_EGYPTIAN = {id: 335, name: 'TEMPLE_EGYPTIAN'};
TEMPLE_GREEK = {id: 336, name: 'TEMPLE_GREEK'};
TEMPLE_JAPANESE = {id: 337, name: 'TEMPLE_JAPANESE'};
TEMPLE_NORSE = {id: 338, name: 'TEMPLE_NORSE'};
TOWN_CENTER_ATLANTEAN = {id: 339, name: 'TOWN_CENTER_ATLANTEAN'};
TOWN_CENTER_CHINESE = {id: 340, name: 'TOWN_CENTER_CHINESE'};
TOWN_CENTER_EGYPTIAN = {id: 341, name: 'TOWN_CENTER_EGYPTIAN'};
TOWN_CENTER_GREEK = {id: 342, name: 'TOWN_CENTER_GREEK'};
TOWN_CENTER_JAPANESE = {id: 343, name: 'TOWN_CENTER_JAPANESE'};
TOWN_CENTER_NORSE = {id: 344, name: 'TOWN_CENTER_NORSE'};
VILLAGE_CENTER_ATLANTEAN = {id: 345, name: 'VILLAGE_CENTER_ATLANTEAN'};
VILLAGE_CENTER_CHINESE = {id: 346, name: 'VILLAGE_CENTER_CHINESE'};
VILLAGE_CENTER_EGYPTIAN = {id: 347, name: 'VILLAGE_CENTER_EGYPTIAN'};
VILLAGE_CENTER_GREEK = {id: 348, name: 'VILLAGE_CENTER_GREEK'};
VILLAGE_CENTER_JAPANESE = {id: 349, name: 'VILLAGE_CENTER_JAPANESE'};
VILLAGE_CENTER_NORSE = {id: 350, name: 'VILLAGE_CENTER_NORSE'};
WATERMILL = {id: 351, name: 'WATERMILL'};
WONDER_FUXI_CHINESE = {id: 352, name: 'WONDER_FUXI_CHINESE'};
WONDER_HADES_GREEK = {id: 353, name: 'WONDER_HADES_GREEK'};
WONDER_ISIS_EGYPTIAN = {id: 354, name: 'WONDER_ISIS_EGYPTIAN'};
WONDER_KRONOS_ATLANTEAN = {id: 355, name: 'WONDER_KRONOS_ATLANTEAN'};
WONDER_ODIN_NORSE = {id: 356, name: 'WONDER_ODIN_NORSE'};
WONDER_POSEIDON_GREEK = {id: 357, name: 'WONDER_POSEIDON_GREEK'};
WONDER_TSUKUYOMI_JAPANESE = {id: 358, name: 'WONDER_TSUKUYOMI_JAPANESE'};
WONDER_ZEUS_GREEK = {id: 359, name: 'WONDER_ZEUS_GREEK'};
WOODEN_WALL_CONNECTOR_ATLANTEAN = {id: 360, name: 'WOODEN_WALL_CONNECTOR_ATLANTEAN'};
WOODEN_WALL_CONNECTOR_CHINESE = {id: 361, name: 'WOODEN_WALL_CONNECTOR_CHINESE'};
WOODEN_WALL_CONNECTOR_EGYPTIAN = {id: 362, name: 'WOODEN_WALL_CONNECTOR_EGYPTIAN'};
WOODEN_WALL_CONNECTOR_GREEK = {id: 363, name: 'WOODEN_WALL_CONNECTOR_GREEK'};
WOODEN_WALL_CONNECTOR_JAPANESE = {id: 364, name: 'WOODEN_WALL_CONNECTOR_JAPANESE'};
WOODEN_WALL_CONNECTOR_NORSE = {id: 365, name: 'WOODEN_WALL_CONNECTOR_NORSE'};
WOODEN_WALL_GATE_ATLANTEAN = {id: 366, name: 'WOODEN_WALL_GATE_ATLANTEAN'};
WOODEN_WALL_GATE_CHINESE = {id: 367, name: 'WOODEN_WALL_GATE_CHINESE'};
WOODEN_WALL_GATE_EGYPTIAN = {id: 368, name: 'WOODEN_WALL_GATE_EGYPTIAN'};
WOODEN_WALL_GATE_GREEK = {id: 369, name: 'WOODEN_WALL_GATE_GREEK'};
WOODEN_WALL_GATE_JAPANESE = {id: 370, name: 'WOODEN_WALL_GATE_JAPANESE'};
WOODEN_WALL_GATE_NORSE = {id: 371, name: 'WOODEN_WALL_GATE_NORSE'};
WOODEN_WALL_LONG_ATLANTEAN = {id: 372, name: 'WOODEN_WALL_LONG_ATLANTEAN'};
WOODEN_WALL_LONG_CHINESE = {id: 373, name: 'WOODEN_WALL_LONG_CHINESE'};
WOODEN_WALL_LONG_EGYPTIAN = {id: 374, name: 'WOODEN_WALL_LONG_EGYPTIAN'};
WOODEN_WALL_LONG_JAPANESE = {id: 375, name: 'WOODEN_WALL_LONG_JAPANESE'};
WOODEN_WALL_MEDUIM_ATLANTEAN = {id: 376, name: 'WOODEN_WALL_MEDUIM_ATLANTEAN'};
WOODEN_WALL_MEDUIM_CHINESE = {id: 377, name: 'WOODEN_WALL_MEDUIM_CHINESE'};
WOODEN_WALL_MEDUIM_EGYPTIAN = {id: 378, name: 'WOODEN_WALL_MEDUIM_EGYPTIAN'};
WOODEN_WALL_MEDUIM_GREEK = {id: 379, name: 'WOODEN_WALL_MEDUIM_GREEK'};
WOODEN_WALL_MEDUIM_JAPANESE = {id: 380, name: 'WOODEN_WALL_MEDUIM_JAPANESE'};
WOODEN_WALL_MEDUIM_NORSE = {id: 381, name: 'WOODEN_WALL_MEDUIM_NORSE'};
WOODEN_WALL_SHORT_ATLANTEAN = {id: 382, name: 'WOODEN_WALL_SHORT_ATLANTEAN'};
WOODEN_WALL_SHORT_CHINESE = {id: 383, name: 'WOODEN_WALL_SHORT_CHINESE'};
WOODEN_WALL_SHORT_EGYPTIAN = {id: 384, name: 'WOODEN_WALL_SHORT_EGYPTIAN'};
WOODEN_WALL_SHORT_GREEK = {id: 385, name: 'WOODEN_WALL_SHORT_GREEK'};
WOODEN_WALL_SHORT_JAPANESE = {id: 386, name: 'WOODEN_WALL_SHORT_JAPANESE'};
WOODEN_WALL_SMALL = {id: 387, name: 'WOODEN_WALL_SMALL'};
BUILDINGS = {id: 388, name: 'BUILDINGS'};
CHAMPIOM_OF_FREYR_LEGEND = {id: 389, name: 'CHAMPIOM_OF_FREYR_LEGEND'};
GOD_POWERS = {id: 390, name: 'GOD_POWERS'};
MINION_OTHER = {id: 391, name: 'MINION_OTHER'};
ONNA_MUSHA_HERO = {id: 392, name: 'ONNA-MUSHA_HERO'};
RAMMING_GALLEY = {id: 393, name: 'RAMMING-GALLEY'};
RAMMING_WASEN = {id: 394, name: 'RAMMING-WASEN'};
RAVEN = {id: 395, name: 'RAVEN'};
TECHS = {id: 396, name: 'TECHS'};
ARMORY_EGYPTIAN = {id: 397, name: 'ARMORY_EGYPTIAN'};
HOUSE_CHINESE = {id: 398, name: 'HOUSE_CHINESE'};
MILLITARY_ACADEMY = {id: 399, name: 'MILLITARY_ACADEMY'};
SHENNONGS_FARM = {id: 400, name: 'SHENNONGS_FARM'};
STABLE_GREEK = {id: 401, name: 'STABLE_GREEK'};
WONDER_JAPANESE = {id: 402, name: 'WONDER_JAPANESE'};
WOODEN_WALL_CHINESE = {id: 403, name: 'WOODEN_WALL_CHINESE'};
WOODEN_WALL_EGYPTIAN = {id: 404, name: 'WOODEN_WALL_EGYPTIAN'};
WOODEN_WALL_GREEK = {id: 405, name: 'WOODEN_WALL_GREEK'};
WOODEN_WALL_JAPANESE = {id: 406, name: 'WOODEN_WALL_JAPANESE'};
CHAMPION_CAVALRY_NORSE = {id: 407, name: 'CHAMPION_CAVALRY_NORSE'};
N_CHAMPION_INFANTRY_NORSE_HF = {id: 408, name: 'N_CHAMPION_INFANTRY_NORSE_HF'};
CONSCRIPT_GREAT_HALL_SOLDIERS = {id: 409, name: 'CONSCRIPT_GREAT_HALL_SOLDIERS'};
CONSCRIPT_HILL_FORT_SOLDIERS = {id: 410, name: 'CONSCRIPT_HILL_FORT_SOLDIERS'};
CONSCRIPT_LONGHOUSE_SOLDIERS = {id: 411, name: 'CONSCRIPT_LONGHOUSE_SOLDIERS'};
DRAFT_HORSES_NORSE = {id: 412, name: 'DRAFT_HORSES_NORSE'};
ENGINEERS_NORSE = {id: 413, name: 'ENGINEERS_NORSE'};
HEAVY_CAVALRY_NORSE = {id: 414, name: 'HEAVY_CAVALRY_NORSE'};
N_HEAVY_INFANTRY_NORSE_HF = {id: 415, name: 'N_HEAVY_INFANTRY_NORSE_HF'};
LEVY_GREAT_HALL_SOLDIERS = {id: 416, name: 'LEVY_GREAT_HALL_SOLDIERS'};
LEVY_HILL_FORT_SOLDIERS = {id: 417, name: 'LEVY_HILL_FORT_SOLDIERS'};
LEVY_LONGHOUSE_SOLDIERS = {id: 418, name: 'LEVY_LONGHOUSE_SOLDIERS'};
MEDIUM_CAVALRY_NORSE = {id: 419, name: 'MEDIUM_CAVALRY_NORSE'};
N_MEDIUM_INFANTRY_NORSE_HF = {id: 420, name: 'N_MEDIUM_INFANTRY_NORSE_HF'};
BUSHIDO_AND_GOD_BLESSINGS = {id: 421, name: 'BUSHIDO_AND_GOD_BLESSINGS'};
MAJOR_GOD = {id: 422, name: 'MAJOR_GOD'};
MINOR_GOD = {id: 423, name: 'MINOR_GOD'};
ABUNDANCE = {id: 424, name: 'ABUNDANCE'};
ADVANCED_DEFENSES = {id: 425, name: 'ADVANCED_DEFENSES'};
ADVANCED_FORTIFICATIONS = {id: 426, name: 'ADVANCED_FORTIFICATIONS'};
ADZE_OF_WEPWAWET = {id: 427, name: 'ADZE_OF_WEPWAWET'};
AEGIS_SHIELD = {id: 428, name: 'AEGIS_SHIELD'};
ALLUVIAL_CLAY = {id: 429, name: 'ALLUVIAL_CLAY'};
AMBASSADORS = {id: 430, name: 'AMBASSADORS'};
ANASTROPHE = {id: 431, name: 'ANASTROPHE'};
ARCHITECTS = {id: 432, name: 'ARCHITECTS'};
ARGIVE_PATRONAGE = {id: 433, name: 'ARGIVE_PATRONAGE'};
ARGONAUTS = {id: 434, name: 'ARGONAUTS'};
ASCETIC_PRACTICES = {id: 435, name: 'ASCETIC_PRACTICES'};
ASMMETRICAL_BOW = {id: 436, name: 'ASMMETRICAL_BOW'};
ASPER_BLOOD = {id: 437, name: 'ASPER_BLOOD'};
ATEF_CROWN = {id: 438, name: 'ATEF_CROWN'};
AUTUMN_OF_ABUNDANCE = {id: 439, name: 'AUTUMN_OF_ABUNDANCE'};
AVENGING_SPIRIT = {id: 440, name: 'AVENGING_SPIRIT'};
AXE_OF_VENGEANCE = {id: 441, name: 'AXE_OF_VENGEANCE'};
BALLISTICS = {id: 442, name: 'BALLISTICS'};
BEAST_SLAYER = {id: 443, name: 'BEAST_SLAYER'};
BERSERKERGANG = {id: 444, name: 'BERSERKERGANG'};
BITE_OF_THE_SHARK = {id: 445, name: 'BITE_OF_THE_SHARK'};
BOILING_OIL = {id: 446, name: 'BOILING_OIL'};
BONE_BOW = {id: 447, name: 'BONE_BOW'};
BOOK_OF_THOTH = {id: 448, name: 'BOOK_OF_THOTH'};
BOTTOMLESS_STOMACH = {id: 449, name: 'BOTTOMLESS_STOMACH'};
BOW_SAW = {id: 450, name: 'BOW_SAW'};
BRAVERY = {id: 451, name: 'BRAVERY'};
BRONZE_ARMOR = {id: 452, name: 'BRONZE_ARMOR'};
BRONZE_SHIELD = {id: 453, name: 'BRONZE_SHIELD'};
BRONZE_WALL_ATLANTEAN = {id: 454, name: 'BRONZE_WALL_ATLANTEAN'};
BRONZE_WEAPONS = {id: 455, name: 'BRONZE_WEAPONS'};
BURNING_MALEVOLENCE = {id: 456, name: 'BURNING_MALEVOLENCE'};
BURNING_PITCH = {id: 457, name: 'BURNING_PITCH'};
CALL_OF_VALHALLA = {id: 458, name: 'CALL_OF_VALHALLA'};
CARPENTERS = {id: 459, name: 'CARPENTERS'};
CARRIER_PIGEONS = {id: 460, name: 'CARRIER_PIGEONS'};
CAVE_TROLL = {id: 461, name: 'CAVE_TROLL'};
CELERITY = {id: 462, name: 'CELERITY'};
CELESTIAL_WEAPONS = {id: 463, name: 'CELESTIAL_WEAPONS'};
CHAMPION_AXEMEN = {id: 464, name: 'CHAMPION_AXEMEN'};
CHAMPION_CAMEL_RIDERS = {id: 465, name: 'CHAMPION_CAMEL_RIDERS'};
CHAMPION_CAVALRY_ATLANTEAN = {id: 466, name: 'CHAMPION_CAVALRY_ATLANTEAN'};
CHAMPION_CAVALRY_GREEK = {id: 467, name: 'CHAMPION_CAVALRY_GREEK'};
CHAMPION_CHARIOTS = {id: 468, name: 'CHAMPION_CHARIOTS'};
CHAMPION_ELEPHANTS = {id: 469, name: 'CHAMPION_ELEPHANTS'};
CHAMPION_INFANTRY_ATLANTEAN = {id: 470, name: 'CHAMPION_INFANTRY_ATLANTEAN'};
CHAMPION_INFANTRY_GREEK = {id: 471, name: 'CHAMPION_INFANTRY_GREEK'};
CHAMPION_RANGED_SOLDIERS_GREEK = {id: 472, name: 'CHAMPION_RANGED_SOLDIERS_GREEK'};
CHAMPION_RANGED_SOLDIERS = {id: 473, name: 'CHAMPION_RANGED_SOLDIERS'};
CHAMPION_SLINGERS = {id: 474, name: 'CHAMPION_SLINGERS'};
CHAMPION_SPEARMEN = {id: 475, name: 'CHAMPION_SPEARMEN'};
CHAMPION_WARSHIP = {id: 476, name: 'CHAMPION_WARSHIP'};
CHANNELS = {id: 477, name: 'CHANNELS'};
CHASING_THE_SUN = {id: 478, name: 'CHASING_THE_SUN'};
CHTHONIC_RITES = {id: 479, name: 'CHTHONIC_RITES'};
CITADEL_WALL = {id: 480, name: 'CITADEL_WALL'};
CLAIRVOYANCE = {id: 481, name: 'CLAIRVOYANCE'};
COINAGE = {id: 482, name: 'COINAGE'};
CONDEMNED_SOUL = {id: 483, name: 'CONDEMNED_SOUL'};
CONSCRIPT_BARRACKS_SOLDIERS = {id: 484, name: 'CONSCRIPT_BARRACKS_SOLDIERS'};
CONSCRIPT_CAVALRY = {id: 485, name: 'CONSCRIPT_CAVALRY'};
CONSCRIPT_COUNTER_SOLDIERS = {id: 486, name: 'CONSCRIPT_COUNTER_SOLDIERS'};
CONSCRIPT_INFANTRY = {id: 487, name: 'CONSCRIPT_INFANTRY'};
CONSCRIPT_MAINLINE_SOLIDERS = {id: 488, name: 'CONSCRIPT_MAINLINE_SOLIDERS'};
CONSCRIPT_MIGDOL_SOLDIERS = {id: 489, name: 'CONSCRIPT_MIGDOL_SOLDIERS'};
CONSCRIPT_PALACE_SOLDIERS = {id: 490, name: 'CONSCRIPT_PALACE_SOLDIERS'};
CONSCRIPT_RANGED_SOLDIERS = {id: 491, name: 'CONSCRIPT_RANGED_SOLDIERS'};
CONSCRIPT_SAILORS = {id: 492, name: 'CONSCRIPT_SAILORS'};
COPPER_ARMOR = {id: 493, name: 'COPPER_ARMOR'};
COPPER_SHIELDS = {id: 494, name: 'COPPER_SHIELDS'};
COPPER_WEAPONS = {id: 495, name: 'COPPER_WEAPONS'};
CRENELLATIONS = {id: 496, name: 'CRENELLATIONS'};
CRIMSON_LINEN = {id: 497, name: 'CRIMSON_LINEN'};
CRIOSPHINX = {id: 498, name: 'CRIOSPHINX'};
CROCODILOPOLIS = {id: 499, name: 'CROCODILOPOLIS'};
CRUSHING_WAVES = {id: 500, name: 'CRUSHING_WAVES'};
DAKTYLOI = {id: 501, name: 'DAKTYLOI'};
DAN_NO_URA_TACTICS = {id: 502, name: 'DAN-NO-URA_TACTICS'};
DARK_WATER = {id: 503, name: 'DARK_WATER'};
DAUGHTERS_OF_THE_SEA = {id: 504, name: 'DAUGHTERS_OF_THE_SEA'};
DEADLY_RAGE = {id: 505, name: 'DEADLY_RAGE'};
DEADLY_SNARE = {id: 506, name: 'DEADLY_SNARE'};
DEIMOS_SWORD_OF_DREAD = {id: 507, name: 'DEIMOS_SWORD_OF_DREAD'};
DEN_DEN_DRUMS = {id: 508, name: 'DEN_DEN_DRUMS'};
DESERT_WIND = {id: 509, name: 'DESERT_WIND'};
DEVOTEES_OF_ATLAS = {id: 510, name: 'DEVOTEES_OF_ATLAS'};
DIONYSIA = {id: 511, name: 'DIONYSIA'};
DISABLOT = {id: 512, name: 'DISABLOT'};
DIVINE_BLOOD = {id: 513, name: 'DIVINE_BLOOD'};
DIVINE_BOOKS = {id: 514, name: 'DIVINE_BOOKS'};
DIVINE_JUDGMENT = {id: 515, name: 'DIVINE_JUDGMENT'};
DIVINE_PREFECTURE = {id: 516, name: 'DIVINE_PREFECTURE'};
DRAGONSCALE_SHIELDS = {id: 517, name: 'DRAGONSCALE_SHIELDS'};
DROUGHT_SHIPS = {id: 518, name: 'DROUGHT_SHIPS'};
DWARVEN_AUGER = {id: 519, name: 'DWARVEN_AUGER'};
DWARVEN_BREASTPLATE = {id: 520, name: 'DWARVEN_BREASTPLATE'};
DWARVEN_MINE = {id: 521, name: 'DWARVEN_MINE'};
DWARVEN_WEAPONS = {id: 522, name: 'DWARVEN_WEAPONS'};
EIGHT_BANNERS = {id: 523, name: 'EIGHT_BANNERS'};
ELECTRUM_BULLETS = {id: 524, name: 'ELECTRUM_BULLETS'};
EMPYRIAN_SPEED = {id: 525, name: 'EMPYRIAN_SPEED'};
ENCLOSED_DECK = {id: 526, name: 'ENCLOSED_DECK'};
ENYOS_BOW_OF_HORROR = {id: 527, name: 'ENYOS_BOW_OF_HORROR'};
ETERNAL_HAUNTING = {id: 528, name: 'ETERNAL_HAUNTING'};
EYES_IN_THE_FOREST = {id: 529, name: 'EYES_IN_THE_FOREST'};
FACE_OF_THE_GORGON = {id: 530, name: 'FACE_OF_THE_GORGON'};
FEASTS_OF_RENOWN = {id: 531, name: 'FEASTS_OF_RENOWN'};
FEET_OF_THE_JACKAL = {id: 532, name: 'FEET_OF_THE_JACKAL'};
FLAMES_OF_TYPHON = {id: 533, name: 'FLAMES_OF_TYPHON'};
FLAMING_BLOOD = {id: 534, name: 'FLAMING_BLOOD'};
FLOOD_CONTROL = {id: 535, name: 'FLOOD_CONTROL'};
FLOOD_OF_THE_NILE = {id: 536, name: 'FLOOD_OF_THE_NILE'};
FORCE_OF_THE_WEST_WIND = {id: 537, name: 'FORCE_OF_THE_WEST_WIND'};
FORGE_OF_OLYMPUS = {id: 538, name: 'FORGE_OF_OLYMPUS'};
FORTIFIED_TOWN_CENTER = {id: 539, name: 'FORTIFIED_TOWN_CENTER'};
FORTIFIED_WALL_EGYPTIAN = {id: 540, name: 'FORTIFIED_WALL_EGYPTIAN'};
FORTIFIED_WALL_GREEK = {id: 541, name: 'FORTIFIED_WALL_GREEK'};
FRENZIED_DASH = {id: 542, name: 'FRENZIED_DASH'};
FREYRS_GIFT = {id: 543, name: 'FREYRS_GIFT'};
FRONTLINE_HEROICS = {id: 544, name: 'FRONTLINE_HEROICS'};
FUNERAL_BARGE = {id: 545, name: 'FUNERAL_BARGE'};
FUNERAL_RITES = {id: 546, name: 'FUNERAL_RITES'};
FURY_OF_THE_FALLEN = {id: 547, name: 'FURY_OF_THE_FALLEN'};
GALES_FURY = {id: 548, name: 'GALES_FURY'};
GEMINI = {id: 549, name: 'GEMINI'};
GILDED_SHIELDS = {id: 550, name: 'GILDED_SHIELDS'};
GJALLARHORN = {id: 551, name: 'GJALLARHORN'};
GOHEI_WANDS = {id: 552, name: 'GOHEI_WANDS'};
GOLDEN_APPLES = {id: 553, name: 'GOLDEN_APPLES'};
GOLDEN_KITE = {id: 554, name: 'GOLDEN_KITE'};
GRANITE_BLOOD = {id: 555, name: 'GRANITE_BLOOD'};
GRANITE_MAW = {id: 556, name: 'GRANITE_MAW'};
GRASP_OF_RAN = {id: 557, name: 'GRASP_OF_RAN'};
GREATEST_OF_FIFTY = {id: 558, name: 'GREATEST_OF_FIFTY'};
GUARD_TOWER_GREEK = {id: 559, name: 'GUARD_TOWER_GREEK'};
GUARD_TOWER = {id: 560, name: 'GUARD_TOWER'};
GUARDIAN_OF_IO = {id: 561, name: 'GUARDIAN_OF_IO'};
HALL_OF_THANES = {id: 562, name: 'HALL_OF_THANES'};
HALO_OF_THE_SUN = {id: 563, name: 'HALO_OF_THE_SUN'};
HAMASK = {id: 564, name: 'HAMASK'};
HAMMER_OF_THUNDER = {id: 565, name: 'HAMMER_OF_THUNDER'};
HAND_AXE = {id: 566, name: 'HAND_AXE'};
HAND_OF_TALOS = {id: 567, name: 'HAND_OF_TALOS'};
HANNYA_MASK = {id: 568, name: 'HANNYA_MASK'};
HEAVENLY_BARRAGE = {id: 569, name: 'HEAVENLY_BARRAGE'};
HEAVY_AXEMEN = {id: 570, name: 'HEAVY_AXEMEN'};
HEAVY_CAMEL_RIDERS = {id: 571, name: 'HEAVY_CAMEL_RIDERS'};
HEAVY_CAVALRY_ATLANTEAN = {id: 572, name: 'HEAVY_CAVALRY_ATLANTEAN'};
HEAVY_CAVALRY_GREEK = {id: 573, name: 'HEAVY_CAVALRY_GREEK'};
HEAVY_CHARIOTS = {id: 574, name: 'HEAVY_CHARIOTS'};
HEAVY_ELEPHANTS = {id: 575, name: 'HEAVY_ELEPHANTS'};
HEAVY_INFANTRY_ATLANTEAN = {id: 576, name: 'HEAVY_INFANTRY_ATLANTEAN'};
HEAVY_INFANTRY_GREEK = {id: 577, name: 'HEAVY_INFANTRY_GREEK'};
HEAVY_RANGED_SOLDIERS_ATLANTEAN = {id: 578, name: 'HEAVY_RANGED_SOLDIERS_ATLANTEAN'};
HEAVY_RANGED_SOLDIERS_GREEK = {id: 579, name: 'HEAVY_RANGED_SOLDIERS_GREEK'};
HEAVY_SLINGERS = {id: 580, name: 'HEAVY_SLINGERS'};
HEAVY_SPEARMAN = {id: 581, name: 'HEAVY_SPEARMAN'};
HEAVY_WARSHIPS = {id: 582, name: 'HEAVY_WARSHIPS'};
HEPHAESTUS_REVENGE = {id: 583, name: 'HEPHAESTUS_REVENGE'};
HERBAL_MEDICINE = {id: 584, name: 'HERBAL_MEDICINE'};
HEROIC_FLEET = {id: 585, name: 'HEROIC_FLEET'};
HEROIC_RENEWAL = {id: 586, name: 'HEROIC_RENEWAL'};
HIERACOSPHINX = {id: 587, name: 'HIERACOSPHINX'};
HOOVES_OF_THE_WIND = {id: 588, name: 'HOOVES_OF_THE_WIND'};
HORNS_OF_CONSECRATION = {id: 589, name: 'HORNS_OF_CONSECRATION'};
HUNTERS_STRENGHT = {id: 590, name: 'HUNTERS_STRENGHT'};
HUNTRESS_AXE = {id: 591, name: 'HUNTRESS_AXE'};
HUSBANDRY = {id: 592, name: 'HUSBANDRY'};
HYPERION = {id: 593, name: 'HYPERION'};
IMPERIAL_ORDER = {id: 594, name: 'IMPERIAL_ORDER'};
IRON_ARMOR = {id: 595, name: 'IRON_ARMOR'};
IRON_SHIELDS = {id: 596, name: 'IRON_SHIELDS'};
IRON_WALL = {id: 597, name: 'IRON_WALL'};
IRON_WEAPONS = {id: 598, name: 'IRON_WEAPONS'};
IRRIGATION = {id: 599, name: 'IRRIGATION'};
IVORY_NETSUKE = {id: 600, name: 'IVORY_NETSUKE'};
JOTUNS = {id: 601, name: 'JOTUNS'};
KAGURA = {id: 602, name: 'KAGURA'};
KATAGI = {id: 603, name: 'KATAGI'};
KUAFU_CHIEFTAIN = {id: 604, name: 'KUAFU_CHIEFTAIN'};
KUMIKI = {id: 605, name: 'KUMIKI'};
LABYRINTH_OF_MINOS = {id: 606, name: 'LABYRINTH_OF_MINOS'};
LANCE_OF_STONE = {id: 607, name: 'LANCE_OF_STONE'};
LAST_STAND = {id: 608, name: 'LAST_STAND'};
LEATHER_FRAME_SHIELD = {id: 609, name: 'LEATHER_FRAME_SHIELD'};
LEIZUS_SILK = {id: 610, name: 'LEIZUS_SILK'};
LEVY_BARRACKS_SOLDIERS = {id: 611, name: 'LEVY_BARRACKS_SOLDIERS'};
LEVY_CAVALRY = {id: 612, name: 'LEVY_CAVALRY'};
LEVY_COUNTER_SOLDIERS = {id: 613, name: 'LEVY_COUNTER_SOLDIERS'};
LEVY_INFANTRY_GREEK = {id: 614, name: 'LEVY_INFANTRY_GREEK'};
LEVY_MAINLINE_SOLDIERS = {id: 615, name: 'LEVY_MAINLINE_SOLDIERS'};
LEVY_MIGDOL_SOLDIERS = {id: 616, name: 'LEVY_MIGDOL_SOLDIERS'};
LEVY_PALACE_SOLDIERS = {id: 617, name: 'LEVY_PALACE_SOLDIERS'};
LEVY_RANGED_SOLDIERS = {id: 618, name: 'LEVY_RANGED_SOLDIERS'};
LONG_SERPENT = {id: 619, name: 'LONG_SERPENT'};
LORD_OF_HORSES = {id: 620, name: 'LORD_OF_HORSES'};
MAELSTROM = {id: 621, name: 'MAELSTROM'};
MASONS = {id: 622, name: 'MASONS'};
MASTER_OF_WEAPONRY = {id: 623, name: 'MASTER_OF_WEAPONRY'};
MECHANICAL_ARTISANS = {id: 624, name: 'MECHANICAL_ARTISANS'};
MEDIUM_AXEMAN = {id: 625, name: 'MEDIUM_AXEMAN'};
MEDIUM_CAVALRY_GREEK = {id: 626, name: 'MEDIUM_CAVALRY_GREEK'};
MEDIUM_INFANTRY_ATLANTEAN = {id: 627, name: 'MEDIUM_INFANTRY_ATLANTEAN'};
MEDIUM_INFANTRY_GREEK = {id: 628, name: 'MEDIUM_INFANTRY_GREEK'};
MEDIUM_RANGED_SOLDIERS_ATLANTEAN = {id: 629, name: 'MEDIUM_RANGED_SOLDIERS_ATLANTEAN'};
MEDIUM_RANGED_SOLDIERS_GREEK = {id: 630, name: 'MEDIUM_RANGED_SOLDIERS_GREEK'};
MEDIUM_SLINGERS = {id: 631, name: 'MEDIUM_SLINGERS'};
MEDIUM_SPEARMAN = {id: 632, name: 'MEDIUM_SPEARMAN'};
METEORIC_IRON_ARMOR = {id: 633, name: 'METEORIC_IRON_ARMOR'};
MONSTROUS_RAGE = {id: 634, name: 'MONSTROUS_RAGE'};
MOUNTAINOUS_MIGHT = {id: 635, name: 'MOUNTAINOUS_MIGHT'};
MYTHIC_REJUVENATION = {id: 636, name: 'MYTHIC_REJUVENATION'};
NEBTY = {id: 637, name: 'NEBTY'};
NECROPOLIS = {id: 638, name: 'NECROPOLIS'};
NEW_KINGDOM = {id: 639, name: 'NEW_KINGDOM'};
NINE_WAVES = {id: 640, name: 'NINE_WAVES'};
OLYMPIAN_PARENTAGE = {id: 641, name: 'OLYMPIAN_PARENTAGE'};
OLYMPIAN_WEAPONS = {id: 642, name: 'OLYMPIAN_WEAPONS'};
OMNISCIENCE = {id: 643, name: 'OMNISCIENCE'};
ONI_MASK = {id: 644, name: 'ONI_MASK'};
ONMYODO = {id: 645, name: 'ONMYODO'};
ORICHALCUM_MAIL = {id: 646, name: 'ORICHALCUM_MAIL'};
ORICHALCUM_WALL = {id: 647, name: 'ORICHALCUM_WALL'};
PEACH_OF_IMMORTALITY = {id: 648, name: 'PEACH_OF_IMMORTALITY'};
PERCEPTION = {id: 649, name: 'PERCEPTION'};
PETRIFICATION = {id: 650, name: 'PETRIFICATION'};
PHOBOS_SPEAR_OF_PANIC = {id: 651, name: 'PHOBOS_SPEAR_OF_PANIC'};
PICKAXE = {id: 652, name: 'PICKAXE'};
PIONEER_OF_THE_SKIES = {id: 653, name: 'PIONEER_OF_THE_SKIES'};
PLOW = {id: 654, name: 'PLOW'};
POSEIDONS_SECRET = {id: 655, name: 'POSEIDONS_SECRET'};
POWER_OF_CHAOS = {id: 656, name: 'POWER_OF_CHAOS'};
PROPHETIC_SIGHT = {id: 657, name: 'PROPHETIC_SIGHT'};
PTAH = {id: 658, name: 'PTAH'};
PURSE_SEINE = {id: 659, name: 'PURSE_SEINE'};
QILINS_BLESSING = {id: 660, name: 'QILINS_BLESSING'};
QUARRY = {id: 661, name: 'QUARRY'};
RAGE_OF_SLAUGHTER = {id: 662, name: 'RAGE_OF_SLAUGHTER'};
RAMPAGE = {id: 663, name: 'RAMPAGE'};
RED_CLIFFS_FLEET = {id: 664, name: 'RED_CLIFFS_FLEET'};
REINCARNATION = {id: 665, name: 'REINCARNATION'};
RESTLESS_ARMY = {id: 666, name: 'RESTLESS_ARMY'};
RHEIAS_GIFT = {id: 667, name: 'RHEIAS_GIFT'};
RIGSTHULA = {id: 668, name: 'RIGSTHULA'};
RIME = {id: 669, name: 'RIME'};
RING_GIVER = {id: 670, name: 'RING_GIVER'};
RING_OATH = {id: 671, name: 'RING_OATH'};
RISING_TIDE = {id: 672, name: 'RISING_TIDE'};
ROAR_OF_ORTHUS = {id: 673, name: 'ROAR_OF_ORTHUS'};
ROCK_SOLID = {id: 674, name: 'ROCK_SOLID'};
SACRED_CATS = {id: 675, name: 'SACRED_CATS'};
SAFEGUARD = {id: 676, name: 'SAFEGUARD'};
SALT_AMPHORA = {id: 677, name: 'SALT_AMPHORA'};
SALTWATER_SPRING = {id: 678, name: 'SALTWATER_SPRING'};
SARISSA = {id: 679, name: 'SARISSA'};
SASHIMONO_BANNERMEN = {id: 680, name: 'SASHIMONO_BANNERMEN'};
SCALLOPED_AXE = {id: 681, name: 'SCALLOPED_AXE'};
SCORCHING_FEATHERS = {id: 682, name: 'SCORCHING_FEATHERS'};
SEASIDE_INFILTRATORS = {id: 683, name: 'SEASIDE_INFILTRATORS'};
SECRETS_OF_THE_TITANS = {id: 684, name: 'SECRETS_OF_THE_TITANS'};
SERPENT_SPEAR = {id: 685, name: 'SERPENT_SPEAR'};
SERVANTS_OF_GLORY = {id: 686, name: 'SERVANTS_OF_GLORY'};
SESSRUMNIR = {id: 687, name: 'SESSRUMNIR'};
SET = {id: 688, name: 'SET'};
SHADUF = {id: 689, name: 'SHADUF'};
SHAFT_MINE = {id: 690, name: 'SHAFT_MINE'};
SHAFTS_OF_PLAGUE = {id: 691, name: 'SHAFTS_OF_PLAGUE'};
SHAKER_OF_HEAVEN = {id: 692, name: 'SHAKER_OF_HEAVEN'};
SHOULDER_OF_TALOS = {id: 693, name: 'SHOULDER_OF_TALOS'};
SIGNAL_FIRES = {id: 694, name: 'SIGNAL_FIRES'};
SINISTER_DEFIANCE = {id: 695, name: 'SINISTER_DEFIANCE'};
SKIN_OF_THE_RHINO = {id: 696, name: 'SKIN_OF_THE_RHINO'};
SLASH_AND_BURN = {id: 697, name: 'SLASH_AND_BURN'};
SLIENT_RESOLVE = {id: 698, name: 'SLIENT_RESOLVE'};
SLINGS_OF_THE_SUN = {id: 699, name: 'SLINGS_OF_THE_SUN'};
SOJUTSU = {id: 700, name: 'SOJUTSU'};
SOLAR_BARQUE = {id: 701, name: 'SOLAR_BARQUE'};
SON_OF_LOONG = {id: 702, name: 'SON_OF_LOONG'};
SONG_OF_MIDSUMMER = {id: 703, name: 'SONG_OF_MIDSUMMER'};
SONS_OF_THE_SUN = {id: 704, name: 'SONS_OF_THE_SUN'};
SONS_SLEIPNIR = {id: 705, name: 'SONS_SLEIPNIR'};
SOUTHERN_FIRE = {id: 706, name: 'SOUTHERN_FIRE'};
SPEAR_OF_HORUS = {id: 707, name: 'SPEAR_OF_HORUS'};
SPIRIT_OF_MAAT = {id: 708, name: 'SPIRIT_OF_MAAT'};
SPIRITED_CHARGE = {id: 709, name: 'SPIRITED_CHARGE'};
SPOILS_OF_WAR = {id: 710, name: 'SPOILS_OF_WAR'};
STONE_WALL_ATLANTEAN = {id: 711, name: 'STONE_WALL_ATLANTEAN'};
STONE_WALL_EGYPTIAN = {id: 712, name: 'STONE_WALL_EGYPTIAN'};
STONE_WALL_GREEK = {id: 713, name: 'STONE_WALL_GREEK'};
STONE_WALL_NORSE = {id: 714, name: 'STONE_WALL_NORSE'};
SUMO_TRAINING = {id: 715, name: 'SUMO_TRAINING'};
SUN_DRIED_MUD_BRICK = {id: 716, name: 'SUN_DRIED_MUD_BRICK'};
SUN_RAY = {id: 717, name: 'SUN_RAY'};
SURVIVAL_EQUIPMENT = {id: 718, name: 'SURVIVAL_EQUIPMENT'};
SWINE_ARRAY = {id: 719, name: 'SWINE_ARRAY'};
SYLVAN_LORE = {id: 720, name: 'SYLVAN_LORE'};
TAI_CHI = {id: 721, name: 'TAI_CHI'};
TAX_COLLECTORS = {id: 722, name: 'TAX_COLLECTORS'};
TEMPESTUOUS_STORM = {id: 723, name: 'TEMPESTUOUS_STORM'};
TEMPLE_OF_HEALING = {id: 724, name: 'TEMPLE_OF_HEALING'};
TENSHU = {id: 725, name: 'TENSHU'};
TEN_FIST_SWORD = {id: 726, name: 'TEN-FIST_SWORD'};
THEIA = {id: 727, name: 'THEIA'};
THRACIAN_HORSES = {id: 728, name: 'THRACIAN_HORSES'};
THUNDERING_HOOVES = {id: 729, name: 'THUNDERING_HOOVES'};
THUNDEROUS_PRESENCE = {id: 730, name: 'THUNDEROUS_PRESENCE'};
THURISAZ_RUNE = {id: 731, name: 'THURISAZ_RUNE'};
TITAN_SHIELD = {id: 732, name: 'TITAN_SHIELD'};
TITANOMACHY = {id: 733, name: 'TITANOMACHY'};
TUSKS_OF_APEDEMAK = {id: 734, name: 'TUSKS_OF_APEDEMAK'};
TWILIGHT_OF_THE_GODS = {id: 735, name: 'TWILIGHT_OF_THE_GODS'};
VALGALDR = {id: 736, name: 'VALGALDR'};
VALLEY_OF_THE_KINGS = {id: 737, name: 'VALLEY_OF_THE_KINGS'};
VAULTS_OF_EREBUS = {id: 738, name: 'VAULTS_OF_EREBUS'};
VIBRANT_LAND = {id: 739, name: 'VIBRANT_LAND'};
VIKINGS = {id: 740, name: 'VIKINGS'};
VOLCANIC_FORGE = {id: 741, name: 'VOLCANIC_FORGE'};
WATCH_TOWER_GREEK = {id: 742, name: 'WATCH_TOWER_GREEK'};
WATCH_TOWER = {id: 743, name: 'WATCH_TOWER'};
WEIGHTLESS_MACE = {id: 744, name: 'WEIGHTLESS_MACE'};
WILL_OF_KRONOS = {id: 745, name: 'WILL_OF_KRONOS'};
WIND_SICKLES = {id: 746, name: 'WIND_SICKLES'};
WINGED_MESSENGER = {id: 747, name: 'WINGED_MESSENGER'};
WINTER_HARVEST = {id: 748, name: 'WINTER_HARVEST'};
WISDOM_OF_NINE = {id: 749, name: 'WISDOM_OF_NINE'};
WRATH_OF_THE_DEEP = {id: 750, name: 'WRATH_OF_THE_DEEP'};
XUANYUANS_BLOODLINE = {id: 751, name: 'XUANYUANS_BLOODLINE'};
YDALIR = {id: 752, name: 'YDALIR'};
N_CHAMPION_INFANTRY_NORSE_LH = {id: 753, name: 'N_CHAMPION_INFANTRY_NORSE_LH'};
N_HEAVY_INFANTRY_NORSE_LH = {id: 754, name: 'N_HEAVY_INFANTRY_NORSE_LH'};
N_MEDIUM_INFANTRY_NORSE_LH = {id: 755, name: 'N_MEDIUM_INFANTRY_NORSE_LH'};

// test if it works
function formatName(originalname) {
    let name = originalname.toString().replace(/<br>/g, '\n').replace(/\n+/g, '\n');
    const items = name.split('\n');
    for (let i = 0; i < items.length; i++) {
        const item = items[i];
        if (items[i].length > 10) {
            let space = item.indexOf(' ');
            if (space !== -1) {
                items[i] = item.slice(0, space) + '\n' + item.slice(space + 1);
                let alternativeSpace = space + 1 + item.slice(space + 1).indexOf(' ');
                if (alternativeSpace !== -1) {
                    if (Math.abs((item.length / 2) - alternativeSpace) < Math.abs((item.length / 2) - space)) {
                        items[i] = item.slice(0, alternativeSpace) + '\n' + item.slice(alternativeSpace + 1);
                    }
                }
            } else {
                let hyphen = item.indexOf('-');
                if (hyphen !== -1) {
                    items[i] = item.slice(0, hyphen) + '-\n' + item.slice(hyphen + 1);
                    let alternativeHyphen = hyphen + 1 + item.slice(hyphen + 1).indexOf('-');
                    if (alternativeHyphen !== -1) {
                        if (Math.abs((item.length / 2) - alternativeHyphen) < Math.abs((item.length / 2) - hyphen)) {
                            items[i] = item.slice(0, alternativeHyphen) + '-\n' + item.slice(alternativeHyphen + 1);
                        }
                    }
                }
            }
        }
    }
    return items.join('\n');
}

class Tree {
    constructor() {
        this.offsets = {
            archaic_1_y: 0,
            archaic_2_y: 0,
            classical_1_y: 0, 
            classical_2_y: 0,
            heroic_1_y: 0,
            heroic_2_y: 0,
            heroic_3_y: 0,
            mythic_1_y: 0,
            mythic_2_y: 0,
        };
        this.height = Math.max(window.innerHeight, 100); // this.height = Math.max(window.innerHeight - 80, 100);
        this.width = 0;
        this.padding = 20;
        this.element_height = 0;
        this.lanes = [];
        this.offsets_x = 150; // 150 is starting offset from the left to accommodate age icons
    }

    // not sure if archaic_1 is correct of if it should be archaic_1_y
    updateOffsets() {
        this.element_height = this.height / 4 / 3;
        let element_offset = this.element_height / 2;

        // console.log('in updateOffsets - this.element_height: ', this.element_height, 'element_offset: ', element_offset);

        this.offsets.archaic_1 = this.padding;
        this.offsets.archaic_2 = this.offsets.archaic_1 + this.element_height + element_offset;
        this.offsets.classical_1 = this.offsets.archaic_2 + this.element_height + element_offset;
        this.offsets.classical_2 = this.offsets.classical_1 + this.element_height + element_offset;
        this.offsets.heroic_1 = this.offsets.classical_2 + this.element_height + element_offset;
        this.offsets.heroic_2 = this.offsets.heroic_1 + this.element_height + element_offset;
        this.offsets.heroic_3 = this.offsets.heroic_2 + this.element_height + element_offset;
        this.offsets.mythic_1 = this.offsets.heroic_3 + this.element_height + element_offset;
        this.offsets.mythic_2 = this.offsets.mythic_1 + this.element_height + element_offset;
    }

    updatePositions() {
        for (let lane of this.lanes) {
            lane.updatePositions(this.offsets, this.element_height);
        }

        let x = this.padding + this.offsets_x;
        for (let i = 0; i < this.lanes.length; i++) {
            this.lanes[i].x = x;
            x = x + this.lanes[i].width + this.padding;
        }
        this.width = x;

        for (let lane of this.lanes) {
            // console.log('this.offsets: ', this.offsets , 'this.element_height: ', this.element_height);
            lane.updatePositions(this.offsets, this.element_height);
        }
    }
}

class Lane {
    constructor() {
        this.rows = {
            archaic_1: [],
            archaic_2: [],
            classical_1: [],
            classical_2: [],
            heroic_1: [],
            heroic_2: [],
            heroic_3: [],
            mythic_1: [],
            mythic_2: [],  
        };
        this.x = 0;
        this.y = 0;
        this.width = 0;
        this.padding = 10;
    }

    updatePositions(offsets, element_length) {
        let lane_width = 0;
        for (let r of Object.keys(this.rows)) {
            let x = this.x;
            let row_width = 0;
            for (let i = 0; i < this.rows[r].length; i++) {
                // console.log('this.rows[r][i].y before: ', this.rows[r][i].y);
                this.rows[r][i].y = offsets[r]; //maybe caret.y is set here
                // console.log('this.rows[r][i].y after: ', this.rows[r][i].y);
                this.rows[r][i].x = x;
                this.rows[r][i].width = element_length;
                this.rows[r][i].height = element_length;
                x = x + this.rows[r][i].width + this.padding;
                row_width = row_width + this.rows[r][i].width + this.padding;
            }
            lane_width = Math.max(lane_width, row_width);
        }
        this.width = lane_width;

        for (let r of Object.keys(this.rows)) {
            for (let i = 0; i < this.rows[r].length; i++) {
                if (this.rows[r][i].isBuilding()) {
                    this.rows[r][i].x = this.x + ((this.width - this.padding) / 2) - (this.rows[r][i].width / 2); //
                }
            }
        }
        // ToDo - add getConnections

        let connections = getConnections();
        // console.log('connections', connections);
        let carets = this.nonBuidingCarets();
        for (let connection of connections) {
            let from = connection[0];
            let to = connection[1]; // not used??
            console.log('connection: ', connection,'from connection[0]: ', from, 'to connection[1]: ', to, 'to.x:', to.x);
            let allConnectionsForFrom = connections.filter(c => c[0] === from && carets.has(c[0]) && carets.has(c[1]));
            let allRelevantTos = allConnectionsForFrom.map(c => c[1]);
            if (carets.has(from) && carets.get(from).x < Math.min(allRelevantTos.map(to_ => carets.get(to_).x))) {
                carets.get(from).x = Math.min(allRelevantTos.map(to_ => carets.get(to_).x));
            }
            if (carets.has(from) && carets.get(from).x > Math.max(allRelevantTos.map(to_ => carets.get(to_).x))) {
                console.assert(allRelevantTos.length === 1, `Overlapping carets: ${allRelevantTos}`)
                allRelevantTos.forEach(to_ => carets.get(to_).x = carets.get(from).x);
            }
        }
    }

    nonBuidingCarets() {
        let c = new Map();
        for (let r of Object.keys(this.rows)) {
            for (let caret of this.rows[r]) {
                if (!caret.isBuilding()) {
                    c.set(caret.id, caret);
                }
            }
        }
        return c;
    }

    caretIds() {
        const idList = [];
        for (let r of Object.keys(this.rows)) {
            for (let i = 0; i < this.rows[r].length; i++) {
                idList.push(this.rows[r][i].id);
            }
        }
        return idList;
    }
}

class Caret {
    constructor(type, name, id) {
        this.type = type;
        this.name = name;
        this.id = PREFIX[type.type] + formatId(id);
        this.width = 100;
        this.height = 100;
        this.x = 0;
        this.y = 0;
    }

    isBuilding() {
        return this.type === TYPES.BUILDING;
    }
}

function formatId(string) {
    // return string.toString().replace(/\s/g, '_').replace(/\//g, '_').toLowerCase();
    return string.toString().toLowerCase();
}

// function getName(id, itemType) {
//     //ToDo handle unique stuff properly
//     if(isFinite.toString().startsWith('UNIQUE')) {
//         return id
//     }
//     const languageNameId = data['data'][itemType][id]['LanguageNameId'];
//     return data['string'][languageNameId];
// }
 
// function building(id) {
//     return new Caret(TYPES.BUILDING, getName(id, 'buildings'), id);
// }

//my first version
// function getName(obj_name_id, itemType) { //(id, itemType)
//     return obj_name_id.name;
// }
// console.log('test123 test123 test123 test123 test123 test123 test123 test123 test123 test123');
function getName(obj_name_id) { //(id, itemType)
    let nameFormatted = obj_name_id.name.toString().replace(/_/g, ' ');
    if (nameFormatted.length > 9) {
        let lastSpaceIndex = nameFormatted.lastIndexOf(' ');
        nameFormatted = `${nameFormatted.slice(0,lastSpaceIndex)}\n${nameFormatted.slice(lastSpaceIndex)}`;
    }
    // console.log('nameFormatted: ', nameFormatted);
    return nameFormatted;
}

function building(obj_name_id) { //(id)
    const caret = new Caret(TYPES.BUILDING, getName(obj_name_id, 'buildings'), obj_name_id.id);
    // console.log('caret: ', caret);
    return caret;
    // return new Caret(TYPES.BUILDING, getName(obj_name_id, 'buildings'), obj_name_id.id);
}

function unit(obj_name_id) { //(id)
    console.log('unit called. obj_name_id: ', obj_name_id)
    // return new Caret(TYPES.UNIT, getName(obj_name_id, 'units'), obj_name_id.id);
    const caret = new Caret(TYPES.UNIT, getName(obj_name_id, 'units'), obj_name_id.id);
    console.log('caret: ', caret);
    return caret;
}

function tech(obj_name_id) { //(id)
    return new Caret(TYPES.TECHNOLOGY, getName(obj_name_id, 'units'), obj_name_id.id);
}

// to-add-blank-dummy-slot
let blankID_Count = 0;
function get_next_BlankID() {
    blankID_Count++;
    
    return `blankID_${blankID_Count}`;
}

function blank_caret() {
    // return new Caret(TYPES.BLANK.type, TYPES.BLANK.name, get_next_BlankID());
    return new Caret(TYPES.BLANK, TYPES.BLANK.name, get_next_BlankID());
}

DUMMY_SLOT = null;

// function getDefaultTree() {
//     let tree = new Tree();
//     tree.updateOffsets();

//     let longhouseLane = new Lane();
//     longhouseLane.rows.classical_1.push(building(LONGHOUSE));
//     // console.log('longhouseLane after 1: ', longhouseLane);
//     longhouseLane.rows.classical_2.push(tech(N_MEDIUM_INFANTRY_NORSE_LH));
//     longhouseLane.rows.classical_2.push(unit(BERSERK));
//     longhouseLane.rows.classical_2.push(unit(THROWING_AXEMAN));
//     longhouseLane.rows.classical_2.push(unit(HIRDMAN));
//     longhouseLane.rows.heroic_1.push(tech(N_HEAVY_INFANTRY_NORSE_LH));
//     longhouseLane.rows.heroic_1.push(tech(LEVY_LONGHOUSE_SOLDIERS));
//     longhouseLane.rows.mythic_1.push(tech(N_CHAMPION_INFANTRY_NORSE_LH))
//     longhouseLane.rows.mythic_1.push(tech(CONSCRIPT_LONGHOUSE_SOLDIERS))
    
//     // console.log('longhouseLane: ', {longhouseLane});
//     tree.lanes.push(longhouseLane);

//     let greatHallLane = new Lane();
//     greatHallLane.rows.classical_1.push(building(GREAT_HALL));
//     greatHallLane.rows.classical_2.push(unit(HERSIR_HERO));
//     greatHallLane.rows.classical_2.push(unit(RAIDING_CAVALRY));
//     greatHallLane.rows.classical_2.push(tech(MEDIUM_CAVALRY_NORSE));
//     greatHallLane.rows.heroic_1.push(unit(GODI_HERO));
//     greatHallLane.rows.heroic_1.push(unit(JARL));
//     greatHallLane.rows.heroic_1.push(tech(HEAVY_CAVALRY_NORSE));
//     greatHallLane.rows.heroic_1.push(tech(LEVY_GREAT_HALL_SOLDIERS));
//     greatHallLane.rows.mythic_1.push(tech(CHAMPION_CAVALRY_NORSE));
//     greatHallLane.rows.mythic_1.push(tech(CONSCRIPT_GREAT_HALL_SOLDIERS));
//     tree.lanes.push(greatHallLane);

//     let hillFortLane = new Lane();
//     hillFortLane.rows.heroic_1.push(building(HILL_FORT));
//     hillFortLane.rows.heroic_2.push(tech(N_MEDIUM_INFANTRY_NORSE_HF));
//     hillFortLane.rows.heroic_3.push(tech(N_HEAVY_INFANTRY_NORSE_HF));
//     hillFortLane.rows.heroic_2.push(unit(HUSKARL));
//     hillFortLane.rows.heroic_2.push(unit(PORTABLE_RAM));
//     hillFortLane.rows.heroic_2.push(tech(DRAFT_HORSES_NORSE));
//     hillFortLane.rows.heroic_2.push(tech(LEVY_HILL_FORT_SOLDIERS));
//     hillFortLane.rows.mythic_1.push(tech(N_CHAMPION_INFANTRY_NORSE_HF));
//     hillFortLane.rows.mythic_1.push(tech(ENGINEERS_NORSE));
//     hillFortLane.rows.mythic_1.push(tech(CONSCRIPT_HILL_FORT_SOLDIERS));
//     hillFortLane.rows.mythic_1.push(unit(BALLISTA));
//     tree.lanes.push(hillFortLane);

//     tree.updatePositions();

//     // return longhouseLane;
//     return tree;
// }

function getDefaultTree() {
    let tree = new Tree();
    tree.updateOffsets();

    let townCenterLane = new Lane();
    townCenterLane.rows.archaic_1.push(building(TOWN_CENTER_NORSE));
    townCenterLane.rows.archaic_2.push(unit(GATHERER));
    townCenterLane.rows.archaic_2.push(unit(DWARF));
    townCenterLane.rows.archaic_2.push(unit(BERSERK));
    townCenterLane.rows.classical_1.push(tech(RIGSTHULA));
    townCenterLane.rows.classical_2.push((tech(MASONS)));
    townCenterLane.rows.heroic_1.push(tech(ARCHITECTS));
    townCenterLane.rows.heroic_2.push((tech(FORTIFIED_TOWN_CENTER)));
    townCenterLane.rows.mythic_1.push(tech(SECRETS_OF_THE_TITANS));

    tree.lanes.push(townCenterLane);

    // // BUG - Shaft Mine and Quarry render directly on top of irrigation and flood control
    // let oxCartLane = new Lane();
    // oxCartLane.rows.archaic_1.push(unit(OX_CART));
    // oxCartLane.rows.archaic_2.push(tech(HUSBANDRY));
    // oxCartLane.rows.archaic_2.push(tech(PICKAXE));
    // oxCartLane.rows.archaic_2.push(tech(HAND_AXE));
    // oxCartLane.rows.classical_1.push(tech(SURVIVAL_EQUIPMENT));
    // oxCartLane.rows.classical_1.push(tech(PLOW));
    // oxCartLane.rows.heroic_1.push(tech(IRRIGATION));
    // oxCartLane.rows.heroic_1.push(tech(SHAFT_MINE));
    // oxCartLane.rows.heroic_1.push(tech(BOW_SAW));
    // oxCartLane.rows.heroic_2.push(tech(WINTER_HARVEST));
    // oxCartLane.rows.mythic_1.push(tech(FLOOD_CONTROL));
    // oxCartLane.rows.mythic_1.push(tech(QUARRY));
    // oxCartLane.rows.mythic_1.push(tech(CARPENTERS));

    let oxCartLane = new Lane();
    oxCartLane.rows.archaic_1.push(unit(OX_CART));
    oxCartLane.rows.archaic_2.push(tech(HUSBANDRY));
    oxCartLane.rows.archaic_2.push(blank_caret());
    oxCartLane.rows.archaic_2.push(tech(PICKAXE));
    oxCartLane.rows.archaic_2.push(tech(HAND_AXE)); 
    oxCartLane.rows.classical_1.push(tech(SURVIVAL_EQUIPMENT));
    oxCartLane.rows.classical_1.push(tech(PLOW));
    
    oxCartLane.rows.heroic_1.push(tech(WINTER_HARVEST));
    oxCartLane.rows.heroic_1.push(tech(IRRIGATION));
    oxCartLane.rows.heroic_1.push(tech(SHAFT_MINE));
    oxCartLane.rows.heroic_1.push(tech(BOW_SAW));
    
    oxCartLane.rows.mythic_1.push(blank_caret());
    oxCartLane.rows.mythic_1.push(tech(FLOOD_CONTROL));
    oxCartLane.rows.mythic_1.push(tech(QUARRY));
    oxCartLane.rows.mythic_1.push(tech(CARPENTERS));
    
    

    tree.lanes.push(oxCartLane);
    
    let houseLane = new Lane();
    houseLane.rows.archaic_1.push(building(HOUSE_NORSE));
    houseLane.rows.classical_1.push(building(FARM_NORSE));

    tree.lanes.push(houseLane);

    let dockLane = new Lane()
    dockLane.rows.archaic_1.push(building(DOCK_NORSE));
    dockLane.rows.archaic_2.push(unit(FISHING_SHIP_NORSE));
    dockLane.rows.classical_1.push(tech(HEROIC_FLEET));
    dockLane.rows.classical_1.push(unit(LONGBOAT));
    dockLane.rows.classical_1.push(unit(DREKI));
    dockLane.rows.classical_1.push(unit(DRAGON_SHIP));
    dockLane.rows.classical_1.push(unit(TRANSPORT_SHIP_NORSE));
    dockLane.rows.classical_2.push(tech(ENCLOSED_DECK));
    dockLane.rows.classical_2.push(tech(PURSE_SEINE));
    dockLane.rows.heroic_1.push(unit(KRAKEN));
    // dockLane.rows.heroic_1.push(tech(ARCTIC_WINDS)); //need to add desc img 
    dockLane.rows.heroic_2.push(tech(WRATH_OF_THE_DEEP));
    dockLane.rows.heroic_2.push(tech(HEAVY_WARSHIPS));
    dockLane.rows.heroic_2.push(tech(SALT_AMPHORA));
    dockLane.rows.mythic_1.push(unit(JORMUN_ELVER));
    dockLane.rows.mythic_1.push(tech(CONSCRIPT_SAILORS));
    dockLane.rows.mythic_1.push(tech(CHAMPION_WARSHIP));
    
    tree.lanes.push(dockLane);

    let templeLane = new Lane();
    templeLane.rows.archaic_1.push(building(TEMPLE_NORSE));
    templeLane.rows.archaic_2.push(unit(HERSIR_HERO));
    templeLane.rows.classical_1.push(unit(VALKYRIE));
    templeLane.rows.classical_1.push(unit(EINHERI));
    templeLane.rows.classical_1.push(tech(SAFEGUARD));
    templeLane.rows.classical_2.push(tech(DISABLOT));
    templeLane.rows.classical_2.push(tech(GJALLARHORN));
    templeLane.rows.heroic_1.push(unit(MOUNTAIN_GIANT));
    templeLane.rows.heroic_1.push(unit(FROST_GIANT));
    templeLane.rows.heroic_2.push(tech(JOTUNS));
    templeLane.rows.heroic_2.push(tech(RIME));
    templeLane.rows.mythic_1.push(tech(OMNISCIENCE));
    templeLane.rows.mythic_1.push(unit(FIRE_GIANT));
    templeLane.rows.mythic_1.push(unit(FENRIS_WOLF_BROOD));

    tree.lanes.push(templeLane);

    let sentryTowerLane = new Lane();
    sentryTowerLane.rows.classical_1.push(building(SENTRY_TOWER_NORSE));
    sentryTowerLane.rows.classical_1.push(tech(WATCH_TOWER));
    sentryTowerLane.rows.classical_2.push(tech(SIGNAL_FIRES));
    sentryTowerLane.rows.classical_2.push(tech(CRENELLATIONS));
    sentryTowerLane.rows.heroic_1.push(tech(CARRIER_PIGEONS));
    sentryTowerLane.rows.heroic_1.push(tech(BOILING_OIL));

    tree.lanes.push(sentryTowerLane);

    let armoryLane = new Lane();
    armoryLane.rows.classical_1.push(building(ARMORY_NORSE));
    armoryLane.rows.classical_2.push(tech(COPPER_WEAPONS));
    armoryLane.rows.classical_2.push(tech(COPPER_ARMOR));
    armoryLane.rows.classical_2.push(tech(COPPER_SHIELDS));
    armoryLane.rows.heroic_1.push(tech(BRONZE_WEAPONS));
    armoryLane.rows.heroic_1.push(tech(COPPER_SHIELDS));
    armoryLane.rows.heroic_1.push(tech(BALLISTA));
    armoryLane.rows.mythic_1.push(tech(IRON_WEAPONS));
    armoryLane.rows.mythic_1.push(tech(IRON_ARMOR));
    armoryLane.rows.mythic_1.push(tech(IRON_SHIELDS));
    armoryLane.rows.mythic_1.push(tech(BURNING_PITCH));

    tree.lanes.push(armoryLane);

    let marketLane = new Lane();
    marketLane.rows.classical_1.push(tech(MARKET_NORSE));
    marketLane.rows.heroic_1.push(unit(OX_CARAVAN));
    marketLane.rows.heroic_1.push(tech(TAX_COLLECTORS));
    marketLane.rows.mythic_1.push(tech(COINAGE));
    marketLane.rows.mythic_1.push(tech(AMBASSADORS));
    
    tree.lanes.push(marketLane);

    let longhouseLane = new Lane();
    longhouseLane.rows.classical_1.push(building(LONGHOUSE));
    // console.log('longhouseLane after 1: ', longhouseLane);
    longhouseLane.rows.classical_2.push(tech(N_MEDIUM_INFANTRY_NORSE_LH));
    longhouseLane.rows.classical_2.push(unit(BERSERK));
    longhouseLane.rows.classical_2.push(unit(THROWING_AXEMAN));
    longhouseLane.rows.classical_2.push(unit(HIRDMAN));
    longhouseLane.rows.classical_2.push(tech(HAMASK));
    longhouseLane.rows.heroic_1.push(tech(N_HEAVY_INFANTRY_NORSE_LH));
    longhouseLane.rows.heroic_1.push(tech(LEVY_LONGHOUSE_SOLDIERS));
    longhouseLane.rows.heroic_1.push(tech(HUNTRESS_AXE));
    longhouseLane.rows.mythic_1.push(tech(N_CHAMPION_INFANTRY_NORSE_LH));
    longhouseLane.rows.mythic_1.push(tech(BERSERKERGANG));
    longhouseLane.rows.mythic_1.push(tech(CONSCRIPT_LONGHOUSE_SOLDIERS));
    
    // console.log('longhouseLane: ', {longhouseLane});
    tree.lanes.push(longhouseLane);

    let greatHallLane = new Lane();
    greatHallLane.rows.classical_1.push(building(GREAT_HALL));
    greatHallLane.rows.classical_2.push(unit(HERSIR_HERO));
    greatHallLane.rows.classical_2.push(unit(RAIDING_CAVALRY));
    greatHallLane.rows.classical_2.push(tech(SESSRUMNIR));
    greatHallLane.rows.classical_2.push(tech(THUNDERING_HOOVES));
    greatHallLane.rows.classical_2.push(tech(MEDIUM_CAVALRY_NORSE));
    greatHallLane.rows.heroic_1.push(unit(GODI_HERO));
    greatHallLane.rows.heroic_1.push(unit(JARL));
    greatHallLane.rows.heroic_1.push(tech(HEAVY_CAVALRY_NORSE));
    greatHallLane.rows.heroic_1.push(tech(LEVY_GREAT_HALL_SOLDIERS));
    greatHallLane.rows.mythic_1.push(tech(CHAMPION_CAVALRY_NORSE));
    greatHallLane.rows.mythic_1.push(tech(CONSCRIPT_GREAT_HALL_SOLDIERS));
    tree.lanes.push(greatHallLane);

    let hillFortLane = new Lane();
    hillFortLane.rows.heroic_1.push(building(HILL_FORT));
    hillFortLane.rows.heroic_2.push(tech(N_MEDIUM_INFANTRY_NORSE_HF));
    hillFortLane.rows.heroic_3.push(tech(N_HEAVY_INFANTRY_NORSE_HF));
    hillFortLane.rows.heroic_2.push(unit(HUSKARL));
    hillFortLane.rows.heroic_2.push(unit(PORTABLE_RAM));
    hillFortLane.rows.heroic_2.push(tech(DRAFT_HORSES_NORSE));
    hillFortLane.rows.heroic_2.push(tech(LEVY_HILL_FORT_SOLDIERS));
    hillFortLane.rows.mythic_1.push(tech(N_CHAMPION_INFANTRY_NORSE_HF));
    hillFortLane.rows.mythic_1.push(tech(ENGINEERS_NORSE));
    hillFortLane.rows.mythic_1.push(tech(CONSCRIPT_HILL_FORT_SOLDIERS));
    hillFortLane.rows.mythic_1.push(unit(BALLISTA));
    tree.lanes.push(hillFortLane);

    tree.updatePositions();

    // return longhouseLane;
    return tree;
}

function u(unit) {
    return 'unit_' + unit;
}

function b(building) {
    return 'building_' + building;
}

function t(tech) {
    return 'tech_' + tech;
}

function getConnections() {
    let connections = [
        [b(TOWN_CENTER_NORSE.id), u(GATHERER.id)],
        [b(TOWN_CENTER_NORSE.id), u(DWARF.id)],
        // [b(TOWN_CENTER_NORSE.id), u(BERSERK.id)], // need to at affixes for tc berserk
        // [b(TOWN_CENTER_NORSE.id), t(MASONS.id)],
        [t(MASONS.id), t(ARCHITECTS.id)],
        // [b(TOWN_CENTER_NORSE.id), t(FORTIFIED_TOWN_CENTER.id)],
        // [b(TOWN_CENTER_NORSE.id), t(SECRETS_OF_THE_TITANS.id)],
        [u(OX_CART.id), t(HUSBANDRY.id)],
        [u(OX_CART.id), t(PICKAXE.id)],
        [u(OX_CART.id), t(HAND_AXE.id)],
        [t(PICKAXE.id), t(SHAFT_MINE.id)],
        [t(SHAFT_MINE.id), t(QUARRY.id)],
        [t(PLOW.id), t(IRRIGATION.id)],
        [t(IRRIGATION.id), t(FLOOD_CONTROL.id)],
        [t(HAND_AXE.id), t(BOW_SAW.id)],
        [t(BOW_SAW.id), t(CARPENTERS.id)],
        [b(DOCK_NORSE.id), u(FISHING_SHIP_NORSE.id)],
        [b(DOCK_NORSE.id), u(LONGBOAT.id)],
        [b(DOCK_NORSE.id), u(DREKI.id)],
        [b(DOCK_NORSE.id), u(DRAGON_SHIP.id)],
        [b(DOCK_NORSE.id), u(TRANSPORT_SHIP_NORSE.id)],
        [b(TEMPLE_NORSE.id), u(HERSIR_HERO.id)],
        [b(TEMPLE_NORSE.id), u(VALKYRIE.id)],
        [b(TEMPLE_NORSE.id), u(EINHERI.id)],
        [b(TEMPLE_NORSE.id), t(SAFEGUARD.id)],
        [u(VALKYRIE.id), t(DISABLOT.id)],
        [u(EINHERI.id), t(GJALLARHORN.id)],
        [b(TEMPLE_NORSE.id), u(MOUNTAIN_GIANT.id)],
        [b(TEMPLE_NORSE.id), u(FROST_GIANT.id)],
        [u(MOUNTAIN_GIANT.id), t(JOTUNS.id)],
        [u(FROST_GIANT.id), t(RIME.id)],
        [b(TEMPLE_NORSE.id), t(OMNISCIENCE.id)],
        [b(TEMPLE_NORSE.id), u(FIRE_GIANT.id)],
        [b(TEMPLE_NORSE.id), u(FENRIS_WOLF_BROOD.id)],

        [u(FISHING_SHIP_NORSE.id), t(PURSE_SEINE.id)],
        [t(PURSE_SEINE.id), t(SALT_AMPHORA.id)],
        [b(LONGHOUSE.id), u(BERSERK.id)],
        [b(LONGHOUSE.id), u(THROWING_AXEMAN.id)],
        [b(LONGHOUSE.id), u(HIRDMAN.id)],
        [b(LONGHOUSE.id), t(N_MEDIUM_INFANTRY_NORSE_LH.id)],
        // [b(LONGHOUSE.id), t(LEVY_LONGHOUSE_SOLDIERS.id)],
        [b(LONGHOUSE.id), t(N_HEAVY_INFANTRY_NORSE_LH.id)],
        [t(LEVY_LONGHOUSE_SOLDIERS.id), t(CONSCRIPT_LONGHOUSE_SOLDIERS.id)],
        [b(LONGHOUSE.id), t(N_CHAMPION_INFANTRY_NORSE_LH.id)],
        [b(GREAT_HALL.id), u(HERSIR_HERO.id)],
        [b(GREAT_HALL.id), u(RAIDING_CAVALRY.id)],
        [b(GREAT_HALL.id), t(MEDIUM_CAVALRY_NORSE.id)],  // MEDIUM_CAVALRY_NORSE = {id: 11, name: "MEDIUM_CAVALRY_NORSE"};
        [b(GREAT_HALL.id), u(GODI_HERO.id)],
        [b(GREAT_HALL.id), u(JARL.id)],
        [b(GREAT_HALL.id), t(HEAVY_CAVALRY_NORSE.id)],
        [b(GREAT_HALL.id), t(LEVY_GREAT_HALL_SOLDIERS.id)],
        [t(HEAVY_CAVALRY_NORSE.id), t(CHAMPION_CAVALRY_NORSE.id)],
        [t(LEVY_GREAT_HALL_SOLDIERS.id), t(CONSCRIPT_GREAT_HALL_SOLDIERS.id)],
        [b(HILL_FORT.id), u(HUSKARL.id)],
        [b(HILL_FORT.id), u(PORTABLE_RAM.id)],
        [b(HILL_FORT.id), t(N_MEDIUM_INFANTRY_NORSE_HF.id)],
        [b(HILL_FORT.id), t(DRAFT_HORSES_NORSE.id)],
        [b(HILL_FORT.id), t(LEVY_HILL_FORT_SOLDIERS.id)],
        [t(N_MEDIUM_INFANTRY_NORSE_HF.id), t(N_HEAVY_INFANTRY_NORSE_HF.id)],
        [t(N_HEAVY_INFANTRY_NORSE_HF.id), t(N_CHAMPION_INFANTRY_NORSE_HF.id)],
        [b(HILL_FORT.id), t(ENGINEERS_NORSE.id)],
        [t(LEVY_HILL_FORT_SOLDIERS.id), t(CONSCRIPT_HILL_FORT_SOLDIERS.id)],
        [b(HILL_FORT.id), u(BALLISTA.id)]

    ];

    let connections_ids = [];
    for (let c of connections) {
        connections_ids.push([formatId(c[0]), formatId(c[1])]);
    }
    return connections_ids;
}

// remove 
function testCrossFileSharing(){
    console.log('cross file sharing successful');
}

function getConnectionPoints(tree) {
    let points = new Map();
    for (let lane of tree.lanes) {
        for (let r of Object.keys(lane.rows)) {
            for (let caret of lane.rows[r]) {
                // console.log('caret: ', caret);
                points.set(caret.id, {
                    x: caret.x + (caret.width / 2),
                    y: caret.y + (caret.height / 2)
                });
            }
        }
    }
    return points;
}