import { ABUNDANCE, ADVANCED_DEFENSES_ST, ADZE_OF_WEPWAWET, AEGIR, AEGIS_SHIELD_AY, AGAVE_BLOOM, AHUIZOTL, ALLUVIAL_CLAY, AME_NO_UZUME, ANASTROPHE, ANCESTORS, ANUBIS, ANUBITE, APHRODITE, APOLLO, ARCADIAN_MEADOW, ARCTIC_WINDS, ARES, ARGIVE_PATRONAGE_DEMETER, ARGIVE_PATRONAGE_ZEUS, ARGONAUTS, ARGUS, ARTEMIS, ASCETIC_PRACTICES, ASGARDIAN_BASTION, ASPER_BLOOD, ASURA, ASYMMETRICAL_BOWS, ATEF_CROWN, ATHENA, ATLAS, AUTOMATON, AUTUMN_OF_ABUNDANCE, AVENGER, AVENGING_SPIRIT, AXE_OF_VENGEANCE, AYOTOCHTLI, BAIHU, BALDR, BAST, BATTLE_BOAR, BEAST_SLAYER, BEHEMOTH, BERSERKERGANG, BITE_OF_THE_SHARK_AY, BLAZING_PRAIRIE, BLOOD_PACT, BOLT, BONE_BOW_AY, BOOK_OF_THOTH, BOTTOMLESS_STOMACH, BRAGI, BRAVERY, BRONZE, BURNING_MALEVOLENCE, CALADRIA, CALL_OF_VALHALLA, CARNIVORA, CAVE_TROLL, CEASEFIRE, CELERITY, CELESTIAL_WEAPONS, CENTAUR, CENTIMANUS, CENTZON_HUITZNAHUA, CENTZON_TOTOCHTIN, CHANEQUE, CHANNELS, CHAOS, CHASING_THE_SUN, CHIMERA, CHIYOU, CHTHONIC_RITES_DK, CIPACTLIS_SCALES, CITADEL, CLAIRVOYANCE, COATEPEC_SHRINES, COATLICUE, COLOSSUS, COMMUNAL_HEARTH, CONDEMNED_SOUL, CORRUPTED_GROUND, COYOLXAUHQUI, COYOLXAUHQUIS_STONE, CREATION, CREATORS_AUSPICE_GOD_BLESSING, CRIMSON_LINEN_DK, CRIOSPHINX, CROCODILOPOLIS, CRUSHING_WAVES, CUICACALLI_TRAINING, CURSE, CYCLOPS, DAKTYLOI, DAN_NO_URA_TACTICS, DARK_WATER_ME, DAUGHTERS_OF_THE_SEA, DEADLY_RAGE, DEADLY_SNARE, DECONSTRUCTION, DEIMOS_SWORD_OF_DREAD_AY, DEN_DEN_DRUMS, DESERT_WIND, DEVOTEES_OF_ATLAS, DIONYSIA, DIONYSUS, DISABLOT, DIVINE_BLOOD, DIVINE_BOOKS_MC, DIVINE_JUDGMENT_AY, DIVINE_LABOR, DIVINE_PREFECTURE, DIVINE_SLASH, DRAGON_TYPHOON, DRAUGR, DROUGHT_SHIPS, DRYAD, DWARVEN_ARMORY, DWARVEN_AUGER, DWARVEN_BREASTPLATE, DWARVEN_MINE, EARTH_MONSTER, EARTH_WALL, EARTHQUAKE, ECLIPSE, EIGHT_BANNERS, EINHERI, ELECTRUM_BULLETS_AY, EMPYRIAN_SPEED, ENCHANTED_HYMN, ENYOS_BOW_OF_HORROR_AR, ETERNAL_HAUNTING, EVENING_STAR, EYES_IN_THE_FOREST, FACE_OF_THE_GORGON, FAFNIR, FATED_ARROWS, FEAST_OF_SUSTENANCE, FEASTS_OF_RENOWN_HF, FEET_OF_THE_JACKAL, FEI_BEASTS, FENRIS_WOLF_BROOD, FIMBULWINTER, FIRE_GIANT, FLAMES_OF_TYPHON, FLAMING_BLOOD, FLAMING_WEAPONS, FLOOD_OF_THE_NILE, FLOWERY_WARS, FORCE_OF_THE_WEST_WIND, FOREST_FIRE, FOREST_PROTECTION, FORGE_OF_OLYMPUS, FORSETI, FOUR_JARS, FRENZIED_DASH, FREYJA, FREYRS_GIFT, FRONTLINE_HEROICS_CB, FROST, FROST_GIANT, FUJIN, FUNERAL_BARGE, FUNERAL_RITES_TC, FURY_OF_THE_FALLEN, GAIA_FOREST, GALES_FURY, GEMINI, GIFT_OF_BEASTS_GOD_BLESSING, GILDED_SHIELDS, GJALLARHORN, GOHEI_WANDS, GOLDEN_APPLES_TC, GOLDEN_KITE_AY, GONGGONG, GOSHINBOKU, GOUMANG, GRACIOUS_HOSPITALITY, GRANITE_BLOOD, GRANITE_MAW, GRASP_OF_RAN, GREAT_FLOOD, GREAT_HUNT, GREATEST_OF_FIFTY, GUARDIAN_OF_IO, GULLINBURSTI, HACHIMAN, HALL_OF_THANES_GH, HALLOWED_WOODLANDS, HALO_OF_THE_SUN, HAMADRYAD, HAMASK, HAMMER_OF_THUNDER_DA, HAND_OF_TALOS, HANNYA_MASK_DJ, HEALING_SPRING, HEART_OF_THE_TITANS, HEAVENLY_BARRAGE, HEIMDALL, HEKATE, HEL, HELIOS, HEPHAESTUS, HEPHAESTUS_REVENGE, HERA, HERBAL_MEDICINE, HERMES, HEROIC_RENEWAL_PE, HESPERIDES_TREE, HESTIA, HIERACOSPHINX, HIPPOCAMPUS, HOOVES_OF_THE_WIND, HORNS_OF_CONSECRATION, HORUS, HOUTU, HUANGDI, HUEHUECOYOTL, HUNDUN, HUNTERS_STRENGTH_AY, HUNTRESS_AXE, HYDRA, HYPERION, IMPERIAL_ORDER, IMPLODE, INARI_OKAMI, INFERNO, INFESTATION, ITZPAPALOTL, IVORY_NETSUKE, JOROGUMO, JOTUNS, KAGURA, KAMAITACHI, KATAGI_DJ, KUAFU_CHIEFTAIN, KUMIKI_CE, KUSANAGI, LABYRINTH_OF_MINOS, LAMPADES, LANCE_OF_STONE, LAST_STAND, LEATHER_FRAME_SHIELD_AY, LEIZUS_SILK_AY, LETO, LIGHTNING_STORM, LIGHTNING_WEAPONS, LOCUST_SWARM, LONG_SERPENT, LORD_OF_HORSES, LULLABY, LURE, LYKAON, MAELSTROM, MAGUEY_CULTIVATION, MALINALXOCHITL, MANTICORE, MAQUIZCOATL, MASTER_OF_WEAPONRY_AY, MECHANICAL_ARTISANS, MEDUSA, METEOR, METZLIAPAN, MICTECAH, MICTLANTECUHTLI, MILITIA, MINAKATATOMI, MINOTAUR, MIRROR_TOWER, MONSTROUS_RAGE, MOUNTAIN_GIANT, MOUNTAINOUS_MIGHT, MUMMY, MYTHIC_REJUVENATION, NAHUALLATOLLI, NEBTY_TC, NECKLACE_OF_EYEBALLS, NECROPOLIS, NEMEAN_LION, NEPHTHYS, NEW_KINGDOM_TC, NEW_MOON, NIDHOGG, NINE_WAVES_HF, NJORD, NUBA, OBSIDIAN_BUTTERFLY, OBSIDIAN_KNAPPING, OBSIDIAN_MIRROR, OCEANUS, OCPATLI_INFUSIONS_CP, OCPATLI_INFUSIONS_WH, OCPATLI_INFUSIONS_NH, OKUNINUSHI, OLD_COYOTES_SPIRIT, OLYMPIAN_PARENTAGE_FT, OLYMPIAN_WEAPONS, OMEN_OF_DEATH, OMEN_OF_MALINALCO, OMETOCHTILS_REVELRY, ONI, ONI_MASK, ONMORAKI, ONMYODO, ORACLE, ORICHALCUM_MAIL_AY, OSIRIS, PAN, PANS_PIONEERS, PATECATL, PEACH_OF_IMMORTALITY, PERCEPTION, PERSEPHONE, PESTILENCE, PETRIFICATION, PETSUCHOS, PHOBOS_SPEAR_OF_PANIC_AY, PHOENIX, PILLAR_OF_TLALOCAN, PIONEER_OF_THE_SKIES, PIOUS_SACRIFICE, PIXIU, PLAGUE_OF_SERPENTS, PLENTY, POSEIDONS_SECRET, POWER_OF_CHAOS, PRECIOUS_BONES_WH, CALL_OF_LYKAION, PROMETHEAN, PROMETHEAN_OFFSPRING, PROMETHEUS, PROPHETIC_SIGHT, PROSPERITY, PROSPEROUS_SEEDS, PTAH, PURGE, QILIN, QILINS_BLESSING, QINGLONG, QIONGQI, QUETZALCOATL, RAGE_OF_SLAUGHTER, RAGNAROK, RAIJIN, RAIJU, RAIN, RAMPAGE, RAVEN, RED_CLIFFS_FLEET, REINCARNATION, RESTLESS_ARMY, RESTORATION, RHEIA, RHEIAS_GIFT, RIGSTHULA, RIME, RING_GIVER, RING_OATH, RISING_TIDE, ROAR_OF_ORTHUS, ROC, ROCK_GIANT, ROCK_SOLID, RUSHOU, SACRED_CATS, SACRED_GATE, SACRED_LAND, SAFEGUARD, SALTWATER_SPRING, SARISSA_AY, SASHIMONO_BANNERMEN, SATYR, SCALLOPED_AXE_AY, SCARAB, SCORCHING_FEATHERS_AY, SCORPION_MAN, SEASIDE_INFILTRATORS, SEKHMET, SENTINEL, SERPENT_SKIRT, SERPENT_SPEAR, SERVANT, SERVANTS_OF_GLORY, SESSRUMNIR, SHADUF_GY, SHAFTS_OF_PLAGUE_AR, SHAKER_OF_HEAVEN, SHARDS_OF_ITZTLI, SHIFTING_SANDS, SHINIGAMI, SHOCKWAVE, SHOGUN, SHOULDER_OF_TALOS, SHRINE_OF_THE_HUNT, SILENT_RESOLVE, SINISTER_DEFIANCE, SIREN, SKADI, SKIN_OF_THE_RHINO, SKY_PASSAGE, SLASH_AND_BURN, SLINGS_OF_THE_SUN_AY, SMITING_GUST, SOBEK_HATHOR, SOJUTSU, SOLAR_BARQUE, SOLAR_SHIELD, SON_OF_LOONG, SON_OF_OSIRIS, SONG_OF_MIDSUMMER, SONS_OF_SLEIPNIR, SONS_OF_THE_SUN, SOUL_GUIDE, SOUTHERN_FIRE, SPEAR_OF_HORUS, SPHINX, SPIDER_LAIR, SPIRIT_OF_MAAT_TC, SPIRITED_CHARGE, SPOILS_OF_WAR, SPY, STARFALL, STING_OF_YAPPAN, STONESKIN_QUINAMETZIN, STRING_OF_HEARTS, STYMPHALIAN_BIRD, SUMO_TRAINING_DJ, SUN_DRIED_MUD_BRICK, SUN_RAY_AR, SWAMPLAND, SWINE_ARRAY, SYLVAN_LORE, TAI_CHI, TAILWIND, TAKEMIKAZUCHI, TAOTIE, TARTARIAN_GATE, TECCIZTECATLS_PENANCE, TEMPEST, TEMPESTUOUS_STORM, TEMPLE_OF_HEALING, TEMPORAL_CHAOS, TEN_FIST_SWORD, TENGU, TENSHU, TEPEYOLLOTLS_REACH, TEPONAZTLI_DRUMS, THE_PEACH_BLOSSOM_SPRING, THEFT_OF_FIRE, THEIA, THORNED_WALLS, THOTH, THRACIAN_HORSES, THUNDER_BURST, THUNDERING_HOOVES, THUNDEROUS_PRESENCE, THURISAZ_RUNE, TITAN_SHIELD, TITANOMACHY, TLALOC, TLALOQUES, TOLOACHE_TRANCE_WH, TONACATEPETL, TORCH_OF_MISFORTUNE, TORNADO, TRAITOR, TROLL, TUNKULUCHU, TUSKS_OF_APEDEMAK, TWILIGHT_OF_THE_GODS_GH, TWISTED_LIMBS, TYR, TZITZIMITL, ULLR, UNDERMINE, UNDERWORLD_INVASION, UNDERWORLD_PASSAGE, VALGALDR, VALKYRIE, VALLEY_OF_THE_KINGS, VALOR, VANISH, VAULTS_OF_EREBUS, VIBRANT_LAND_HC, VIDAR, VIKINGS, VISION, VOLCANIC_FORGE_AR, VOLCANO, VORTEX, WADJET, WALKING_WOODS, WANYUDO, WATATSUMI, WAY_OF_THE_MOON_BUSHIDO, WAY_OF_THE_STORM_BUSHIDO, WAY_OF_THE_SUN_BUSHIDO, WEIGHTLESS_MACE_AY, WILL_OF_KRONOS, WIND_SICKLES, WINGED_MESSENGER, WINGS_OF_ITZPAPALOTL, WINGS_OF_THE_SOUTH, WINTER_HARVEST, WISDOM_OF_NINE, WITHER, WRATH_OF_THE_DEEP, XOLOTL, XUANNU, XUANYUANS_BLOODLINE, YAZI, YDALIR, YIN_AND_YANG_GOD_BLESSING, YINGLONGS_WRATH, ZHUQUE, ZHURONG, BURNT_WATER, MYRMIDON, SHADE_OF_HADES, GASTRAPHETOROS, HETAIROS, HARPY, IRON_GRIP, HYMN_OF_THE_WILDWOOD, GUIDING_FLAME, HARVEST_OF_SOULS_AY, AMAZON_ARCHER, BABOON_OF_SET, } from "./units.js";
export const minorGodLaneMatrices = {
    huitzilopochtli: [
        [BLOOD_PACT, WINGS_OF_THE_SOUTH], // archaic_1  
        [], // archaic_2 
        [PATECATL, AGAVE_BLOOM, CENTZON_TOTOCHTIN, OMETOCHTILS_REVELRY, OCPATLI_INFUSIONS_CP, MAGUEY_CULTIVATION], // classical_1 
        [MALINALXOCHITL, INFESTATION, MAQUIZCOATL, OMEN_OF_MALINALCO, STING_OF_YAPPAN, TOLOACHE_TRANCE_WH], // classical_2
        [COATLICUE, EARTH_MONSTER, AYOTOCHTLI, SERPENT_SKIRT, COATEPEC_SHRINES, STRING_OF_HEARTS, CIPACTLIS_SCALES], // heroic_1
        [ITZPAPALOTL, PURGE, OBSIDIAN_BUTTERFLY, WINGS_OF_ITZPAPALOTL, OBSIDIAN_KNAPPING, FLOWERY_WARS, SHARDS_OF_ITZTLI], // heroic_2
        [TLALOC, PILLAR_OF_TLALOCAN, AHUIZOTL, BURNT_WATER, TLALOQUES, TONACATEPETL, FOUR_JARS], // heroic_3
        [MICTLANTECUHTLI, VOLCANO, TUNKULUCHU, NECKLACE_OF_EYEBALLS, OMEN_OF_DEATH, PRECIOUS_BONES_WH, MICTECAH], // mythic_1
        [], // mythic_2
    ],
    tezcatlipoca: [
        [OBSIDIAN_MIRROR, TEPEYOLLOTLS_REACH], // archaic_1  
        [], // archaic_2 
        [MALINALXOCHITL, INFESTATION, MAQUIZCOATL, OMEN_OF_MALINALCO, STING_OF_YAPPAN, TOLOACHE_TRANCE_WH], // classical_1 
        [HUEHUECOYOTL, LULLABY, CHANEQUE, OLD_COYOTES_SPIRIT, CUICACALLI_TRAINING, TEPONAZTLI_DRUMS, NAHUALLATOLLI], // classical_2
        [COYOLXAUHQUI, STARFALL, TZITZIMITL, CENTZON_HUITZNAHUA, COYOLXAUHQUIS_STONE, TECCIZTECATLS_PENANCE, METZLIAPAN], // heroic_1
        [ITZPAPALOTL, PURGE, OBSIDIAN_BUTTERFLY, WINGS_OF_ITZPAPALOTL, OBSIDIAN_KNAPPING, FLOWERY_WARS, SHARDS_OF_ITZTLI], // heroic_2
        [XOLOTL, CORRUPTED_GROUND, SOUL_GUIDE, TORCH_OF_MISFORTUNE, EVENING_STAR, TWISTED_LIMBS, STONESKIN_QUINAMETZIN], // heroic_3
        [MICTLANTECUHTLI, VOLCANO, TUNKULUCHU, NECKLACE_OF_EYEBALLS, OMEN_OF_DEATH, PRECIOUS_BONES_WH, MICTECAH], // mythic_1
        [], // mythic_2
    ],
    quetzalcoatl: [
        [TAILWIND, FEAST_OF_SUSTENANCE], // archaic_1  
        [], // archaic_2 
        [PATECATL, AGAVE_BLOOM, CENTZON_TOTOCHTIN, OMETOCHTILS_REVELRY, OCPATLI_INFUSIONS_CP, MAGUEY_CULTIVATION], // classical_1 
        [HUEHUECOYOTL, LULLABY, CHANEQUE, OLD_COYOTES_SPIRIT, CUICACALLI_TRAINING, TEPONAZTLI_DRUMS, NAHUALLATOLLI], // classical_2
        [COATLICUE, EARTH_MONSTER, AYOTOCHTLI, SERPENT_SKIRT, COATEPEC_SHRINES, STRING_OF_HEARTS, CIPACTLIS_SCALES], // heroic_1
        [COYOLXAUHQUI, STARFALL, TZITZIMITL, CENTZON_HUITZNAHUA, COYOLXAUHQUIS_STONE, TECCIZTECATLS_PENANCE, METZLIAPAN], // heroic_2
        [TLALOC, PILLAR_OF_TLALOCAN, AHUIZOTL, BURNT_WATER, TLALOQUES, TONACATEPETL, FOUR_JARS], // heroic_3
        [XOLOTL, CORRUPTED_GROUND, SOUL_GUIDE, TORCH_OF_MISFORTUNE, EVENING_STAR, TWISTED_LIMBS, STONESKIN_QUINAMETZIN], // mythic_1
        [], // mythic_2
    ],
    amaterasu: [
        [SOLAR_SHIELD, WAY_OF_THE_SUN_BUSHIDO, KAGURA], // archaic_1  
        [], // archaic_2 
        [AME_NO_UZUME, GOSHINBOKU, KAMAITACHI, WIND_SICKLES, KATAGI_DJ, GOHEI_WANDS], // classical_1 
        [MINAKATATOMI, SHRINE_OF_THE_HUNT, WANYUDO, CONDEMNED_SOUL, SALTWATER_SPRING, HUNTERS_STRENGTH_AY, KUMIKI_CE], // classical_2
        [HACHIMAN, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE_AY, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
        [RAIJIN, THUNDER_BURST, RAIJU, THUNDEROUS_PRESENCE, DEN_DEN_DRUMS, HANNYA_MASK_DJ, HEAVENLY_BARRAGE], // heroic_2
        [TAKEMIKAZUCHI, DIVINE_SLASH, ASURA, BURNING_MALEVOLENCE, SUMO_TRAINING_DJ, TEN_FIST_SWORD, SOJUTSU], // heroic_3
        [OKUNINUSHI, SACRED_GATE, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
        [], // mythic_2
    ],
    tsukuyomi: [
        [NEW_MOON, WAY_OF_THE_MOON_BUSHIDO, TENSHU], // archaic_1  
        [], // archaic_2 
        [AME_NO_UZUME, GOSHINBOKU, KAMAITACHI, WIND_SICKLES, KATAGI_DJ, GOHEI_WANDS], // classical_1
        [INARI_OKAMI, SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
        [HACHIMAN, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE_AY, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
        [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_2
        [WATATSUMI, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO, ASYMMETRICAL_BOWS], // heroic_3
        [OKUNINUSHI, SACRED_GATE, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
        [], // mythic_2
    ],
    susanoo: [
        [KUSANAGI, WAY_OF_THE_STORM_BUSHIDO, CRUSHING_WAVES], // archaic_1
        [], // archaic_2 
        [MINAKATATOMI, SHRINE_OF_THE_HUNT, WANYUDO, CONDEMNED_SOUL, SALTWATER_SPRING, HUNTERS_STRENGTH_AY, KUMIKI_CE], // classical_1
        [INARI_OKAMI, SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
        [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_1
        [RAIJIN, THUNDER_BURST, RAIJU, THUNDEROUS_PRESENCE, DEN_DEN_DRUMS, HANNYA_MASK_DJ, HEAVENLY_BARRAGE], // heroic_2
        [TAKEMIKAZUCHI, DIVINE_SLASH, ASURA, BURNING_MALEVOLENCE, SUMO_TRAINING_DJ, TEN_FIST_SWORD, SOJUTSU], // heroic_3
        [WATATSUMI, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO, ASYMMETRICAL_BOWS], // mythic_1
        [], // mythic_2
    ],
    fuxi: [
        [THE_PEACH_BLOSSOM_SPRING, YIN_AND_YANG_GOD_BLESSING, CELESTIAL_WEAPONS, TAI_CHI],
        [], // archaic_2 
        [XUANNU, VANISH, QILIN, DIVINE_BOOKS_MC, REINCARNATION, QILINS_BLESSING], // classical_1
        [CHIYOU, LIGHTNING_WEAPONS, YAZI, MASTER_OF_WEAPONRY_AY, SPOILS_OF_WAR, SON_OF_LOONG, RAGE_OF_SLAUGHTER], // classical_2
        [GOUMANG, FOREST_PROTECTION, VIBRANT_LAND_HC, HOOVES_OF_THE_WIND, FRENZIED_DASH, MAELSTROM], // heroic_1
        [NUBA, DROUGHT_SHIPS, TAOTIE, SCORCHING_FEATHERS_AY, ROCK_SOLID, BOTTOMLESS_STOMACH, DROUGHT_SHIPS], // heroic_2
        [GONGGONG, GREAT_FLOOD, QINGLONG, SHAKER_OF_HEAVEN, TEMPESTUOUS_STORM, LAST_STAND, RISING_TIDE], // heroic_3
        [HUANGDI, YINGLONGS_WRATH, HUNDUN, XUANYUANS_BLOODLINE, LEIZUS_SILK_AY, IMPERIAL_ORDER, POWER_OF_CHAOS], // mythic_1
        [], // mythic_2
    ],
    nuwa: [
        [CREATION, CREATORS_AUSPICE_GOD_BLESSING, KUAFU_CHIEFTAIN, MOUNTAINOUS_MIGHT],
        [], // archaic_2 
        [XUANNU, VANISH, QILIN, DIVINE_BOOKS_MC, REINCARNATION, QILINS_BLESSING], // classical_1
        [HOUTU, EARTH_WALL, QIONGQI, ADVANCED_DEFENSES_ST, CHASING_THE_SUN, ABUNDANCE, SINISTER_DEFIANCE], // classical_2
        [GOUMANG, FOREST_PROTECTION, VIBRANT_LAND_HC, HOOVES_OF_THE_WIND, FRENZIED_DASH, MAELSTROM], // heroic_1
        [RUSHOU, FEI_BEASTS, BAIHU, PIXIU, GILDED_SHIELDS, DIVINE_JUDGMENT_AY, AUTUMN_OF_ABUNDANCE, RED_CLIFFS_FLEET], // heroic_2
        [GONGGONG, GREAT_FLOOD, QINGLONG, SHAKER_OF_HEAVEN, TEMPESTUOUS_STORM, LAST_STAND, RISING_TIDE], // heroic_3
        [ZHURONG, BLAZING_PRAIRIE, ZHUQUE, FLAMING_BLOOD, SLASH_AND_BURN, SONG_OF_MIDSUMMER, SOUTHERN_FIRE], // mythic_1
        [], // mythic_2
    ],
    shennong: [
        [PROSPEROUS_SEEDS, GIFT_OF_BEASTS_GOD_BLESSING, HERBAL_MEDICINE, PEACH_OF_IMMORTALITY],
        [], // archaic_2 
        [HOUTU, EARTH_WALL, QIONGQI, ADVANCED_DEFENSES_ST, CHASING_THE_SUN, ABUNDANCE, SINISTER_DEFIANCE], // classical_1
        [CHIYOU, LIGHTNING_WEAPONS, YAZI, MASTER_OF_WEAPONRY_AY, SPOILS_OF_WAR, SON_OF_LOONG, RAGE_OF_SLAUGHTER], // classical_2
        [RUSHOU, FEI_BEASTS, BAIHU, PIXIU, GILDED_SHIELDS, DIVINE_JUDGMENT_AY, AUTUMN_OF_ABUNDANCE, RED_CLIFFS_FLEET], // heroic_1
        [NUBA, DECONSTRUCTION, TAOTIE, SCORCHING_FEATHERS_AY, ROCK_SOLID, BOTTOMLESS_STOMACH, DROUGHT_SHIPS], // heroic_2
        [ZHURONG, BLAZING_PRAIRIE, ZHUQUE, FLAMING_BLOOD, SLASH_AND_BURN, SONG_OF_MIDSUMMER, SOUTHERN_FIRE], // heroic_3
        [HUANGDI, YINGLONGS_WRATH, HUNDUN, XUANYUANS_BLOODLINE, LEIZUS_SILK_AY, IMPERIAL_ORDER, POWER_OF_CHAOS], // mythic_1
        [], // mythic_2
    ],
    zeus: [
        [BOLT, MYRMIDON, OLYMPIAN_PARENTAGE_FT], // archaic_1
        [], // archaic_2
        [ATHENA, RESTORATION, MINOTAUR, LABYRINTH_OF_MINOS, AEGIS_SHIELD_AY, SARISSA_AY], // classical_1
        [HERMES, CEASEFIRE, CENTAUR, SYLVAN_LORE, SPIRITED_CHARGE, WINGED_MESSENGER], // classical_2
        [APOLLO, UNDERWORLD_PASSAGE, MANTICORE, ORACLE, TEMPLE_OF_HEALING, SUN_RAY_AR, ANASTROPHE], // heroic_1
        [DIONYSUS, BRONZE, HYDRA, CHTHONIC_RITES_DK, DIONYSIA, THRACIAN_HORSES], // heroic_2
        [HEPHAESTUS, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
        [HERA, LIGHTNING_STORM, MEDUSA, ARGIVE_PATRONAGE_ZEUS, FACE_OF_THE_GORGON, MONSTROUS_RAGE], // mythic_1
        [], // mythic_2
    ],
    hades: [
        [SENTINEL, SHADE_OF_HADES, GASTRAPHETOROS, VAULTS_OF_EREBUS], // archaic_1 // need to change SENTINEL to type = tech, bolt is placeholder to prevent error
        [], // archaic_2
        [ATHENA, RESTORATION, MINOTAUR, LABYRINTH_OF_MINOS, AEGIS_SHIELD_AY, SARISSA_AY], // classical_1
        [ARES, PESTILENCE, CYCLOPS, PHOBOS_SPEAR_OF_PANIC_AY, WILL_OF_KRONOS, ENYOS_BOW_OF_HORROR_AR, DEIMOS_SWORD_OF_DREAD_AY], // classical_2
        [APOLLO, UNDERWORLD_PASSAGE, MANTICORE, ORACLE, TEMPLE_OF_HEALING, SUN_RAY_AR, ANASTROPHE], // heroic_1
        [APHRODITE, CURSE, NEMEAN_LION, GOLDEN_APPLES_TC, DIVINE_BLOOD, ROAR_OF_ORTHUS, ARGONAUTS], // heroic_2
        [HEPHAESTUS, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
        [ARTEMIS, EARTHQUAKE, CHIMERA, FLAMES_OF_TYPHON, SHAFTS_OF_PLAGUE_AR, BEAST_SLAYER], // mythic_1
        [], // mythic_2
    ],
    poseidon: [
        [LURE, HIPPOCAMPUS, MILITIA, HETAIROS, LORD_OF_HORSES], // archaic_1
        [], // archaic_2
        [ARES, PESTILENCE, CYCLOPS, PHOBOS_SPEAR_OF_PANIC_AY, WILL_OF_KRONOS, ENYOS_BOW_OF_HORROR_AR, DEIMOS_SWORD_OF_DREAD_AY], // classical_1
        [HERMES, CEASEFIRE, CENTAUR, SYLVAN_LORE, SPIRITED_CHARGE, WINGED_MESSENGER], // classical_2
        [APHRODITE, CURSE, NEMEAN_LION, GOLDEN_APPLES_TC, DIVINE_BLOOD, ROAR_OF_ORTHUS, ARGONAUTS], // heroic_1
        [DIONYSUS, BRONZE, HYDRA, CHTHONIC_RITES_DK, DIONYSIA, THRACIAN_HORSES], // heroic_2
        [HEPHAESTUS, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
        [ARTEMIS, EARTHQUAKE, CHIMERA, FLAMES_OF_TYPHON, SHAFTS_OF_PLAGUE_AR, BEAST_SLAYER], // mythic_1
        [], // mythic_2
    ],
    demeter: [
        [WITHER, HARPY, AMAZON_ARCHER, DIVINE_LABOR, IRON_GRIP], // archaic_1
        [], // archaic_2
        [ARES, PESTILENCE, CYCLOPS, PHOBOS_SPEAR_OF_PANIC_AY, WILL_OF_KRONOS, ENYOS_BOW_OF_HORROR_AR, DEIMOS_SWORD_OF_DREAD_AY], // classical_1
        [PAN, ARCADIAN_MEADOW, LYKAON, THORNED_WALLS, PANS_PIONEERS, CALL_OF_LYKAION, HYMN_OF_THE_WILDWOOD], // classical_2
        [APHRODITE, CURSE, NEMEAN_LION, GOLDEN_APPLES_TC, DIVINE_BLOOD, ROAR_OF_ORTHUS, ARGONAUTS], // heroic_1
        [HESTIA, COMMUNAL_HEARTH, HAMADRYAD, GRACIOUS_HOSPITALITY, HALLOWED_WOODLANDS, FATED_ARROWS, GUIDING_FLAME], // heroic_2
        [HERA, LIGHTNING_STORM, MEDUSA, ARGIVE_PATRONAGE_DEMETER, FACE_OF_THE_GORGON, MONSTROUS_RAGE], // heroic_3
        [PERSEPHONE, UNDERWORLD_INVASION, SIREN, SACRED_LAND, ENCHANTED_HYMN, PIOUS_SACRIFICE, HARVEST_OF_SOULS_AY], // mythic_1
        [], // mythic_2
    ],
    ra: [
        [RAIN, SKIN_OF_THE_RHINO], // archaic_1
        [], // archaic_2
        [BAST, ECLIPSE, SPHINX, SACRED_CATS, ADZE_OF_WEPWAWET, CRIOSPHINX, HIERACOSPHINX], // classical_1
        [PTAH, SHIFTING_SANDS, WADJET, SCALLOPED_AXE_AY, LEATHER_FRAME_SHIELD_AY, ELECTRUM_BULLETS_AY, SHADUF_GY], // classical_2
        [SOBEK_HATHOR, LOCUST_SWARM, ROC, PETSUCHOS, CROCODILOPOLIS, SUN_DRIED_MUD_BRICK, DARK_WATER_ME, SOLAR_BARQUE], // heroic_1
        [SEKHMET, CITADEL, SCARAB, BONE_BOW_AY, SLINGS_OF_THE_SUN_AY, CRIMSON_LINEN_DK, FORCE_OF_THE_WEST_WIND], // heroic_2
        [OSIRIS, SON_OF_OSIRIS, MUMMY, DESERT_WIND, NEW_KINGDOM_TC, ATEF_CROWN], // heroic_3
        [HORUS, TORNADO, AVENGER, AXE_OF_VENGEANCE, SPEAR_OF_HORUS, GREATEST_OF_FIFTY], // mythic_1
        [], // mythic_2
    ],
    isis: [
        [PROSPERITY, FLOOD_OF_THE_NILE], // archaic_1
        [], // archaic_2
        [BAST, ECLIPSE, SPHINX, SACRED_CATS, ADZE_OF_WEPWAWET, CRIOSPHINX, HIERACOSPHINX], // classical_1
        [ANUBIS, PLAGUE_OF_SERPENTS, ANUBITE, FEET_OF_THE_JACKAL, SERPENT_SPEAR, NECROPOLIS], // classical_2
        [SOBEK_HATHOR, LOCUST_SWARM, ROC, PETSUCHOS, CROCODILOPOLIS, SUN_DRIED_MUD_BRICK, DARK_WATER_ME, SOLAR_BARQUE], // heroic_1
        [NEPHTHYS, ANCESTORS, SCORPION_MAN, FUNERAL_RITES_TC, SPIRIT_OF_MAAT_TC, NEBTY_TC, FUNERAL_BARGE], // heroic_2
        [OSIRIS, SON_OF_OSIRIS, MUMMY, DESERT_WIND, NEW_KINGDOM_TC, ATEF_CROWN], // heroic_3
        [THOTH, METEOR, PHOENIX, VALLEY_OF_THE_KINGS, BOOK_OF_THOTH, TUSKS_OF_APEDEMAK], // mythic_1
        [], // mythic_2
    ],
    set: [
        [VISION, BABOON_OF_SET, CLAIRVOYANCE], // archaic_1 
        [], // archaic_2
        [ANUBIS, PLAGUE_OF_SERPENTS, ANUBITE, FEET_OF_THE_JACKAL, SERPENT_SPEAR, NECROPOLIS], // classical_1
        [PTAH, SHIFTING_SANDS, WADJET, SCALLOPED_AXE_AY, LEATHER_FRAME_SHIELD_AY, ELECTRUM_BULLETS_AY, SHADUF_GY], // classical_2
        [SEKHMET, CITADEL, SCARAB, BONE_BOW_AY, SLINGS_OF_THE_SUN_AY, CRIMSON_LINEN_DK, FORCE_OF_THE_WEST_WIND], // heroic_1
        [NEPHTHYS, ANCESTORS, SCORPION_MAN, FUNERAL_RITES_TC, SPIRIT_OF_MAAT_TC, NEBTY_TC, FUNERAL_BARGE], // heroic_2
        [THOTH, METEOR, PHOENIX, VALLEY_OF_THE_KINGS, BOOK_OF_THOTH, TUSKS_OF_APEDEMAK], // heroic_3
        [HORUS, TORNADO, AVENGER, AXE_OF_VENGEANCE, SPEAR_OF_HORUS, GREATEST_OF_FIFTY], // mythic_1
        [], // mythic_2
    ],
    thor: [
        [GULLINBURSTI, DWARVEN_ARMORY, HAMMER_OF_THUNDER_DA], // archaic_1 //DWARVEN_MINE is type=tech need to change to god power
        [], // archaic_2
        [FREYJA, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
        [FORSETI, HEALING_SPRING, TROLL, HALL_OF_THANES_GH, DWARVEN_BREASTPLATE, CAVE_TROLL], // classical_2
        [SKADI, FROST, FROST_GIANT, RIME, HUNTRESS_AXE, WINTER_HARVEST, ARCTIC_WINDS], // heroic_1
        [BRAGI, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_2
        [BALDR, RAGNAROK, FIRE_GIANT, SONS_OF_SLEIPNIR, DWARVEN_AUGER], // heroic_3
        [TYR, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
        [], // mythic_2
    ],
    odin: [
        [GREAT_HUNT, RAVEN, HAMASK], // archaic_1
        [], // archaic_2
        [FREYJA, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
        [HEIMDALL, UNDERMINE, EINHERI, GJALLARHORN, SAFEGUARD, RIGSTHULA], // classical_2
        [SKADI, FROST, FROST_GIANT, RIME, HUNTRESS_AXE, WINTER_HARVEST, ARCTIC_WINDS], // heroic_1
        [NJORD, WALKING_WOODS, MOUNTAIN_GIANT, RING_GIVER, VIKINGS, JOTUNS, WRATH_OF_THE_DEEP], // heroic_2
        [BALDR, RAGNAROK, FIRE_GIANT, SONS_OF_SLEIPNIR, DWARVEN_AUGER], // heroic_3
        [TYR, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
        [], // mythic_2
    ],
    loki: [
        [SPY, EYES_IN_THE_FOREST], // archaic_1
        [], // archaic_2
        [FORSETI, HEALING_SPRING, TROLL, HALL_OF_THANES_GH, DWARVEN_BREASTPLATE, CAVE_TROLL], // classical_1
        [HEIMDALL, UNDERMINE, EINHERI, GJALLARHORN, SAFEGUARD, RIGSTHULA], // classical_2
        [BRAGI, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_1
        [NJORD, WALKING_WOODS, MOUNTAIN_GIANT, RING_GIVER, VIKINGS, JOTUNS, WRATH_OF_THE_DEEP], // heroic_2
        [HEL, NIDHOGG, FIRE_GIANT, FROST_GIANT, MOUNTAIN_GIANT, RAMPAGE, GRANITE_BLOOD], // heroic_3
        [TYR, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
        [], // mythic_2
    ],
    freyr: [
        [GULLINBURSTI, FREYRS_GIFT], // archaic_1
        [], // archaic_2
        [FREYJA, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
        [ULLR, ASGARDIAN_BASTION, DRAUGR, VALGALDR, SERVANTS_OF_GLORY, RING_OATH, YDALIR], // classical_2
        [BRAGI, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_1
        [AEGIR, TEMPEST, ROCK_GIANT, GRANITE_MAW, FEASTS_OF_RENOWN_HF, NINE_WAVES_HF, GRASP_OF_RAN], // heroic_2
        [HEL, NIDHOGG, FIRE_GIANT, FROST_GIANT, MOUNTAIN_GIANT, RAMPAGE, GRANITE_BLOOD], // heroic_3
        [VIDAR, INFERNO, FAFNIR, TWILIGHT_OF_THE_GODS_GH, AVENGING_SPIRIT, SILENT_RESOLVE, FURY_OF_THE_FALLEN], // mythic_1
        [], // mythic_2
    ],
    kronos: [
        [DECONSTRUCTION, TEMPORAL_CHAOS], // archaic_1
        [], // archaic_2
        [PROMETHEUS, VALOR, PROMETHEAN, ALLUVIAL_CLAY, HEART_OF_THE_TITANS, THEFT_OF_FIRE], // classical_1
        [LETO, SPIDER_LAIR, AUTOMATON, HEPHAESTUS_REVENGE, VOLCANIC_FORGE_AR, PERCEPTION], // classical_2
        [HYPERION, CHAOS, SATYR, GEMINI, HEROIC_RENEWAL_PE, SONS_OF_THE_SUN, PIONEER_OF_THE_SKIES], // heroic_1
        [RHEIA, TRAITOR, BEHEMOTH, HORNS_OF_CONSECRATION, ORICHALCUM_MAIL_AY, RHEIAS_GIFT, DAKTYLOI], // heroic_2
        [HELIOS, VORTEX, CENTIMANUS, MIRROR_TOWER, HALO_OF_THE_SUN, PETRIFICATION, TITANOMACHY], // heroic_3
        [ATLAS, IMPLODE, ARGUS, GUARDIAN_OF_IO, DEVOTEES_OF_ATLAS, TITAN_SHIELD], // mythic_1
        [], // mythic_2
    ],
    oranos: [
        [SHOCKWAVE, SKY_PASSAGE, EMPYRIAN_SPEED], // archaic_1
        [], // archaic_2
        [PROMETHEUS, VALOR, PROMETHEAN, ALLUVIAL_CLAY, HEART_OF_THE_TITANS, THEFT_OF_FIRE], // classical_1
        [OCEANUS, CARNIVORA, CALADRIA, SERVANT, BITE_OF_THE_SHARK_AY, WEIGHTLESS_MACE_AY, FRONTLINE_HEROICS_CB], // classical_2
        [HYPERION, CHAOS, SATYR, GEMINI, HEROIC_RENEWAL_PE, SONS_OF_THE_SUN, PIONEER_OF_THE_SKIES], // heroic_1
        [THEIA, HESPERIDES_TREE, STYMPHALIAN_BIRD, DRYAD, PROPHETIC_SIGHT, POSEIDONS_SECRET, LANCE_OF_STONE, DAUGHTERS_OF_THE_SEA], // heroic_2
        [HELIOS, VORTEX, CENTIMANUS, MIRROR_TOWER, HALO_OF_THE_SUN, PETRIFICATION, TITANOMACHY], // heroic_3
        [HEKATE, TARTARIAN_GATE, LAMPADES, ASPER_BLOOD, MYTHIC_REJUVENATION, CELERITY], // mythic_1
        [], // mythic_2
    ],
    gaia: [
        [GAIA_FOREST, CHANNELS], // archaic_1
        [], // archaic_2
        [OCEANUS, CARNIVORA, CALADRIA, SERVANT, BITE_OF_THE_SHARK_AY, WEIGHTLESS_MACE_AY, FRONTLINE_HEROICS_CB], // classical_1
        [LETO, SPIDER_LAIR, AUTOMATON, HEPHAESTUS_REVENGE, VOLCANIC_FORGE_AR, PERCEPTION], // classical_2
        [THEIA, HESPERIDES_TREE, STYMPHALIAN_BIRD, DRYAD, PROPHETIC_SIGHT, POSEIDONS_SECRET, LANCE_OF_STONE, DAUGHTERS_OF_THE_SEA], // heroic_1
        [RHEIA, TRAITOR, BEHEMOTH, HORNS_OF_CONSECRATION, ORICHALCUM_MAIL_AY, RHEIAS_GIFT, DAKTYLOI], // heroic_2
        [HEKATE, TARTARIAN_GATE, LAMPADES, ASPER_BLOOD, MYTHIC_REJUVENATION, CELERITY], // heroic_3
        [ATLAS, IMPLODE, ARGUS, GUARDIAN_OF_IO, DEVOTEES_OF_ATLAS, TITAN_SHIELD], // mythic_1
        [], // mythic_2
    ],
};
//# sourceMappingURL=minorGodLaneMatrices.js.map