import { BARRACKS, FARM_AZTEC, HOUSE_AZTEC, MONUMENT_TO_GODS, MONUMENT_TO_PHARAOHS, MONUMENT_TO_PRIESTS, MONUMENT_TO_SOLDIERS, MONUMENT_TO_VILLAGERS, TITAN_GATE, WOODEN_WALL_AZTEC } from "./units.js";

const buildingCaretsToSkipCenteringFor = [TITAN_GATE, BARRACKS, MONUMENT_TO_VILLAGERS, MONUMENT_TO_SOLDIERS, MONUMENT_TO_PRIESTS, MONUMENT_TO_PHARAOHS, MONUMENT_TO_GODS, WOODEN_WALL_AZTEC, FARM_AZTEC, HOUSE_AZTEC];

export const buildingCaretsToSkipCenteringForId = buildingCaretsToSkipCenteringFor.map(caret => `building_${String(caret.id)}`);