import { BLANK } from "./addNewLaneToTree.js"
import { ABUNDANCE, ADVANCED_DEFENSES_ST, ADZE_OF_WEPWAWET, AEGIR_minor_god, AEGIS_SHIELD_AY, AGAVE_BLOOM, AHUIZOTL, ALLUVIAL_CLAY, AME_NO_UZUME_minor_god, ANASTROPHE, ANCESTORS, ANUBIS_minor_god, ANUBITE, APHRODITE_minor_god, APOLLO_minor_god, ARCADIAN_MEADOW, ARCTIC_WINDS, ARES_minor_god, ARGIVE_PATRONAGE_DEMETER, ARGIVE_PATRONAGE_ZEUS, ARGONAUTS, ARGUS, ARTEMIS_minor_god, ASCETIC_PRACTICES, ASGARDIAN_BASTION, ASPER_BLOOD, ASURA, ASYMMETRICAL_BOWS, ATEF_CROWN, ATHENA_minor_god, ATLAS_minor_god, AUTOMATON, AUTUMN_OF_ABUNDANCE, AVENGER, AVENGING_SPIRIT, AXE_OF_VENGEANCE, AYOTOCHTLI, BAIHU, BALDR_minor_god, BAST_minor_god, BATTLE_BOAR, BEAST_SLAYER, BEHEMOTH, BERSERKERGANG, BITE_OF_THE_SHARK_AY, BLAZING_PRAIRIE, BLOOD_PACT, BOLT, BONE_BOW_AY, BOOK_OF_THOTH, BOTTOMLESS_STOMACH, BRAGI_minor_god, BRAVERY, BRONZE, BURNING_MALEVOLENCE, CALADRIA, CALL_OF_VALHALLA, CARNIVORA, CAVE_TROLL, CEASEFIRE, CELERITY, CELESTIAL_WEAPONS, CENTAUR, CENTIMANUS, CENTZON_HUITZNAHUA, CENTZON_TOTOCHTIN, CHANEQUE, CHANNELS, CHAOS, CHASING_THE_SUN, CHIMERA, CHIYOU_minor_god, CHTHONIC_RITES_DK, CIPACTLIS_SCALES, CITADEL, CLAIRVOYANCE, COATEPEC_SHRINES, COATLICUE_minor_god, COLOSSUS, COMMUNAL_HEARTH_god_power, CONDEMNED_SOUL, CORRUPTED_GROUND, COYOLXAUHQUI_minor_god, COYOLXAUHQUIS_STONE, CREATION, CREATORS_AUSPICE_GOD_BLESSING, CRIMSON_LINEN_DK, CRIOSPHINX, CROCODILOPOLIS, CRUSHING_WAVES, CUICACALLI_TRAINING, CURSE, CYCLOPS, DAKTYLOI, DAN_NO_URA_TACTICS, DARK_WATER_ME, DAUGHTERS_OF_THE_SEA, DEADLY_RAGE, DEADLY_SNARE, DECONSTRUCTION, DEIMOS_SWORD_OF_DREAD_AY, DEN_DEN_DRUMS, DESERT_WIND, DEVOTEES_OF_ATLAS, DIONYSIA, DIONYSUS_minor_god, DISABLOT, DIVINE_BLOOD, DIVINE_BOOKS_MC, DIVINE_JUDGMENT_AY, DIVINE_LABOR, DIVINE_PREFECTURE, DIVINE_SLASH, DRAGON_TYPHOON, DRAUGR, DROUGHT_SHIPS, DRYAD, DWARVEN_ARMORY, DWARVEN_AUGER, DWARVEN_BREASTPLATE, DWARVEN_MINE, EARTH_MONSTER, EARTH_WALL_god_power, EARTHQUAKE, ECLIPSE, EIGHT_BANNERS, EINHERI, ELECTRUM_BULLETS_AY, EMPYRIAN_SPEED, ENCHANTED_HYMN, ENYOS_BOW_OF_HORROR_AR, ETERNAL_HAUNTING, EVENING_STAR, EYES_IN_THE_FOREST, FACE_OF_THE_GORGON, FAFNIR, FATED_ARROWS, FEAST_OF_SUSTENANCE, FEASTS_OF_RENOWN_HF, FEET_OF_THE_JACKAL, FEI_BEASTS, FENRIS_WOLF_BROOD, FIMBULWINTER, FIRE_GIANT, FLAMES_OF_TYPHON, FLAMING_BLOOD, FLAMING_WEAPONS, FLOOD_OF_THE_NILE, FLOWERY_WARS, FORCE_OF_THE_WEST_WIND, FOREST_FIRE, FOREST_PROTECTION, FORGE_OF_OLYMPUS, FORSETI_minor_god, FOUR_JARS, FRENZIED_DASH, FREYJA_minor_god, FREYRS_GIFT, FRONTLINE_HEROICS_CB, FROST, FROST_GIANT, FUJIN, FUNERAL_BARGE, FUNERAL_RITES_TC, FURY_OF_THE_FALLEN, GAIA_FOREST, GALES_FURY, GEMINI, GIFT_OF_BEASTS_GOD_BLESSING, GILDED_SHIELDS, GJALLARHORN, GOHEI_WANDS, GOLDEN_APPLES_TC, GOLDEN_KITE_AY, GONGGONG_minor_god, GOSHINBOKU_god_power, GOUMANG_minor_god, GRACIOUS_HOSPITALITY, GRANITE_BLOOD, GRANITE_MAW, GRASP_OF_RAN, GREAT_FLOOD, GREAT_HUNT, GREATEST_OF_FIFTY, GUARDIAN_OF_IO, GULLINBURSTI_god_power, HACHIMAN_minor_god, HALL_OF_THANES_GH, HALLOWED_WOODLANDS, HALO_OF_THE_SUN, HAMADRYAD, HAMASK, HAMMER_OF_THUNDER_DA, HAND_OF_TALOS, HANNYA_MASK_DJ, HEALING_SPRING_god_power, HEART_OF_THE_TITANS, HEAVENLY_BARRAGE, HEIMDALL_minor_god, HEKATE_minor_god, HEL_minor_god, HELIOS_minor_god, HEPHAESTUS_minor_god, HEPHAESTUS_REVENGE, HERA_minor_god, HERBAL_MEDICINE, HERMES_minor_god, HEROIC_RENEWAL_PE, HESPERIDES_TREE_god_power, HESTIA_minor_god, HIERACOSPHINX, HIPPOCAMPUS, HOOVES_OF_THE_WIND, HORNS_OF_CONSECRATION, HORUS_minor_god, HOUTU_minor_god, HUANGDI_minor_god, HUEHUECOYOTL, HUNDUN, HUNTERS_STRENGTH_AY, HUNTRESS_AXE, HYDRA, HYPERION_minor_god, IMPERIAL_ORDER, IMPLODE, INARI_OKAMI, INFERNO, INFESTATION, ITZPAPALOTL_minor_god, IVORY_NETSUKE, JOROGUMO, JOTUNS, KAGURA, KAMAITACHI, KATAGI_DJ, KUAFU_CHIEFTAIN, KUMIKI_CE, KUSANAGI, LABYRINTH_OF_MINOS, LAMPADES, LANCE_OF_STONE, LAST_STAND, LEATHER_FRAME_SHIELD_AY, LEIZUS_SILK_AY, LETO_minor_god, LIGHTNING_STORM, LIGHTNING_WEAPONS, LOCUST_SWARM, LONG_SERPENT, LORD_OF_HORSES, LULLABY, LURE_god_power, MAELSTROM, MAGUEY_CULTIVATION, MALINALXOCHITL_minor_god, MANTICORE, MAQUIZCOATL, MASTER_OF_WEAPONRY_AY, MECHANICAL_ARTISANS, MEDUSA, METEOR, METZLIAPAN, MICTECAH, MICTLANTECUHTLI_minor_god, MILITIA, MINAKATATOMI_minor_god, MINOTAUR, MIRROR_TOWER, MONSTROUS_RAGE, MOUNTAIN_GIANT, MOUNTAINOUS_MIGHT, MUMMY, MYTHIC_REJUVENATION, NAHUALLATOLLI, NEBTY_TC, NECKLACE_OF_EYEBALLS, NECROPOLIS, NEMEAN_LION, NEPHTHYS_minor_god, NEW_KINGDOM_TC, NEW_MOON, NIDHOGG, NINE_WAVES_HF, NJORD_minor_god, NUBA, OBSIDIAN_BUTTERFLY, OBSIDIAN_KNAPPING, OBSIDIAN_MIRROR, OCEANUS_minor_god, OCPATLI_INFUSIONS_CP, OCPATLI_INFUSIONS_WH, OCPATLI_INFUSIONS_NH, OKUNINUSHI, OLD_COYOTES_SPIRIT, OLYMPIAN_PARENTAGE_FT, OLYMPIAN_WEAPONS, OMEN_OF_DEATH, OMEN_OF_MALINALCO, OMETOCHTILS_REVELRY, ONI, ONI_MASK, ONMORAKI, ONMYODO, ORACLE_tech, ORICHALCUM_MAIL_AY, OSIRIS_tech, PAN_minor_god, PANS_PIONEERS, PATECATL_minor_god, PEACH_OF_IMMORTALITY, PERCEPTION, PERSEPHONE_minor_god, PESTILENCE, PETRIFICATION, PETSUCHOS, PHOBOS_SPEAR_OF_PANIC_AY, PHOENIX, PILLAR_OF_TLALOCAN, PIONEER_OF_THE_SKIES, PIOUS_SACRIFICE, PIXIU, PLAGUE_OF_SERPENTS, PLENTY, POSEIDONS_SECRET, POWER_OF_CHAOS, PRECIOUS_BONES_WH, CALL_OF_LYKAION, PROMETHEAN, PROMETHEAN_OFFSPRING, PROMETHEUS_tech, PROPHETIC_SIGHT, PROSPERITY, PROSPEROUS_SEEDS, PTAH_minor_god, PURGE, QILIN, QILINS_BLESSING, QINGLONG, QIONGQI, RAGE_OF_SLAUGHTER, RAGNAROK, RAIJIN_minor_god, RAIJU, RAIN, RAMPAGE, RAVEN, RED_CLIFFS_FLEET, REINCARNATION, RESTLESS_ARMY, RESTORATION, RHEIA_minor_god, RHEIAS_GIFT, RIGSTHULA, RIME, RING_GIVER, RING_OATH, RISING_TIDE, ROAR_OF_ORTHUS, ROC, ROCK_GIANT, ROCK_SOLID, RUSHOU_minor_god, SACRED_CATS, SACRED_GATE_god_power, SACRED_LAND, SAFEGUARD, SALTWATER_SPRING, SARISSA_AY, SASHIMONO_BANNERMEN, SATYR, SCALLOPED_AXE_AY, SCARAB, SCORCHING_FEATHERS_AY, SCORPION_MAN, SEASIDE_INFILTRATORS, SEKHMET_minor_god, SENTINEL, SERPENT_SKIRT, SERPENT_SPEAR, SERVANT, SERVANTS_OF_GLORY, SESSRUMNIR, SHADUF_GY, SHAFTS_OF_PLAGUE_AR, SHAKER_OF_HEAVEN, SHARDS_OF_ITZTLI, SHIFTING_SANDS, SHINIGAMI, SHOCKWAVE, SHOGUN, SHOULDER_OF_TALOS, SHRINE_OF_THE_HUNT_god_power, SILENT_RESOLVE, SINISTER_DEFIANCE, SIREN, SKADI_minor_god, SKIN_OF_THE_RHINO, SKY_PASSAGE, SLASH_AND_BURN, SLINGS_OF_THE_SUN_AY, SMITING_GUST, SOBEK_HATHOR, SOJUTSU, SOLAR_BARQUE, SOLAR_SHIELD, SON_OF_LOONG, SON_OF_OSIRIS, SONG_OF_MIDSUMMER, SONS_OF_SLEIPNIR, SONS_OF_THE_SUN, SOUL_GUIDE, SOUTHERN_FIRE, SPEAR_OF_HORUS, SPHINX, SPIDER_LAIR, SPIRIT_OF_MAAT_TC, SPIRITED_CHARGE, SPOILS_OF_WAR, SPY, STARFALL, STING_OF_YAPPAN, STONESKIN_QUINAMETZIN, STRING_OF_HEARTS, STYMPHALIAN_BIRD, SUMO_TRAINING_DJ, SUN_DRIED_MUD_BRICK, SUN_RAY_AR, SWAMPLAND, SWINE_ARRAY, SYLVAN_LORE, TAI_CHI, TAILWIND, TAKEMIKAZUCHI_minor_god, TAOTIE, TARTARIAN_GATE_god_power, TECCIZTECATLS_PENANCE, TEMPEST, TEMPESTUOUS_STORM, TEMPLE_OF_HEALING, TEMPORAL_CHAOS, TEN_FIST_SWORD, TENGU, TENSHU, TEPEYOLLOTLS_REACH, TEPONAZTLI_DRUMS, THE_PEACH_BLOSSOM_SPRING_god_power, THEFT_OF_FIRE, THEIA_minor_god, THORNED_WALLS, THOTH_minor_god, THRACIAN_HORSES, THUNDER_BURST, THUNDERING_HOOVES, THUNDEROUS_PRESENCE, THURISAZ_RUNE, TITAN_SHIELD, TITANOMACHY, TLALOC_minor_god, TLALOQUES, TOLOACHE_TRANCE_WH, TONACATEPETL, TORCH_OF_MISFORTUNE, TORNADO, TRAITOR, TROLL, TUNKULUCHU, TUSKS_OF_APEDEMAK, TWILIGHT_OF_THE_GODS_GH, TWISTED_LIMBS, TYR_minor_god, TZITZIMITL, ULLR_minor_god, UNDERMINE, UNDERWORLD_INVASION, UNDERWORLD_PASSAGE_god_power, VALGALDR, VALKYRIE, VALLEY_OF_THE_KINGS, VALOR, VANISH, VAULTS_OF_EREBUS, VIBRANT_LAND_HC, VIDAR_minor_god, VIKINGS, VISION, VOLCANIC_FORGE_AR, VOLCANO, VORTEX, WADJET, WALKING_WOODS, WANYUDO, WATATSUMI_minor_god, WAY_OF_THE_MOON_BUSHIDO, WAY_OF_THE_STORM_BUSHIDO, WAY_OF_THE_SUN_BUSHIDO, WEIGHTLESS_MACE_AY, WILL_OF_KRONOS, WIND_SICKLES, WINGED_MESSENGER, WINGS_OF_ITZPAPALOTL, WINGS_OF_THE_SOUTH, WINTER_HARVEST, WISDOM_OF_NINE, WITHER, WRATH_OF_THE_DEEP, XOLOTL_minor_god, XUANNU, XUANYUANS_BLOODLINE, YAZI, YDALIR, YIN_AND_YANG_GOD_BLESSING, YINGLONGS_WRATH, ZHUQUE, ZHURONG_minor_god, BURNT_WATER, MYRMIDON, SHADE_OF_HADES, GASTRAPHETOROS, HETAIROS, HARPY, IRON_GRIP, HYMN_OF_THE_WILDWOOD, GUIDING_FLAME, HARVEST_OF_SOULS_AY, AMAZON_ARCHER, BABOON_OF_SET, LYKAON_VILLAGER, } from "./units.js"

export const minorGodLaneMatrices = {

        huitzilopochtli : [
            [BLOOD_PACT, WINGS_OF_THE_SOUTH], // archaic_1  
            [BLANK], // archaic_2 
            [PATECATL_minor_god, AGAVE_BLOOM, CENTZON_TOTOCHTIN, OMETOCHTILS_REVELRY,OCPATLI_INFUSIONS_CP, MAGUEY_CULTIVATION], // classical_1 
            [MALINALXOCHITL_minor_god, INFESTATION, MAQUIZCOATL, OMEN_OF_MALINALCO, STING_OF_YAPPAN, TOLOACHE_TRANCE_WH], // classical_2
            [COATLICUE_minor_god, EARTH_MONSTER, AYOTOCHTLI, SERPENT_SKIRT, COATEPEC_SHRINES, STRING_OF_HEARTS, CIPACTLIS_SCALES], // heroic_1
            [ITZPAPALOTL_minor_god, PURGE, OBSIDIAN_BUTTERFLY, WINGS_OF_ITZPAPALOTL, OBSIDIAN_KNAPPING, FLOWERY_WARS, SHARDS_OF_ITZTLI], // heroic_2
            [TLALOC_minor_god, PILLAR_OF_TLALOCAN, AHUIZOTL, BURNT_WATER, TLALOQUES, TONACATEPETL, FOUR_JARS], // heroic_3
            [MICTLANTECUHTLI_minor_god, VOLCANO, TUNKULUCHU, NECKLACE_OF_EYEBALLS, OMEN_OF_DEATH, PRECIOUS_BONES_WH, MICTECAH], // mythic_1
            [], // mythic_2
    ],

    tezcatlipoca : [
            [OBSIDIAN_MIRROR, TEPEYOLLOTLS_REACH], // archaic_1  
            [BLANK], // archaic_2 
            [MALINALXOCHITL_minor_god, INFESTATION, MAQUIZCOATL, OMEN_OF_MALINALCO, STING_OF_YAPPAN, TOLOACHE_TRANCE_WH], // classical_1 
            [HUEHUECOYOTL, LULLABY, CHANEQUE, OLD_COYOTES_SPIRIT, CUICACALLI_TRAINING, TEPONAZTLI_DRUMS, NAHUALLATOLLI], // classical_2
            [COYOLXAUHQUI_minor_god, STARFALL, TZITZIMITL, CENTZON_HUITZNAHUA, COYOLXAUHQUIS_STONE, TECCIZTECATLS_PENANCE, METZLIAPAN], // heroic_1
            [ITZPAPALOTL_minor_god, PURGE, OBSIDIAN_BUTTERFLY, WINGS_OF_ITZPAPALOTL, OBSIDIAN_KNAPPING, FLOWERY_WARS, SHARDS_OF_ITZTLI], // heroic_2
            [XOLOTL_minor_god, CORRUPTED_GROUND, SOUL_GUIDE, TORCH_OF_MISFORTUNE, EVENING_STAR, TWISTED_LIMBS, STONESKIN_QUINAMETZIN], // heroic_3
            [MICTLANTECUHTLI_minor_god, VOLCANO, TUNKULUCHU, NECKLACE_OF_EYEBALLS, OMEN_OF_DEATH, PRECIOUS_BONES_WH, MICTECAH], // mythic_1
            [], // mythic_2
    ],

    quetzalcoatl : [
            [TAILWIND, FEAST_OF_SUSTENANCE], // archaic_1  
            [BLANK], // archaic_2 
            [PATECATL_minor_god, AGAVE_BLOOM, CENTZON_TOTOCHTIN, OMETOCHTILS_REVELRY,OCPATLI_INFUSIONS_CP, MAGUEY_CULTIVATION], // classical_1 
            [HUEHUECOYOTL, LULLABY, CHANEQUE, OLD_COYOTES_SPIRIT, CUICACALLI_TRAINING, TEPONAZTLI_DRUMS, NAHUALLATOLLI], // classical_2
            [COATLICUE_minor_god, EARTH_MONSTER, AYOTOCHTLI, SERPENT_SKIRT, COATEPEC_SHRINES, STRING_OF_HEARTS, CIPACTLIS_SCALES], // heroic_1
            [COYOLXAUHQUI_minor_god, STARFALL, TZITZIMITL, CENTZON_HUITZNAHUA, COYOLXAUHQUIS_STONE, TECCIZTECATLS_PENANCE, METZLIAPAN], // heroic_2
            [TLALOC_minor_god, PILLAR_OF_TLALOCAN, AHUIZOTL, BURNT_WATER, TLALOQUES, TONACATEPETL, FOUR_JARS], // heroic_3
            [XOLOTL_minor_god, CORRUPTED_GROUND, SOUL_GUIDE, TORCH_OF_MISFORTUNE, EVENING_STAR, TWISTED_LIMBS, STONESKIN_QUINAMETZIN], // mythic_1
            [], // mythic_2
    ],

    amaterasu : [
            [SOLAR_SHIELD, WAY_OF_THE_SUN_BUSHIDO, KAGURA], // archaic_1  
            [BLANK], // archaic_2 
            [AME_NO_UZUME_minor_god, GOSHINBOKU_god_power, KAMAITACHI, WIND_SICKLES, KATAGI_DJ, GOHEI_WANDS], // classical_1 
            [MINAKATATOMI_minor_god, SHRINE_OF_THE_HUNT_god_power, WANYUDO, CONDEMNED_SOUL, SALTWATER_SPRING, HUNTERS_STRENGTH_AY, KUMIKI_CE], // classical_2
            [HACHIMAN_minor_god, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE_AY, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
            [RAIJIN_minor_god, THUNDER_BURST, RAIJU, THUNDEROUS_PRESENCE, DEN_DEN_DRUMS, HANNYA_MASK_DJ, HEAVENLY_BARRAGE], // heroic_2
            [TAKEMIKAZUCHI_minor_god, DIVINE_SLASH, ASURA, BURNING_MALEVOLENCE, SUMO_TRAINING_DJ, TEN_FIST_SWORD, SOJUTSU], // heroic_3
            [OKUNINUSHI, SACRED_GATE_god_power, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
            [], // mythic_2
    ],

    tsukuyomi : [
            [NEW_MOON, WAY_OF_THE_MOON_BUSHIDO, TENSHU], // archaic_1  
            [BLANK], // archaic_2 
            [AME_NO_UZUME_minor_god, GOSHINBOKU_god_power, KAMAITACHI, WIND_SICKLES, KATAGI_DJ, GOHEI_WANDS], // classical_1
            [INARI_OKAMI, SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
            [HACHIMAN_minor_god, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE_AY, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
            [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_2
            [WATATSUMI_minor_god, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO, ASYMMETRICAL_BOWS], // heroic_3
            [OKUNINUSHI, SACRED_GATE_god_power, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
            [], // mythic_2
    ],

    susanoo : [
            [KUSANAGI, WAY_OF_THE_STORM_BUSHIDO, CRUSHING_WAVES], // archaic_1
            [BLANK], // archaic_2 
            [MINAKATATOMI_minor_god, SHRINE_OF_THE_HUNT_god_power, WANYUDO, CONDEMNED_SOUL, SALTWATER_SPRING, HUNTERS_STRENGTH_AY, KUMIKI_CE], // classical_1
            [INARI_OKAMI, SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
            [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_1
            [RAIJIN_minor_god, THUNDER_BURST, RAIJU, THUNDEROUS_PRESENCE, DEN_DEN_DRUMS, HANNYA_MASK_DJ, HEAVENLY_BARRAGE], // heroic_2
            [TAKEMIKAZUCHI_minor_god, DIVINE_SLASH, ASURA, BURNING_MALEVOLENCE, SUMO_TRAINING_DJ, TEN_FIST_SWORD, SOJUTSU], // heroic_3
            [WATATSUMI_minor_god, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO, ASYMMETRICAL_BOWS], // mythic_1
            [], // mythic_2
    ],

    fuxi : [
            [THE_PEACH_BLOSSOM_SPRING_god_power, YIN_AND_YANG_GOD_BLESSING, CELESTIAL_WEAPONS, TAI_CHI], 
            [BLANK], // archaic_2 
            [XUANNU, VANISH, QILIN, DIVINE_BOOKS_MC, REINCARNATION, QILINS_BLESSING], // classical_1
            [CHIYOU_minor_god, LIGHTNING_WEAPONS, YAZI, MASTER_OF_WEAPONRY_AY, SPOILS_OF_WAR, SON_OF_LOONG, RAGE_OF_SLAUGHTER], // classical_2
            [GOUMANG_minor_god, FOREST_PROTECTION, VIBRANT_LAND_HC, HOOVES_OF_THE_WIND, FRENZIED_DASH, MAELSTROM], // heroic_1
            [NUBA, DROUGHT_SHIPS,TAOTIE, SCORCHING_FEATHERS_AY, ROCK_SOLID, BOTTOMLESS_STOMACH, DROUGHT_SHIPS], // heroic_2
            [GONGGONG_minor_god, GREAT_FLOOD, QINGLONG, SHAKER_OF_HEAVEN, TEMPESTUOUS_STORM, LAST_STAND, RISING_TIDE], // heroic_3
            [HUANGDI_minor_god, YINGLONGS_WRATH, HUNDUN, XUANYUANS_BLOODLINE, LEIZUS_SILK_AY, IMPERIAL_ORDER, POWER_OF_CHAOS], // mythic_1
            [], // mythic_2
    ],

    nuwa : [
            [CREATION, CREATORS_AUSPICE_GOD_BLESSING, KUAFU_CHIEFTAIN, MOUNTAINOUS_MIGHT],
            [BLANK], // archaic_2 
            [XUANNU, VANISH, QILIN, DIVINE_BOOKS_MC, REINCARNATION, QILINS_BLESSING], // classical_1
            [HOUTU_minor_god, EARTH_WALL_god_power, QIONGQI, ADVANCED_DEFENSES_ST, CHASING_THE_SUN, ABUNDANCE, SINISTER_DEFIANCE], // classical_2
            [GOUMANG_minor_god, FOREST_PROTECTION, VIBRANT_LAND_HC, HOOVES_OF_THE_WIND, FRENZIED_DASH, MAELSTROM], // heroic_1
            [RUSHOU_minor_god, FEI_BEASTS, BAIHU, PIXIU, GILDED_SHIELDS, DIVINE_JUDGMENT_AY, AUTUMN_OF_ABUNDANCE, RED_CLIFFS_FLEET], // heroic_2
            [GONGGONG_minor_god, GREAT_FLOOD, QINGLONG, SHAKER_OF_HEAVEN, TEMPESTUOUS_STORM, LAST_STAND, RISING_TIDE], // heroic_3
            [ZHURONG_minor_god, BLAZING_PRAIRIE, ZHUQUE, FLAMING_BLOOD, SLASH_AND_BURN, SONG_OF_MIDSUMMER, SOUTHERN_FIRE], // mythic_1
            [], // mythic_2
    ],

    shennong : [
            [PROSPEROUS_SEEDS, GIFT_OF_BEASTS_GOD_BLESSING, HERBAL_MEDICINE, PEACH_OF_IMMORTALITY],
            [BLANK], // archaic_2 
            [HOUTU_minor_god, EARTH_WALL_god_power, QIONGQI, ADVANCED_DEFENSES_ST, CHASING_THE_SUN, ABUNDANCE, SINISTER_DEFIANCE], // classical_1
            [CHIYOU_minor_god, LIGHTNING_WEAPONS, YAZI, MASTER_OF_WEAPONRY_AY, SPOILS_OF_WAR, SON_OF_LOONG, RAGE_OF_SLAUGHTER], // classical_2
            [RUSHOU_minor_god, FEI_BEASTS, BAIHU, PIXIU, GILDED_SHIELDS, DIVINE_JUDGMENT_AY, AUTUMN_OF_ABUNDANCE, RED_CLIFFS_FLEET], // heroic_1
            [NUBA, DECONSTRUCTION,TAOTIE, SCORCHING_FEATHERS_AY, ROCK_SOLID, BOTTOMLESS_STOMACH, DROUGHT_SHIPS], // heroic_2
            [ZHURONG_minor_god, BLAZING_PRAIRIE, ZHUQUE, FLAMING_BLOOD, SLASH_AND_BURN, SONG_OF_MIDSUMMER, SOUTHERN_FIRE], // heroic_3
            [HUANGDI_minor_god, YINGLONGS_WRATH, HUNDUN, XUANYUANS_BLOODLINE, LEIZUS_SILK_AY, IMPERIAL_ORDER, POWER_OF_CHAOS], // mythic_1
            [], // mythic_2
    ],

    zeus : [
            [BOLT, MYRMIDON, OLYMPIAN_PARENTAGE_FT], // archaic_1
            [BLANK], // archaic_2
            [ATHENA_minor_god, RESTORATION, MINOTAUR, LABYRINTH_OF_MINOS, AEGIS_SHIELD_AY, SARISSA_AY], // classical_1
            [HERMES_minor_god, CEASEFIRE, CENTAUR, SYLVAN_LORE, SPIRITED_CHARGE, WINGED_MESSENGER], // classical_2
            [APOLLO_minor_god, UNDERWORLD_PASSAGE_god_power, MANTICORE, ORACLE_tech, TEMPLE_OF_HEALING, SUN_RAY_AR, ANASTROPHE], // heroic_1
            [DIONYSUS_minor_god, BRONZE, HYDRA, CHTHONIC_RITES_DK, DIONYSIA, THRACIAN_HORSES], // heroic_2
            [HEPHAESTUS_minor_god, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
            [HERA_minor_god, LIGHTNING_STORM, MEDUSA, ARGIVE_PATRONAGE_ZEUS, FACE_OF_THE_GORGON, MONSTROUS_RAGE], // mythic_1
            [], // mythic_2
    ],

    hades : [
            [SENTINEL,SHADE_OF_HADES, GASTRAPHETOROS, VAULTS_OF_EREBUS], // archaic_1 // need to change SENTINEL to type = tech, bolt is placeholder to prevent error
            [BLANK], // archaic_2
            [ATHENA_minor_god, RESTORATION, MINOTAUR, LABYRINTH_OF_MINOS, AEGIS_SHIELD_AY, SARISSA_AY], // classical_1
            [ARES_minor_god, PESTILENCE, CYCLOPS, PHOBOS_SPEAR_OF_PANIC_AY, WILL_OF_KRONOS, ENYOS_BOW_OF_HORROR_AR, DEIMOS_SWORD_OF_DREAD_AY], // classical_2
            [APOLLO_minor_god, UNDERWORLD_PASSAGE_god_power, MANTICORE, ORACLE_tech, TEMPLE_OF_HEALING, SUN_RAY_AR, ANASTROPHE], // heroic_1
            [APHRODITE_minor_god, CURSE, NEMEAN_LION, GOLDEN_APPLES_TC, DIVINE_BLOOD, ROAR_OF_ORTHUS, ARGONAUTS], // heroic_2
            [HEPHAESTUS_minor_god, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
            [ARTEMIS_minor_god, EARTHQUAKE, CHIMERA, FLAMES_OF_TYPHON, SHAFTS_OF_PLAGUE_AR, BEAST_SLAYER], // mythic_1
            [], // mythic_2
    ],

    poseidon : [
            [LURE_god_power, HIPPOCAMPUS, MILITIA, HETAIROS, LORD_OF_HORSES], // archaic_1
            [BLANK], // archaic_2
            [ARES_minor_god, PESTILENCE, CYCLOPS, PHOBOS_SPEAR_OF_PANIC_AY, WILL_OF_KRONOS, ENYOS_BOW_OF_HORROR_AR, DEIMOS_SWORD_OF_DREAD_AY], // classical_1
            [HERMES_minor_god, CEASEFIRE, CENTAUR, SYLVAN_LORE, SPIRITED_CHARGE, WINGED_MESSENGER], // classical_2
            [APHRODITE_minor_god, CURSE, NEMEAN_LION, GOLDEN_APPLES_TC, DIVINE_BLOOD, ROAR_OF_ORTHUS, ARGONAUTS], // heroic_1
            [DIONYSUS_minor_god, BRONZE, HYDRA, CHTHONIC_RITES_DK, DIONYSIA, THRACIAN_HORSES], // heroic_2
            [HEPHAESTUS_minor_god, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
            [ARTEMIS_minor_god, EARTHQUAKE, CHIMERA, FLAMES_OF_TYPHON, SHAFTS_OF_PLAGUE_AR, BEAST_SLAYER], // mythic_1
            [], // mythic_2
    ],

    demeter : [
            [WITHER, HARPY, AMAZON_ARCHER, DIVINE_LABOR, IRON_GRIP], // archaic_1
            [BLANK], // archaic_2
            [ARES_minor_god, PESTILENCE, CYCLOPS, PHOBOS_SPEAR_OF_PANIC_AY, WILL_OF_KRONOS, ENYOS_BOW_OF_HORROR_AR, DEIMOS_SWORD_OF_DREAD_AY], // classical_1
            [PAN_minor_god, ARCADIAN_MEADOW, LYKAON_VILLAGER, THORNED_WALLS, PANS_PIONEERS, CALL_OF_LYKAION, HYMN_OF_THE_WILDWOOD], // classical_2
            [APHRODITE_minor_god, CURSE, NEMEAN_LION, GOLDEN_APPLES_TC, DIVINE_BLOOD, ROAR_OF_ORTHUS, ARGONAUTS], // heroic_1
            [HESTIA_minor_god, COMMUNAL_HEARTH_god_power, HAMADRYAD, GRACIOUS_HOSPITALITY, HALLOWED_WOODLANDS, FATED_ARROWS, GUIDING_FLAME], // heroic_2
            [HERA_minor_god, LIGHTNING_STORM, MEDUSA, ARGIVE_PATRONAGE_DEMETER, FACE_OF_THE_GORGON, MONSTROUS_RAGE], // heroic_3
            [PERSEPHONE_minor_god, UNDERWORLD_INVASION, SIREN, SACRED_LAND, ENCHANTED_HYMN, PIOUS_SACRIFICE, HARVEST_OF_SOULS_AY], // mythic_1
            [], // mythic_2
    ],

    ra:[
            [RAIN, SKIN_OF_THE_RHINO], // archaic_1
            [BLANK], // archaic_2
            [BAST_minor_god, ECLIPSE, SPHINX, SACRED_CATS, ADZE_OF_WEPWAWET, CRIOSPHINX, HIERACOSPHINX], // classical_1
            [PTAH_minor_god, SHIFTING_SANDS, WADJET, SCALLOPED_AXE_AY, LEATHER_FRAME_SHIELD_AY, ELECTRUM_BULLETS_AY, SHADUF_GY], // classical_2
            [SOBEK_HATHOR, LOCUST_SWARM, ROC, PETSUCHOS, CROCODILOPOLIS, SUN_DRIED_MUD_BRICK, DARK_WATER_ME, SOLAR_BARQUE], // heroic_1
            [SEKHMET_minor_god, CITADEL, SCARAB, BONE_BOW_AY, SLINGS_OF_THE_SUN_AY, CRIMSON_LINEN_DK, FORCE_OF_THE_WEST_WIND], // heroic_2
            [OSIRIS_tech, SON_OF_OSIRIS, MUMMY, DESERT_WIND, NEW_KINGDOM_TC, ATEF_CROWN], // heroic_3
            [HORUS_minor_god, TORNADO, AVENGER, AXE_OF_VENGEANCE, SPEAR_OF_HORUS, GREATEST_OF_FIFTY], // mythic_1
            [], // mythic_2
    ],

    isis:[
            [PROSPERITY, FLOOD_OF_THE_NILE], // archaic_1
            [BLANK], // archaic_2
            [BAST_minor_god, ECLIPSE, SPHINX, SACRED_CATS, ADZE_OF_WEPWAWET, CRIOSPHINX, HIERACOSPHINX], // classical_1
            [ANUBIS_minor_god, PLAGUE_OF_SERPENTS, ANUBITE, FEET_OF_THE_JACKAL, SERPENT_SPEAR, NECROPOLIS], // classical_2
            [SOBEK_HATHOR, LOCUST_SWARM, ROC, PETSUCHOS, CROCODILOPOLIS, SUN_DRIED_MUD_BRICK, DARK_WATER_ME, SOLAR_BARQUE], // heroic_1
            [NEPHTHYS_minor_god, ANCESTORS, SCORPION_MAN, FUNERAL_RITES_TC, SPIRIT_OF_MAAT_TC, NEBTY_TC, FUNERAL_BARGE], // heroic_2
            [OSIRIS_tech, SON_OF_OSIRIS, MUMMY, DESERT_WIND, NEW_KINGDOM_TC, ATEF_CROWN], // heroic_3
            [THOTH_minor_god, METEOR, PHOENIX, VALLEY_OF_THE_KINGS, BOOK_OF_THOTH, TUSKS_OF_APEDEMAK], // mythic_1
            [], // mythic_2
    ],

    set:[
            [VISION, BABOON_OF_SET, CLAIRVOYANCE], // archaic_1 
            [BLANK], // archaic_2
            [ANUBIS_minor_god, PLAGUE_OF_SERPENTS, ANUBITE, FEET_OF_THE_JACKAL, SERPENT_SPEAR, NECROPOLIS], // classical_1
            [PTAH_minor_god, SHIFTING_SANDS, WADJET, SCALLOPED_AXE_AY, LEATHER_FRAME_SHIELD_AY, ELECTRUM_BULLETS_AY, SHADUF_GY], // classical_2
            [SEKHMET_minor_god, CITADEL, SCARAB, BONE_BOW_AY, SLINGS_OF_THE_SUN_AY, CRIMSON_LINEN_DK, FORCE_OF_THE_WEST_WIND], // heroic_1
            [NEPHTHYS_minor_god, ANCESTORS, SCORPION_MAN, FUNERAL_RITES_TC, SPIRIT_OF_MAAT_TC, NEBTY_TC, FUNERAL_BARGE], // heroic_2
            [THOTH_minor_god, METEOR, PHOENIX, VALLEY_OF_THE_KINGS, BOOK_OF_THOTH, TUSKS_OF_APEDEMAK], // heroic_3
            [HORUS_minor_god, TORNADO, AVENGER, AXE_OF_VENGEANCE, SPEAR_OF_HORUS, GREATEST_OF_FIFTY], // mythic_1
            [], // mythic_2
    ],

    thor: [
            [DWARVEN_MINE, DWARVEN_ARMORY, HAMMER_OF_THUNDER_DA], // archaic_1 //DWARVEN_MINE is type=tech need to change to god power
            [BLANK], // archaic_2
            [FREYJA_minor_god, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
            [FORSETI_minor_god, HEALING_SPRING_god_power, TROLL, HALL_OF_THANES_GH, DWARVEN_BREASTPLATE, CAVE_TROLL], // classical_2
            [SKADI_minor_god, FROST, FROST_GIANT, RIME, HUNTRESS_AXE, WINTER_HARVEST, ARCTIC_WINDS], // heroic_1
            [BRAGI_minor_god, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_2
            [BALDR_minor_god, RAGNAROK, FIRE_GIANT, SONS_OF_SLEIPNIR, DWARVEN_AUGER], // heroic_3
            [TYR_minor_god, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
            [], // mythic_2
    ],

    odin: [
        [GREAT_HUNT, RAVEN, HAMASK], // archaic_1
        [BLANK], // archaic_2
        [FREYJA_minor_god, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
        [HEIMDALL_minor_god, UNDERMINE, EINHERI, GJALLARHORN, SAFEGUARD, RIGSTHULA], // classical_2
        [SKADI_minor_god, FROST, FROST_GIANT, RIME, HUNTRESS_AXE, WINTER_HARVEST, ARCTIC_WINDS], // heroic_1
        [NJORD_minor_god, WALKING_WOODS, MOUNTAIN_GIANT, RING_GIVER, VIKINGS, JOTUNS, WRATH_OF_THE_DEEP], // heroic_2
        [BALDR_minor_god, RAGNAROK, FIRE_GIANT, SONS_OF_SLEIPNIR, DWARVEN_AUGER], // heroic_3
        [TYR_minor_god, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
        [], // mythic_2
    ],

    loki: [
            [SPY, EYES_IN_THE_FOREST], // archaic_1
            [BLANK], // archaic_2
            [FORSETI_minor_god, HEALING_SPRING_god_power, TROLL, HALL_OF_THANES_GH, DWARVEN_BREASTPLATE, CAVE_TROLL], // classical_1
            [HEIMDALL_minor_god, UNDERMINE, EINHERI, GJALLARHORN, SAFEGUARD, RIGSTHULA], // classical_2
            [BRAGI_minor_god, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_1
            [NJORD_minor_god, WALKING_WOODS, MOUNTAIN_GIANT, RING_GIVER, VIKINGS, JOTUNS, WRATH_OF_THE_DEEP], // heroic_2
            [HEL_minor_god, NIDHOGG, FIRE_GIANT, FROST_GIANT, MOUNTAIN_GIANT, RAMPAGE, GRANITE_BLOOD], // heroic_3
            [TYR_minor_god, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
            [], // mythic_2
    ],
     
    freyr : [
            [GULLINBURSTI_god_power, FREYRS_GIFT], // archaic_1
            [BLANK], // archaic_2
            [FREYJA_minor_god, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
            [ULLR_minor_god, ASGARDIAN_BASTION, DRAUGR, VALGALDR, SERVANTS_OF_GLORY, RING_OATH, YDALIR], // classical_2
            [BRAGI_minor_god, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_1
            [AEGIR_minor_god, TEMPEST, ROCK_GIANT, GRANITE_MAW, FEASTS_OF_RENOWN_HF, NINE_WAVES_HF, GRASP_OF_RAN], // heroic_2
            [HEL_minor_god, NIDHOGG, FIRE_GIANT, FROST_GIANT, MOUNTAIN_GIANT, RAMPAGE, GRANITE_BLOOD], // heroic_3
            [VIDAR_minor_god, INFERNO, FAFNIR, TWILIGHT_OF_THE_GODS_GH, AVENGING_SPIRIT, SILENT_RESOLVE, FURY_OF_THE_FALLEN], // mythic_1
            [], // mythic_2
    ],

    kronos: [
            [DECONSTRUCTION, TEMPORAL_CHAOS], // archaic_1
            [BLANK], // archaic_2
            [PROMETHEUS_tech, VALOR, PROMETHEAN, ALLUVIAL_CLAY, HEART_OF_THE_TITANS, THEFT_OF_FIRE], // classical_1
            [LETO_minor_god, SPIDER_LAIR, AUTOMATON, HEPHAESTUS_REVENGE, VOLCANIC_FORGE_AR, PERCEPTION], // classical_2
            [HYPERION_minor_god, CHAOS, SATYR, GEMINI, HEROIC_RENEWAL_PE, SONS_OF_THE_SUN, PIONEER_OF_THE_SKIES], // heroic_1
            [RHEIA_minor_god, TRAITOR, BEHEMOTH, HORNS_OF_CONSECRATION, ORICHALCUM_MAIL_AY, RHEIAS_GIFT, DAKTYLOI], // heroic_2
            [HELIOS_minor_god, VORTEX, CENTIMANUS, MIRROR_TOWER, HALO_OF_THE_SUN, PETRIFICATION, TITANOMACHY], // heroic_3
            [ATLAS_minor_god, IMPLODE, ARGUS, GUARDIAN_OF_IO, DEVOTEES_OF_ATLAS, TITAN_SHIELD], // mythic_1
            [], // mythic_2
    ],

    oranos : [
            [SHOCKWAVE, SKY_PASSAGE, EMPYRIAN_SPEED], // archaic_1
            [BLANK], // archaic_2
            [PROMETHEUS_tech, VALOR, PROMETHEAN, ALLUVIAL_CLAY, HEART_OF_THE_TITANS, THEFT_OF_FIRE], // classical_1
            [OCEANUS_minor_god, CARNIVORA, CALADRIA, SERVANT, BITE_OF_THE_SHARK_AY, WEIGHTLESS_MACE_AY, FRONTLINE_HEROICS_CB], // classical_2
            [HYPERION_minor_god, CHAOS, SATYR, GEMINI, HEROIC_RENEWAL_PE, SONS_OF_THE_SUN, PIONEER_OF_THE_SKIES], // heroic_1
            [THEIA_minor_god, HESPERIDES_TREE_god_power, STYMPHALIAN_BIRD, DRYAD, PROPHETIC_SIGHT, POSEIDONS_SECRET, LANCE_OF_STONE, DAUGHTERS_OF_THE_SEA], // heroic_2
            [HELIOS_minor_god, VORTEX, CENTIMANUS, MIRROR_TOWER, HALO_OF_THE_SUN, PETRIFICATION, TITANOMACHY], // heroic_3
            [HEKATE_minor_god, TARTARIAN_GATE_god_power, LAMPADES, ASPER_BLOOD, MYTHIC_REJUVENATION, CELERITY], // mythic_1
            [], // mythic_2
    ],

    gaia : [
            [GAIA_FOREST, CHANNELS], // archaic_1
            [BLANK], // archaic_2
            [OCEANUS_minor_god, CARNIVORA, CALADRIA, SERVANT, BITE_OF_THE_SHARK_AY, WEIGHTLESS_MACE_AY, FRONTLINE_HEROICS_CB], // classical_1
            [LETO_minor_god, SPIDER_LAIR, AUTOMATON, HEPHAESTUS_REVENGE, VOLCANIC_FORGE_AR, PERCEPTION], // classical_2
            [THEIA_minor_god, HESPERIDES_TREE_god_power, STYMPHALIAN_BIRD, DRYAD, PROPHETIC_SIGHT, POSEIDONS_SECRET, LANCE_OF_STONE, DAUGHTERS_OF_THE_SEA], // heroic_1
            [RHEIA_minor_god, TRAITOR, BEHEMOTH, HORNS_OF_CONSECRATION, ORICHALCUM_MAIL_AY, RHEIAS_GIFT, DAKTYLOI], // heroic_2
            [HEKATE_minor_god, TARTARIAN_GATE_god_power, LAMPADES, ASPER_BLOOD, MYTHIC_REJUVENATION, CELERITY], // heroic_3
            [ATLAS_minor_god, IMPLODE, ARGUS, GUARDIAN_OF_IO, DEVOTEES_OF_ATLAS, TITAN_SHIELD], // mythic_1
            [], // mythic_2
    ],

}



    

    
    

    


    
    
 