import { ABUNDANCE, ADVANCED_DEFENSES, ADZE_OF_WEPWAWET, AEGIR, AEGIS_SHIELD, ALLUVIAL_CLAY, AME_NO_UZUME, ANASTROPHE, ANCESTORS, ANUBIS, ANUBITE, APHRODITE, APOLLO, ARCTIC_WINDS, ARES, ARGIVE_PATRONAGE, ARGONAUTS, ARGUS, ARTEMIS, ASCETIC_PRACTICES, ASGARDIAN_BASTION, ASPER_BLOOD, ASURA, ASYMMETRICAL_BOWS, ATEF_CROWN, ATHENA, ATLAS, AUTOMATON, AUTUMN_OF_ABUNDANCE, AVENGER, AVENGING_SPIRIT, AXE_OF_VENGEANCE, BAIHU, BALDR, BAST, BATTLE_BOAR, BEAST_SLAYER, BEHEMOTH, BERSERKERGANG, BITE_OF_THE_SHARK, BLAZING_PRAIRIE, BOLT, BONE_BOW, BOOK_OF_THOTH, BOTTOMLESS_STOMACH, BRAGI, BRAVERY, BRONZE, BURNING_MALEVOLENCE, CALADRIA, CALL_OF_VALHALLA, CARNIVORA, CAVE_TROLL, CEASEFIRE, CELERITY, CELESTIAL_WEAPONS, CENTAUR, CENTIMANUS, CHANNELS, CHAOS, CHASING_THE_SUN, CHIMERA, CHIYOU, CHTHONIC_RITES, CITADEL, CLAIRVOYANCE, COLOSSUS, CONDEMNED_SOUL, CREATION, CREATORS_AUSPICE_GOD_BLESSING, CRIMSON_LINEN, CRIOSPHINX, CROCODILOPOLIS, CRUSHING_WAVES, CURSE, CYCLOPS, DAKTYLOI, DAN_NO_URA_TACTICS, DARK_WATER, DAUGHTERS_OF_THE_SEA, DEADLY_RAGE, DEADLY_SNARE, DECONSTRUCTION, DEIMOS_SWORD_OF_DREAD, DEN_DEN_DRUMS, DESERT_WIND, DEVOTEES_OF_ATLAS, DIONYSIA, DIONYSUS, DISABLOT, DIVINE_BLOOD, DIVINE_BOOKS, DIVINE_JUDGMENT, DIVINE_PREFECTURE, DIVINE_SLASH, DRAGON_TYPHOON, DRAUGR, DROUGHT_SHIPS, DRYAD, DWARVEN_ARMORY, DWARVEN_AUGER, DWARVEN_BREASTPLATE, DWARVEN_MINE, EARTH_WALL, EARTHQUAKE, ECLIPSE, EIGHT_BANNERS, EINHERI, ELECTRUM_BULLETS, EMPYRIAN_SPEED, ENYOS_BOW_OF_HORROR, ETERNAL_HAUNTING, EYES_IN_THE_FOREST, FACE_OF_THE_GORGON, FAFNIR, FEASTS_OF_RENOWN, FEET_OF_THE_JACKAL, FEI_BEASTS, FENRIS_WOLF_BROOD, FIMBULWINTER, FIRE_GIANT, FLAMES_OF_TYPHON, FLAMING_BLOOD, FLAMING_WEAPONS, FLOOD_OF_THE_NILE, FORCE_OF_THE_WEST_WIND, FOREST_FIRE, FOREST_PROTECTION, FORGE_OF_OLYMPUS, FORSETI, FRENZIED_DASH, FREYJA, FREYRS_GIFT, FRONTLINE_HEROICS, FROST, FROST_GIANT, FUJIN, FUNERAL_BARGE, FUNERAL_RITES, FURY_OF_THE_FALLEN, GAIA_FOREST, GALES_FURY, GEMINI, GIFT_OF_BEASTS_GOD_BLESSING, GILDED_SHIELDS, GJALLARHORN, GOHEI_WANDS, GOLDEN_APPLES, GOLDEN_KITE, GONGGONG, GOSHINBOKU, GOUMANG, GRANITE_BLOOD, GRANITE_MAW, GRASP_OF_RAN, GREAT_FLOOD, GREAT_HUNT, GREATEST_OF_FIFTY, GUARDIAN_OF_IO, GULLINBURSTI, HACHIMAN, HALL_OF_THANES, HALO_OF_THE_SUN, HAMASK, HAMMER_OF_THUNDER, HAND_OF_TALOS, HANNYA_MASK, HEALING_SPRING, HEART_OF_THE_TITANS, HEAVENLY_BARRAGE, HEIMDALL, HEKATE, HEL, HELIOS, HEPHAESTUS, HEPHAESTUS_REVENGE, HERA, HERBAL_MEDICINE, HERMES, HEROIC_RENEWAL, HESPERIDES_TREE, HIERACOSPHINX, HIPPOCAMPUS, HOOVES_OF_THE_WIND, HORNS_OF_CONSECRATION, HORUS, HOUTU, HUANGDI, HUNDUN, HUNTERS_STRENGTH, HUNTRESS_AXE, HYDRA, HYPERION, IMPERIAL_ORDER, IMPLODE, INARI_OKAMI, INFERNO, IVORY_NETSUKE, JOROGUMO, JOTUNS, KAGURA, KAMAITACHI, KATAGI, KUAFU_CHIEFTAIN, KUMIKI, KUSANAGI, LABYRINTH_OF_MINOS, LAMPADES, LANCE_OF_STONE, LAST_STAND, LEATHER_FRAME_SHIELD, LEIZUS_SILK, LETO, LIGHTNING_STORM, LIGHTNING_WEAPONS, LOCUST_SWARM, LONG_SERPENT, LORD_OF_HORSES, LURE, MAELSTROM, MANTICORE, MASTER_OF_WEAPONRY, MECHANICAL_ARTISANS, MEDUSA, METEOR, MILITIA, MINAKATATOMI, MINOTAUR, MIRROR_TOWER, MONSTROUS_RAGE, MOUNTAIN_GIANT, MOUNTAINOUS_MIGHT, MUMMY, MYTHIC_REJUVENATION, NEBTY, NECROPOLIS, NEMEAN_LION, NEPHTHYS, NEW_KINGDOM, NEW_MOON, NIDHOGG, NINE_WAVES, NJORD, NUBA, OCEANUS, OKUNINUSHI, OLYMPIAN_PARENTAGE, OLYMPIAN_WEAPONS, ONI, ONI_MASK, ONMORAKI, ONMYODO, ORACLE, ORICHALCUM_MAIL, OSIRIS, PEACH_OF_IMMORTALITY, PERCEPTION, PESTILENCE, PETRIFICATION, PETSUCHOS, PHOBOS_SPEAR_OF_PANIC, PHOENIX, PIONEER_OF_THE_SKIES, PIXIU, PLAGUE_OF_SERPENTS, PLENTY, POSEIDONS_SECRET, POWER_OF_CHAOS, PROMETHEAN, PROMETHEUS, PROPHETIC_SIGHT, PROSPERITY, PROSPEROUS_SEEDS, PTAH, QILIN, QILINS_BLESSING, QINGLONG, QIONGQI, RAGE_OF_SLAUGHTER, RAGNAROK, RAIJIN, RAIJU, RAIN, RAMPAGE, RAVEN, RED_CLIFFS_FLEET, REINCARNATION, RESTLESS_ARMY, RESTORATION, RHEIA, RHEIAS_GIFT, RIGSTHULA, RIME, RING_GIVER, RING_OATH, RISING_TIDE, ROAR_OF_ORTHUS, ROC, ROCK_GIANT, ROCK_SOLID, RUSHOU, SACRED_CATS, SACRED_GATE, SAFEGUARD, SALTWATER_SPRING, SARISSA, SASHIMONO_BANNERMEN, SATYR, SCALLOPED_AXE, SCARAB, SCORCHING_FEATHERS, SCORPION_MAN, SEASIDE_INFILTRATORS, SEKHMET, SENTINEL, SERPENT_SPEAR, SERVANT, SERVANTS_OF_GLORY, SESSRUMNIR, SHADUF, SHAFTS_OF_PLAGUE, SHAKER_OF_HEAVEN, SHIFTING_SANDS, SHINIGAMI, SHOCKWAVE, SHOGUN, SHOULDER_OF_TALOS, SHRINE_OF_THE_HUNT, SILENT_RESOLVE, SINISTER_DEFIANCE, SKADI, SKIN_OF_THE_RHINO, SKY_PASSAGE, SLASH_AND_BURN, SLINGS_OF_THE_SUN, SMITING_GUST, SOBEK_HATHOR, SOJUTSU, SOLAR_BARQUE, SOLAR_SHIELD, SON_OF_LOONG, SON_OF_OSIRIS, SONG_OF_MIDSUMMER, SONS_OF_SLEIPNIR, SONS_OF_THE_SUN, SOUTHERN_FIRE, SPEAR_OF_HORUS, SPHINX, SPIDER_LAIR, SPIRIT_OF_MAAT, SPIRITED_CHARGE, SPOILS_OF_WAR, SPY, STYMPHALIAN_BIRD, SUMO_TRAINING, SUN_DRIED_MUD_BRICK, SUN_RAY, SWAMPLAND, SWINE_ARRAY, SYLVAN_LORE, TAI_CHI, TAKEMIKAZUCHI, TAOTIE, TARTARIAN_GATE, TEMPEST, TEMPESTUOUS_STORM, TEMPLE_OF_HEALING, TEMPORAL_CHAOS, TEN_FIST_SWORD, TENGU, TENSHU, THE_PEACH_BLOSSOM_SPRING, THEFT_OF_FIRE, THEIA, THOTH, THRACIAN_HORSES, THUNDER_BURST, THUNDERING_HOOVES, THUNDEROUS_PRESENCE, THURISAZ_RUNE, TITAN_SHIELD, TITANOMACHY, TORNADO, TRAITOR, TROLL, TUSKS_OF_APEDEMAK, TWILIGHT_OF_THE_GODS, TYR, ULLR, UNDERMINE, UNDERWORLD_PASSAGE, VALGALDR, VALKYRIE, VALLEY_OF_THE_KINGS, VALOR, VANISH, VAULTS_OF_EREBUS, VIBRANT_LAND, VIDAR, VIKINGS, VISION, VOLCANIC_FORGE, VORTEX, WADJET, WALKING_WOODS, WANYUDO, WATATSUMI, WAY_OF_THE_MOON_BUSHIDO, WAY_OF_THE_STORM_BUSHIDO, WAY_OF_THE_SUN_BUSHIDO, WEIGHTLESS_MACE, WILL_OF_KRONOS, WIND_SICKLES, WINGED_MESSENGER, WINTER_HARVEST, WISDOM_OF_NINE, WRATH_OF_THE_DEEP, XUANNU, XUANYUANS_BLOODLINE, YAZI, YDALIR, YIN_AND_YANG, YINGLONGS_WRATH, ZHUQUE, ZHURONG, } from "./units.js"

export const minorGodLaneMatrices = {

    amaterasu : [
            [SOLAR_SHIELD, WAY_OF_THE_SUN_BUSHIDO, KAGURA], // archaic_1  
            [], // archaic_2 
            [AME_NO_UZUME, GOSHINBOKU, KAMAITACHI, WIND_SICKLES, KATAGI, GOHEI_WANDS], // classical_1 
            [MINAKATATOMI, SHRINE_OF_THE_HUNT, WANYUDO, CONDEMNED_SOUL, SALTWATER_SPRING, HUNTERS_STRENGTH, KUMIKI], // classical_2
            [HACHIMAN, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
            [RAIJIN, THUNDER_BURST, RAIJU, THUNDEROUS_PRESENCE, DEN_DEN_DRUMS, HANNYA_MASK, HEAVENLY_BARRAGE], // heroic_2
            [TAKEMIKAZUCHI, DIVINE_SLASH, ASURA, BURNING_MALEVOLENCE, SUMO_TRAINING, TEN_FIST_SWORD, SOJUTSU], // heroic_3
            [OKUNINUSHI, SACRED_GATE, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
            [], // mythic_2
    ],

    tsukuyomi : [
            [NEW_MOON, WAY_OF_THE_MOON_BUSHIDO, TENSHU], // archaic_1  
            [], // archaic_2 
            [AME_NO_UZUME, GOSHINBOKU, KAMAITACHI, WIND_SICKLES, KATAGI, GOHEI_WANDS], // classical_1
            [INARI_OKAMI,SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
            [HACHIMAN, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
            [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_2
            [WATATSUMI, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO, ASYMMETRICAL_BOWS], // heroic_3
            [OKUNINUSHI, SACRED_GATE, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
            [], // mythic_2
    ],

    susanoo : [
            [KUSANAGI, WAY_OF_THE_STORM_BUSHIDO, CRUSHING_WAVES], // archaic_1  // change katagi to way of the storm
            [], // archaic_2 
            [MINAKATATOMI, SHRINE_OF_THE_HUNT, WANYUDO, CONDEMNED_SOUL, SALTWATER_SPRING, HUNTERS_STRENGTH, KUMIKI], // classical_1
            [INARI_OKAMI, SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
            [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_1
            [RAIJIN, THUNDER_BURST, RAIJU, THUNDEROUS_PRESENCE, DEN_DEN_DRUMS, HANNYA_MASK, HEAVENLY_BARRAGE], // heroic_2
            [TAKEMIKAZUCHI, DIVINE_SLASH, ASURA, BURNING_MALEVOLENCE, SUMO_TRAINING, TEN_FIST_SWORD, SOJUTSU], // heroic_3
            [WATATSUMI, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO, ASYMMETRICAL_BOWS], // mythic_1
            [], // mythic_2
    ],

    fuxi : [
            [THE_PEACH_BLOSSOM_SPRING, YIN_AND_YANG, CELESTIAL_WEAPONS, TAI_CHI], 
            [], // archaic_2 
            [XUANNU, VANISH, QILIN, DIVINE_BOOKS, REINCARNATION, QILINS_BLESSING], // classical_1
            [CHIYOU, LIGHTNING_WEAPONS, YAZI, MASTER_OF_WEAPONRY, SPOILS_OF_WAR, SON_OF_LOONG, RAGE_OF_SLAUGHTER], // classical_2
            [GOUMANG, FOREST_PROTECTION, VIBRANT_LAND, HOOVES_OF_THE_WIND, FRENZIED_DASH, MAELSTROM], // heroic_1
            [NUBA, DROUGHT_SHIPS,TAOTIE, SCORCHING_FEATHERS, ROCK_SOLID, BOTTOMLESS_STOMACH, DROUGHT_SHIPS], // heroic_2
            [GONGGONG, GREAT_FLOOD, QINGLONG, SHAKER_OF_HEAVEN, TEMPESTUOUS_STORM, LAST_STAND, RISING_TIDE], // heroic_3
            [HUANGDI, YINGLONGS_WRATH, HUNDUN, XUANYUANS_BLOODLINE, LEIZUS_SILK, IMPERIAL_ORDER, POWER_OF_CHAOS], // mythic_1
            [], // mythic_2
    ],

    nuwa : [
            [CREATION, CREATORS_AUSPICE_GOD_BLESSING, KUAFU_CHIEFTAIN, MOUNTAINOUS_MIGHT],
            [], // archaic_2 
            [XUANNU, VANISH, QILIN, DIVINE_BOOKS, REINCARNATION, QILINS_BLESSING], // classical_1
            [HOUTU, EARTH_WALL, QIONGQI, ADVANCED_DEFENSES, CHASING_THE_SUN, ABUNDANCE, SINISTER_DEFIANCE], // classical_2
            [GOUMANG, FOREST_PROTECTION, VIBRANT_LAND, HOOVES_OF_THE_WIND, FRENZIED_DASH, MAELSTROM], // heroic_1
            [RUSHOU, FEI_BEASTS, BAIHU, PIXIU, GILDED_SHIELDS, DIVINE_JUDGMENT, AUTUMN_OF_ABUNDANCE, RED_CLIFFS_FLEET], // heroic_2
            [GONGGONG, GREAT_FLOOD, QINGLONG, SHAKER_OF_HEAVEN, TEMPESTUOUS_STORM, LAST_STAND, RISING_TIDE], // heroic_3
            [ZHURONG, BLAZING_PRAIRIE, ZHUQUE, FLAMING_BLOOD, SLASH_AND_BURN, SONG_OF_MIDSUMMER, SOUTHERN_FIRE], // mythic_1
            [], // mythic_2
    ],

    shennong : [
            [PROSPEROUS_SEEDS, GIFT_OF_BEASTS_GOD_BLESSING, HERBAL_MEDICINE, PEACH_OF_IMMORTALITY],
            [], // archaic_2 
            [HOUTU, EARTH_WALL, QIONGQI, ADVANCED_DEFENSES, CHASING_THE_SUN, ABUNDANCE, SINISTER_DEFIANCE], // classical_1
            [CHIYOU, LIGHTNING_WEAPONS, YAZI, MASTER_OF_WEAPONRY, SPOILS_OF_WAR, SON_OF_LOONG, RAGE_OF_SLAUGHTER], // classical_2
            [RUSHOU, FEI_BEASTS, BAIHU, PIXIU, GILDED_SHIELDS, DIVINE_JUDGMENT, AUTUMN_OF_ABUNDANCE, RED_CLIFFS_FLEET], // heroic_1
            [NUBA, DECONSTRUCTION,TAOTIE, SCORCHING_FEATHERS, ROCK_SOLID, BOTTOMLESS_STOMACH, DROUGHT_SHIPS], // heroic_2
            [ZHURONG, BLAZING_PRAIRIE, ZHUQUE, FLAMING_BLOOD, SLASH_AND_BURN, SONG_OF_MIDSUMMER, SOUTHERN_FIRE], // heroic_3
            [HUANGDI, YINGLONGS_WRATH, HUNDUN, XUANYUANS_BLOODLINE, LEIZUS_SILK, IMPERIAL_ORDER, POWER_OF_CHAOS], // mythic_1
            [], // mythic_2
    ],

    zeus : [
            [BOLT, OLYMPIAN_PARENTAGE], // archaic_1
            [], // archaic_2
            [ATHENA, RESTORATION, MINOTAUR, LABYRINTH_OF_MINOS, AEGIS_SHIELD, SARISSA], // classical_1
            [HERMES, CEASEFIRE, CENTAUR, SYLVAN_LORE, SPIRITED_CHARGE, WINGED_MESSENGER], // classical_2
            [APOLLO, UNDERWORLD_PASSAGE, MANTICORE, ORACLE, TEMPLE_OF_HEALING, SUN_RAY, ANASTROPHE], // heroic_1
            [DIONYSUS,BRONZE, HYDRA, CHTHONIC_RITES, DIONYSIA, THRACIAN_HORSES], // heroic_2
            [HEPHAESTUS, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
            [HERA, LIGHTNING_STORM, MEDUSA, ARGIVE_PATRONAGE, FACE_OF_THE_GORGON, MONSTROUS_RAGE], // mythic_1
            [], // mythic_2
    ],

    hades : [
            [BOLT, SHAFTS_OF_PLAGUE, VAULTS_OF_EREBUS], // archaic_1 // need to change SENTINEL to type = tech, bolt is placeholder to prevent error
            [], // archaic_2
            [ATHENA, RESTORATION, MINOTAUR, LABYRINTH_OF_MINOS, AEGIS_SHIELD, SARISSA], // classical_1
            [ARES, PESTILENCE, CYCLOPS, PHOBOS_SPEAR_OF_PANIC, WILL_OF_KRONOS, ENYOS_BOW_OF_HORROR, DEIMOS_SWORD_OF_DREAD], // classical_2
            [APOLLO, UNDERWORLD_PASSAGE, MANTICORE, ORACLE, TEMPLE_OF_HEALING, SUN_RAY, ANASTROPHE], // heroic_1
            [APHRODITE, CURSE, NEMEAN_LION, GOLDEN_APPLES, DIVINE_BLOOD, ROAR_OF_ORTHUS, ARGONAUTS], // heroic_2
            [HEPHAESTUS, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
            [ARTEMIS, EARTHQUAKE, CHIMERA, FLAMES_OF_TYPHON, SHAFTS_OF_PLAGUE, BEAST_SLAYER], // mythic_1
            [], // mythic_2
    ],

    poseidon : [
            [LURE, HIPPOCAMPUS, MILITIA, LORD_OF_HORSES], // archaic_1
            [], // archaic_2
            [ARES, PESTILENCE, CYCLOPS, PHOBOS_SPEAR_OF_PANIC, WILL_OF_KRONOS, ENYOS_BOW_OF_HORROR, DEIMOS_SWORD_OF_DREAD], // classical_1
            [HERMES, CEASEFIRE, CENTAUR, SYLVAN_LORE, SPIRITED_CHARGE, WINGED_MESSENGER], // classical_2
            [APHRODITE, CURSE, NEMEAN_LION, GOLDEN_APPLES, DIVINE_BLOOD, ROAR_OF_ORTHUS, ARGONAUTS], // heroic_1
            [APOLLO, UNDERWORLD_PASSAGE, MANTICORE, ORACLE, TEMPLE_OF_HEALING, SUN_RAY, ANASTROPHE], // heroic_2
            [HEPHAESTUS, PLENTY, COLOSSUS, HAND_OF_TALOS, SHOULDER_OF_TALOS, FORGE_OF_OLYMPUS, OLYMPIAN_WEAPONS], // heroic_3
            [ARTEMIS, EARTHQUAKE, CHIMERA, FLAMES_OF_TYPHON, SHAFTS_OF_PLAGUE, BEAST_SLAYER], // mythic_1
            [], // mythic_2
    ],

    ra:[
            [RAIN, SKIN_OF_THE_RHINO], // archaic_1
            [], // archaic_2
            [BAST, ECLIPSE, SPHINX, SACRED_CATS, ADZE_OF_WEPWAWET, CRIOSPHINX, HIERACOSPHINX], // classical_1
            [PTAH, SHIFTING_SANDS, WADJET, SCALLOPED_AXE, LEATHER_FRAME_SHIELD, ELECTRUM_BULLETS, SHADUF], // classical_2
            [SOBEK_HATHOR, LOCUST_SWARM, ROC, PETSUCHOS, CROCODILOPOLIS, SUN_DRIED_MUD_BRICK, DARK_WATER, SOLAR_BARQUE], // heroic_1
            [SEKHMET, CITADEL, SCARAB, BONE_BOW, SLINGS_OF_THE_SUN, CRIMSON_LINEN, FORCE_OF_THE_WEST_WIND], // heroic_2
            [OSIRIS, SON_OF_OSIRIS, MUMMY, DESERT_WIND, NEW_KINGDOM, ATEF_CROWN], // heroic_3
            [HORUS, TORNADO, AVENGER, AXE_OF_VENGEANCE, SPEAR_OF_HORUS, GREATEST_OF_FIFTY], // mythic_1
            [], // mythic_2
    ],

    isis:[
            [PROSPERITY, FLOOD_OF_THE_NILE], // archaic_1
            [], // archaic_2
            [BAST, ECLIPSE, SPHINX, SACRED_CATS, ADZE_OF_WEPWAWET, CRIOSPHINX, HIERACOSPHINX], // classical_1
            [ANUBIS, PLAGUE_OF_SERPENTS, ANUBITE, FEET_OF_THE_JACKAL, SERPENT_SPEAR, NECROPOLIS], // classical_2
            [SOBEK_HATHOR, LOCUST_SWARM, ROC, PETSUCHOS, CROCODILOPOLIS, SUN_DRIED_MUD_BRICK, DARK_WATER, SOLAR_BARQUE], // heroic_1
            [NEPHTHYS, ANCESTORS, SCORPION_MAN, FUNERAL_RITES, SPIRIT_OF_MAAT, NEBTY, FUNERAL_BARGE], // heroic_2
            [OSIRIS, SON_OF_OSIRIS, MUMMY, DESERT_WIND, NEW_KINGDOM, ATEF_CROWN], // heroic_3
            [THOTH, METEOR, PHOENIX, VALLEY_OF_THE_KINGS, BOOK_OF_THOTH, TUSKS_OF_APEDEMAK], // mythic_1
            [], // mythic_2
    ],

    set:[
            [VISION, BATTLE_BOAR, CLAIRVOYANCE], // archaic_1 
            [], // archaic_2
            [ANUBIS, PLAGUE_OF_SERPENTS, ANUBITE, FEET_OF_THE_JACKAL, SERPENT_SPEAR, NECROPOLIS], // classical_1
            [PTAH, SHIFTING_SANDS, WADJET, SCALLOPED_AXE, LEATHER_FRAME_SHIELD, ELECTRUM_BULLETS, SHADUF], // classical_2
            [SOBEK_HATHOR, LOCUST_SWARM, ROC, PETSUCHOS, CROCODILOPOLIS, SUN_DRIED_MUD_BRICK, DARK_WATER, SOLAR_BARQUE], // heroic_1
            [NEPHTHYS, ANCESTORS, SCORPION_MAN, FUNERAL_RITES, SPIRIT_OF_MAAT, NEBTY, FUNERAL_BARGE], // heroic_2
            [THOTH, METEOR, PHOENIX, VALLEY_OF_THE_KINGS, BOOK_OF_THOTH, TUSKS_OF_APEDEMAK], // heroic_3
            [HORUS, TORNADO, AVENGER, AXE_OF_VENGEANCE, SPEAR_OF_HORUS, GREATEST_OF_FIFTY], // mythic_1
            [], // mythic_2
    ],

    thor: [
            [GULLINBURSTI, DWARVEN_ARMORY, HAMMER_OF_THUNDER], // archaic_1 //DWARVEN_MINE is type=tech need to change to god power
            [], // archaic_2
            [FREYJA, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
            [FORSETI, HEALING_SPRING, TROLL, HALL_OF_THANES, DWARVEN_BREASTPLATE, CAVE_TROLL], // classical_2
            [SKADI, FROST, FROST_GIANT, RIME, HUNTRESS_AXE, WINTER_HARVEST, ARCTIC_WINDS], // heroic_1
            [BRAGI, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_2
            [BALDR, RAGNAROK, FIRE_GIANT, SONS_OF_SLEIPNIR, DWARVEN_AUGER], // heroic_3
            [TYR, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
            [], // mythic_2
    ],

    odin: [
        [GREAT_HUNT, RAVEN, HAMASK], // archaic_1
        [], // archaic_2
        [FREYJA, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
        [HEIMDALL, UNDERMINE, EINHERI, GJALLARHORN, SAFEGUARD, RIGSTHULA], // classical_2
        [SKADI, FROST, FROST_GIANT, RIME, HUNTRESS_AXE, WINTER_HARVEST, ARCTIC_WINDS], // heroic_1
        [NJORD, WALKING_WOODS, MOUNTAIN_GIANT, RING_GIVER, VIKINGS, JOTUNS, WRATH_OF_THE_DEEP], // heroic_2
        [BALDR, RAGNAROK, FIRE_GIANT, SONS_OF_SLEIPNIR, DWARVEN_AUGER], // heroic_3
        [TYR, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
        [], // mythic_2
    ],

    loki: [
            [SPY, EYES_IN_THE_FOREST], // archaic_1
            [], // archaic_2
            [FORSETI, HEALING_SPRING, TROLL, HALL_OF_THANES, DWARVEN_BREASTPLATE, CAVE_TROLL], // classical_1
            [HEIMDALL, UNDERMINE, EINHERI, GJALLARHORN, SAFEGUARD, RIGSTHULA], // classical_2
            [BRAGI, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_1
            [NJORD, WALKING_WOODS, MOUNTAIN_GIANT, RING_GIVER, VIKINGS, JOTUNS, WRATH_OF_THE_DEEP], // heroic_2
            [HEL, NIDHOGG, FIRE_GIANT, FROST_GIANT, MOUNTAIN_GIANT, RAMPAGE, GRANITE_BLOOD], // heroic_3
            [TYR, FIMBULWINTER, FENRIS_WOLF_BROOD, BERSERKERGANG, BRAVERY], // mythic_1
            [], // mythic_2
    ],

     
    freyr : [
            [GULLINBURSTI, FREYRS_GIFT], // archaic_1
            [], // archaic_2
            [FREYJA, FOREST_FIRE, VALKYRIE, DISABLOT, THUNDERING_HOOVES, SESSRUMNIR], // classical_1
            [ULLR, ASGARDIAN_BASTION, DRAUGR, VALGALDR, SERVANTS_OF_GLORY, RING_OATH, YDALIR], // classical_2
            [BRAGI, FLAMING_WEAPONS, BATTLE_BOAR, CALL_OF_VALHALLA, THURISAZ_RUNE, SWINE_ARRAY, LONG_SERPENT], // heroic_1
            [AEGIR, TEMPEST, ROCK_GIANT, GRANITE_MAW, FEASTS_OF_RENOWN, NINE_WAVES, GRASP_OF_RAN], // heroic_2
            [HEL, NIDHOGG, FIRE_GIANT, FROST_GIANT, MOUNTAIN_GIANT, RAMPAGE, GRANITE_BLOOD], // heroic_3
            [VIDAR, INFERNO, FAFNIR, TWILIGHT_OF_THE_GODS, AVENGING_SPIRIT, SILENT_RESOLVE, FURY_OF_THE_FALLEN], // mythic_1
            [], // mythic_2
    ],

    kronos: [
            [DECONSTRUCTION, TEMPORAL_CHAOS], // archaic_1
            [], // archaic_2
            [PROMETHEUS, VALOR, PROMETHEAN, ALLUVIAL_CLAY, HEART_OF_THE_TITANS, THEFT_OF_FIRE], // classical_1
            [LETO, SPIDER_LAIR, AUTOMATON, HEPHAESTUS_REVENGE, VOLCANIC_FORGE, PERCEPTION], // classical_2
            [HYPERION, CHAOS, SATYR, GEMINI, HEROIC_RENEWAL, SONS_OF_THE_SUN, PIONEER_OF_THE_SKIES], // heroic_1
            [RHEIA, TRAITOR, BEHEMOTH, HORNS_OF_CONSECRATION, ORICHALCUM_MAIL, RHEIAS_GIFT, DAKTYLOI], // heroic_2
            [HELIOS, VORTEX, CENTIMANUS, MIRROR_TOWER, HALO_OF_THE_SUN, PETRIFICATION, TITANOMACHY], // heroic_3
            [ATLAS, IMPLODE, ARGUS, GUARDIAN_OF_IO, DEVOTEES_OF_ATLAS, TITAN_SHIELD], // mythic_1
            [], // mythic_2
    ],

    oranos : [
            [SHOCKWAVE, SKY_PASSAGE, EMPYRIAN_SPEED], // archaic_1
            [], // archaic_2
            [PROMETHEUS, VALOR, PROMETHEAN, ALLUVIAL_CLAY, HEART_OF_THE_TITANS, THEFT_OF_FIRE], // classical_1
            [OCEANUS, CARNIVORA, CALADRIA, SERVANT, BITE_OF_THE_SHARK, WEIGHTLESS_MACE, FRONTLINE_HEROICS], // classical_2
            [HYPERION, CHAOS, SATYR, GEMINI, HEROIC_RENEWAL, SONS_OF_THE_SUN, PIONEER_OF_THE_SKIES], // heroic_1
            [THEIA, HESPERIDES_TREE, STYMPHALIAN_BIRD, DRYAD, PROPHETIC_SIGHT, POSEIDONS_SECRET, LANCE_OF_STONE, DAUGHTERS_OF_THE_SEA], // heroic_2
            [HELIOS, VORTEX, CENTIMANUS, MIRROR_TOWER, HALO_OF_THE_SUN, PETRIFICATION, TITANOMACHY], // heroic_3
            [HEKATE, TARTARIAN_GATE, LAMPADES, ASPER_BLOOD, MYTHIC_REJUVENATION, CELERITY], // mythic_1
            [], // mythic_2
    ],

    gaia : [
            [GAIA_FOREST, CHANNELS], // archaic_1
            [], // archaic_2
            [OCEANUS, CARNIVORA, CALADRIA, SERVANT, BITE_OF_THE_SHARK, WEIGHTLESS_MACE, FRONTLINE_HEROICS], // classical_1
            [LETO, SPIDER_LAIR, AUTOMATON, HEPHAESTUS_REVENGE, VOLCANIC_FORGE, PERCEPTION], // classical_2
            [THEIA, HESPERIDES_TREE, STYMPHALIAN_BIRD, DRYAD, PROPHETIC_SIGHT, POSEIDONS_SECRET, LANCE_OF_STONE, DAUGHTERS_OF_THE_SEA], // heroic_1
            [RHEIA, TRAITOR, BEHEMOTH, HORNS_OF_CONSECRATION, ORICHALCUM_MAIL, RHEIAS_GIFT, DAKTYLOI], // heroic_2
            [HEKATE, TARTARIAN_GATE, LAMPADES, ASPER_BLOOD, MYTHIC_REJUVENATION, CELERITY], // heroic_3
            [ATLAS, IMPLODE, ARGUS, GUARDIAN_OF_IO, DEVOTEES_OF_ATLAS, TITAN_SHIELD], // mythic_1
            [], // mythic_2
    ],

}



    

    
    

    


    
    
    // TSUKUYOMI

    // minorGodLaneMatrix = [
    //         [NEW_MOON, KATAGI, TENSHU], // archaic_1  
    //         [], // archaic_2 
    //         [AME_NO_UZUME, GOSHINBOKU, AUTOMATON, WIND_SICKLES, KATAGI, GOHEI_WANDS], // classical_1
    //         [SWAMPLAND, JOROGUMO, DEADLY_SNARE, WISDOM_OF_NINE, SASHIMONO_BANNERMEN, IVORY_NETSUKE], // classical_2
    //         [HACHIMAN, SHOGUN, TENGU, ASCETIC_PRACTICES, GOLDEN_KITE, EIGHT_BANNERS, DAN_NO_URA_TACTICS], // heroic_1
    //         [FUJIN, SMITING_GUST, ONI, DEADLY_RAGE, ONI_MASK, GALES_FURY], // heroic_2
    //         [WATATSUMI, DRAGON_TYPHOON, SHINIGAMI, ETERNAL_HAUNTING, SEASIDE_INFILTRATORS, ONMYODO,], // heroic_3
    //         [OKUNINUSHI, SACRED_GATE, ONMORAKI, RESTLESS_ARMY, DIVINE_PREFECTURE, MECHANICAL_ARTISANS], // mythic_1
    //         [], // mythic_2
    // ];

    